// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/inventory/v1/inventory.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryAPI_UserListProductVariantInventoryFilter_FullMethodName  = "/api.inventory.v1.InventoryAPI/UserListProductVariantInventoryFilter"
	InventoryAPI_UserListProductVariantInventory_FullMethodName        = "/api.inventory.v1.InventoryAPI/UserListProductVariantInventory"
	InventoryAPI_UserListProductVariantInventoryHistory_FullMethodName = "/api.inventory.v1.InventoryAPI/UserListProductVariantInventoryHistory"
)

// InventoryAPIClient is the client API for InventoryAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryAPI is a service that provides inventory management for products.
// Listing	Show list of created variants, with pagination, sort by columns: variant name, sku, available, buying, on-order
// Listing	Filter	Allow filtering by fields: variant name, sku, catalog
// Listing	History	Allow viewing in/out history of variant
type InventoryAPIClient interface {
	UserListProductVariantInventoryFilter(ctx context.Context, in *UserListProductVariantInventoryFilterRequest, opts ...grpc.CallOption) (*UserListProductVariantInventoryFilterResponse, error)
	UserListProductVariantInventory(ctx context.Context, in *UserListProductVariantInventoryRequest, opts ...grpc.CallOption) (*UserListProductVariantInventoryResponse, error)
	UserListProductVariantInventoryHistory(ctx context.Context, in *UserListProductVariantInventoryHistoryRequest, opts ...grpc.CallOption) (*UserListProductVariantInventoryHistoryResponse, error)
}

type inventoryAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryAPIClient(cc grpc.ClientConnInterface) InventoryAPIClient {
	return &inventoryAPIClient{cc}
}

func (c *inventoryAPIClient) UserListProductVariantInventoryFilter(ctx context.Context, in *UserListProductVariantInventoryFilterRequest, opts ...grpc.CallOption) (*UserListProductVariantInventoryFilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListProductVariantInventoryFilterResponse)
	err := c.cc.Invoke(ctx, InventoryAPI_UserListProductVariantInventoryFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryAPIClient) UserListProductVariantInventory(ctx context.Context, in *UserListProductVariantInventoryRequest, opts ...grpc.CallOption) (*UserListProductVariantInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListProductVariantInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryAPI_UserListProductVariantInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryAPIClient) UserListProductVariantInventoryHistory(ctx context.Context, in *UserListProductVariantInventoryHistoryRequest, opts ...grpc.CallOption) (*UserListProductVariantInventoryHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListProductVariantInventoryHistoryResponse)
	err := c.cc.Invoke(ctx, InventoryAPI_UserListProductVariantInventoryHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryAPIServer is the server API for InventoryAPI service.
// All implementations should embed UnimplementedInventoryAPIServer
// for forward compatibility.
//
// InventoryAPI is a service that provides inventory management for products.
// Listing	Show list of created variants, with pagination, sort by columns: variant name, sku, available, buying, on-order
// Listing	Filter	Allow filtering by fields: variant name, sku, catalog
// Listing	History	Allow viewing in/out history of variant
type InventoryAPIServer interface {
	UserListProductVariantInventoryFilter(context.Context, *UserListProductVariantInventoryFilterRequest) (*UserListProductVariantInventoryFilterResponse, error)
	UserListProductVariantInventory(context.Context, *UserListProductVariantInventoryRequest) (*UserListProductVariantInventoryResponse, error)
	UserListProductVariantInventoryHistory(context.Context, *UserListProductVariantInventoryHistoryRequest) (*UserListProductVariantInventoryHistoryResponse, error)
}

// UnimplementedInventoryAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryAPIServer struct{}

func (UnimplementedInventoryAPIServer) UserListProductVariantInventoryFilter(context.Context, *UserListProductVariantInventoryFilterRequest) (*UserListProductVariantInventoryFilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListProductVariantInventoryFilter not implemented")
}
func (UnimplementedInventoryAPIServer) UserListProductVariantInventory(context.Context, *UserListProductVariantInventoryRequest) (*UserListProductVariantInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListProductVariantInventory not implemented")
}
func (UnimplementedInventoryAPIServer) UserListProductVariantInventoryHistory(context.Context, *UserListProductVariantInventoryHistoryRequest) (*UserListProductVariantInventoryHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListProductVariantInventoryHistory not implemented")
}
func (UnimplementedInventoryAPIServer) testEmbeddedByValue() {}

// UnsafeInventoryAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryAPIServer will
// result in compilation errors.
type UnsafeInventoryAPIServer interface {
	mustEmbedUnimplementedInventoryAPIServer()
}

func RegisterInventoryAPIServer(s grpc.ServiceRegistrar, srv InventoryAPIServer) {
	// If the following call pancis, it indicates UnimplementedInventoryAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryAPI_ServiceDesc, srv)
}

func _InventoryAPI_UserListProductVariantInventoryFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListProductVariantInventoryFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAPIServer).UserListProductVariantInventoryFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAPI_UserListProductVariantInventoryFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAPIServer).UserListProductVariantInventoryFilter(ctx, req.(*UserListProductVariantInventoryFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryAPI_UserListProductVariantInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListProductVariantInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAPIServer).UserListProductVariantInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAPI_UserListProductVariantInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAPIServer).UserListProductVariantInventory(ctx, req.(*UserListProductVariantInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryAPI_UserListProductVariantInventoryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListProductVariantInventoryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAPIServer).UserListProductVariantInventoryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAPI_UserListProductVariantInventoryHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAPIServer).UserListProductVariantInventoryHistory(ctx, req.(*UserListProductVariantInventoryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryAPI_ServiceDesc is the grpc.ServiceDesc for InventoryAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.inventory.v1.InventoryAPI",
	HandlerType: (*InventoryAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserListProductVariantInventoryFilter",
			Handler:    _InventoryAPI_UserListProductVariantInventoryFilter_Handler,
		},
		{
			MethodName: "UserListProductVariantInventory",
			Handler:    _InventoryAPI_UserListProductVariantInventory_Handler,
		},
		{
			MethodName: "UserListProductVariantInventoryHistory",
			Handler:    _InventoryAPI_UserListProductVariantInventoryHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/inventory/v1/inventory.proto",
}
