// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/support/v1/internal_vendor_support.proto

package supportv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalVendorSupportAPI_InternalVendorListSupportRequest_FullMethodName         = "/api.support.v1.InternalVendorSupportAPI/InternalVendorListSupportRequest"
	InternalVendorSupportAPI_InternalVendorCreateSupportRequest_FullMethodName       = "/api.support.v1.InternalVendorSupportAPI/InternalVendorCreateSupportRequest"
	InternalVendorSupportAPI_InternalLegacyVendorListSupportRequest_FullMethodName   = "/api.support.v1.InternalVendorSupportAPI/InternalLegacyVendorListSupportRequest"
	InternalVendorSupportAPI_InternalLegacyVendorCreateSupportRequest_FullMethodName = "/api.support.v1.InternalVendorSupportAPI/InternalLegacyVendorCreateSupportRequest"
)

// InternalVendorSupportAPIClient is the client API for InternalVendorSupportAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalVendorSupportAPI is the team-scoped internal API the integration
// gateway calls. It mirrors the InternalVendorOrderAPI pattern: the gateway
// extracts the team_id (and, for writes, the acting user) from the vendor's
// API key and passes them explicitly here.
type InternalVendorSupportAPIClient interface {
	InternalVendorListSupportRequest(ctx context.Context, in *InternalVendorListSupportRequestRequest, opts ...grpc.CallOption) (*ListSupportRequestResponse, error)
	InternalVendorCreateSupportRequest(ctx context.Context, in *InternalVendorCreateSupportRequestRequest, opts ...grpc.CallOption) (*CreateSupportRequestResponse, error)
	InternalLegacyVendorListSupportRequest(ctx context.Context, in *InternalLegacyVendorListSupportRequestRequest, opts ...grpc.CallOption) (*LegacyListSupportRequestResponse, error)
	InternalLegacyVendorCreateSupportRequest(ctx context.Context, in *InternalLegacyVendorCreateSupportRequestRequest, opts ...grpc.CallOption) (*LegacyCreateSupportRequestResponse, error)
}

type internalVendorSupportAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalVendorSupportAPIClient(cc grpc.ClientConnInterface) InternalVendorSupportAPIClient {
	return &internalVendorSupportAPIClient{cc}
}

func (c *internalVendorSupportAPIClient) InternalVendorListSupportRequest(ctx context.Context, in *InternalVendorListSupportRequestRequest, opts ...grpc.CallOption) (*ListSupportRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupportRequestResponse)
	err := c.cc.Invoke(ctx, InternalVendorSupportAPI_InternalVendorListSupportRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalVendorSupportAPIClient) InternalVendorCreateSupportRequest(ctx context.Context, in *InternalVendorCreateSupportRequestRequest, opts ...grpc.CallOption) (*CreateSupportRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSupportRequestResponse)
	err := c.cc.Invoke(ctx, InternalVendorSupportAPI_InternalVendorCreateSupportRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalVendorSupportAPIClient) InternalLegacyVendorListSupportRequest(ctx context.Context, in *InternalLegacyVendorListSupportRequestRequest, opts ...grpc.CallOption) (*LegacyListSupportRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LegacyListSupportRequestResponse)
	err := c.cc.Invoke(ctx, InternalVendorSupportAPI_InternalLegacyVendorListSupportRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalVendorSupportAPIClient) InternalLegacyVendorCreateSupportRequest(ctx context.Context, in *InternalLegacyVendorCreateSupportRequestRequest, opts ...grpc.CallOption) (*LegacyCreateSupportRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LegacyCreateSupportRequestResponse)
	err := c.cc.Invoke(ctx, InternalVendorSupportAPI_InternalLegacyVendorCreateSupportRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalVendorSupportAPIServer is the server API for InternalVendorSupportAPI service.
// All implementations should embed UnimplementedInternalVendorSupportAPIServer
// for forward compatibility.
//
// InternalVendorSupportAPI is the team-scoped internal API the integration
// gateway calls. It mirrors the InternalVendorOrderAPI pattern: the gateway
// extracts the team_id (and, for writes, the acting user) from the vendor's
// API key and passes them explicitly here.
type InternalVendorSupportAPIServer interface {
	InternalVendorListSupportRequest(context.Context, *InternalVendorListSupportRequestRequest) (*ListSupportRequestResponse, error)
	InternalVendorCreateSupportRequest(context.Context, *InternalVendorCreateSupportRequestRequest) (*CreateSupportRequestResponse, error)
	InternalLegacyVendorListSupportRequest(context.Context, *InternalLegacyVendorListSupportRequestRequest) (*LegacyListSupportRequestResponse, error)
	InternalLegacyVendorCreateSupportRequest(context.Context, *InternalLegacyVendorCreateSupportRequestRequest) (*LegacyCreateSupportRequestResponse, error)
}

// UnimplementedInternalVendorSupportAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalVendorSupportAPIServer struct{}

func (UnimplementedInternalVendorSupportAPIServer) InternalVendorListSupportRequest(context.Context, *InternalVendorListSupportRequestRequest) (*ListSupportRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalVendorListSupportRequest not implemented")
}
func (UnimplementedInternalVendorSupportAPIServer) InternalVendorCreateSupportRequest(context.Context, *InternalVendorCreateSupportRequestRequest) (*CreateSupportRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalVendorCreateSupportRequest not implemented")
}
func (UnimplementedInternalVendorSupportAPIServer) InternalLegacyVendorListSupportRequest(context.Context, *InternalLegacyVendorListSupportRequestRequest) (*LegacyListSupportRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalLegacyVendorListSupportRequest not implemented")
}
func (UnimplementedInternalVendorSupportAPIServer) InternalLegacyVendorCreateSupportRequest(context.Context, *InternalLegacyVendorCreateSupportRequestRequest) (*LegacyCreateSupportRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalLegacyVendorCreateSupportRequest not implemented")
}
func (UnimplementedInternalVendorSupportAPIServer) testEmbeddedByValue() {}

// UnsafeInternalVendorSupportAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalVendorSupportAPIServer will
// result in compilation errors.
type UnsafeInternalVendorSupportAPIServer interface {
	mustEmbedUnimplementedInternalVendorSupportAPIServer()
}

func RegisterInternalVendorSupportAPIServer(s grpc.ServiceRegistrar, srv InternalVendorSupportAPIServer) {
	// If the following call pancis, it indicates UnimplementedInternalVendorSupportAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalVendorSupportAPI_ServiceDesc, srv)
}

func _InternalVendorSupportAPI_InternalVendorListSupportRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalVendorListSupportRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalVendorSupportAPIServer).InternalVendorListSupportRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalVendorSupportAPI_InternalVendorListSupportRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalVendorSupportAPIServer).InternalVendorListSupportRequest(ctx, req.(*InternalVendorListSupportRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalVendorSupportAPI_InternalVendorCreateSupportRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalVendorCreateSupportRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalVendorSupportAPIServer).InternalVendorCreateSupportRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalVendorSupportAPI_InternalVendorCreateSupportRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalVendorSupportAPIServer).InternalVendorCreateSupportRequest(ctx, req.(*InternalVendorCreateSupportRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalVendorSupportAPI_InternalLegacyVendorListSupportRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalLegacyVendorListSupportRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalVendorSupportAPIServer).InternalLegacyVendorListSupportRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalVendorSupportAPI_InternalLegacyVendorListSupportRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalVendorSupportAPIServer).InternalLegacyVendorListSupportRequest(ctx, req.(*InternalLegacyVendorListSupportRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalVendorSupportAPI_InternalLegacyVendorCreateSupportRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalLegacyVendorCreateSupportRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalVendorSupportAPIServer).InternalLegacyVendorCreateSupportRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalVendorSupportAPI_InternalLegacyVendorCreateSupportRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalVendorSupportAPIServer).InternalLegacyVendorCreateSupportRequest(ctx, req.(*InternalLegacyVendorCreateSupportRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalVendorSupportAPI_ServiceDesc is the grpc.ServiceDesc for InternalVendorSupportAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalVendorSupportAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.support.v1.InternalVendorSupportAPI",
	HandlerType: (*InternalVendorSupportAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalVendorListSupportRequest",
			Handler:    _InternalVendorSupportAPI_InternalVendorListSupportRequest_Handler,
		},
		{
			MethodName: "InternalVendorCreateSupportRequest",
			Handler:    _InternalVendorSupportAPI_InternalVendorCreateSupportRequest_Handler,
		},
		{
			MethodName: "InternalLegacyVendorListSupportRequest",
			Handler:    _InternalVendorSupportAPI_InternalLegacyVendorListSupportRequest_Handler,
		},
		{
			MethodName: "InternalLegacyVendorCreateSupportRequest",
			Handler:    _InternalVendorSupportAPI_InternalLegacyVendorCreateSupportRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/support/v1/internal_vendor_support.proto",
}
