// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/migration/v1/webhook_oms.proto

package migrationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookOMSIntegrationAPI_OrderAddressUpdated_FullMethodName = "/api.migration.v1.WebhookOMSIntegrationAPI/OrderAddressUpdated"
)

// WebhookOMSIntegrationAPIClient is the client API for WebhookOMSIntegrationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebhookOMSIntegrationAPIClient interface {
	OrderAddressUpdated(ctx context.Context, in *WebhookOrderAddressUpdatedRequest, opts ...grpc.CallOption) (*WebhookOrderAddressUpdatedResponse, error)
}

type webhookOMSIntegrationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookOMSIntegrationAPIClient(cc grpc.ClientConnInterface) WebhookOMSIntegrationAPIClient {
	return &webhookOMSIntegrationAPIClient{cc}
}

func (c *webhookOMSIntegrationAPIClient) OrderAddressUpdated(ctx context.Context, in *WebhookOrderAddressUpdatedRequest, opts ...grpc.CallOption) (*WebhookOrderAddressUpdatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookOrderAddressUpdatedResponse)
	err := c.cc.Invoke(ctx, WebhookOMSIntegrationAPI_OrderAddressUpdated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookOMSIntegrationAPIServer is the server API for WebhookOMSIntegrationAPI service.
// All implementations should embed UnimplementedWebhookOMSIntegrationAPIServer
// for forward compatibility.
type WebhookOMSIntegrationAPIServer interface {
	OrderAddressUpdated(context.Context, *WebhookOrderAddressUpdatedRequest) (*WebhookOrderAddressUpdatedResponse, error)
}

// UnimplementedWebhookOMSIntegrationAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookOMSIntegrationAPIServer struct{}

func (UnimplementedWebhookOMSIntegrationAPIServer) OrderAddressUpdated(context.Context, *WebhookOrderAddressUpdatedRequest) (*WebhookOrderAddressUpdatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderAddressUpdated not implemented")
}
func (UnimplementedWebhookOMSIntegrationAPIServer) testEmbeddedByValue() {}

// UnsafeWebhookOMSIntegrationAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookOMSIntegrationAPIServer will
// result in compilation errors.
type UnsafeWebhookOMSIntegrationAPIServer interface {
	mustEmbedUnimplementedWebhookOMSIntegrationAPIServer()
}

func RegisterWebhookOMSIntegrationAPIServer(s grpc.ServiceRegistrar, srv WebhookOMSIntegrationAPIServer) {
	// If the following call pancis, it indicates UnimplementedWebhookOMSIntegrationAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookOMSIntegrationAPI_ServiceDesc, srv)
}

func _WebhookOMSIntegrationAPI_OrderAddressUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebhookOrderAddressUpdatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookOMSIntegrationAPIServer).OrderAddressUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookOMSIntegrationAPI_OrderAddressUpdated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookOMSIntegrationAPIServer).OrderAddressUpdated(ctx, req.(*WebhookOrderAddressUpdatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookOMSIntegrationAPI_ServiceDesc is the grpc.ServiceDesc for WebhookOMSIntegrationAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookOMSIntegrationAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.migration.v1.WebhookOMSIntegrationAPI",
	HandlerType: (*WebhookOMSIntegrationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderAddressUpdated",
			Handler:    _WebhookOMSIntegrationAPI_OrderAddressUpdated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/migration/v1/webhook_oms.proto",
}
