openapi: 3.1.0
info:
  contact:
    email: engineering@gearment.com
    name: Gearment Engineering Team
    url: https://gearment.com
  license: {}
  termsOfService: "https://gearment.com/integration/api-terms-of-service.html"
  title: "common.type.v1"
  version: "3.0.0"
servers:
  - url: "https://api.dev.geadev.com/{serviceName}"
    description: "Staging Server"
    variables:
      serviceName:
        default: "iam"
        enum:
          - iam
          - product
          - seller
        description: "The service name"
  - url: "http://localhost:{servicePort}"
    description: "Local Server"
    variables:
      servicePort:
        default: "9000"
        description: "The port number"
paths: {}
components:
  schemas:
    common.type.v1.GeneralAddress:
      type: object
      properties:
        line1:
          type: string
          title: line1
          maxLength: 100
          minLength: 1
          additionalProperties: false
        line2:
          type: string
          title: line2
          maxLength: 30
          minLength: 1
          additionalProperties: false
        countryCode:
          type: string
          title: country_code
          maxLength: 3
          minLength: 2
          additionalProperties: false
        country:
          type: string
          title: country
          maxLength: 100
          minLength: 1
          additionalProperties: false
        regionCode:
          type: string
          title: region_code
          maxLength: 10
          minLength: 1
          additionalProperties: false
        region:
          type: string
          title: region
          maxLength: 100
          minLength: 1
          additionalProperties: false
        adminArea:
          type: string
          title: admin_area
          maxLength: 100
          additionalProperties: false
        locality:
          type: string
          title: locality
          maxLength: 100
          additionalProperties: false
        sublocality:
          type: string
          title: sublocality
          maxLength: 100
          additionalProperties: false
        firstName:
          type: string
          title: first_name
          maxLength: 100
          additionalProperties: false
        lastName:
          type: string
          title: last_name
          maxLength: 100
          additionalProperties: false
        phoneNo:
          type: string
          title: phone_no
          maxLength: 15
          pattern: ^(?:\+?\d{1,3})?[-.\s()]*\d{1,4}[-.\s()]*\d{1,4}[-.\s()]*\d{1,4}[-.\s()]*\d{1,9}$
          additionalProperties: false
        email:
          type: string
          title: email
          maxLength: 100
          format: email
          additionalProperties: false
        note:
          type: string
          title: note
          maxLength: 500
          additionalProperties: false
        postalCode:
          type: string
          title: postal_code
          maxLength: 50
          minLength: 5
          additionalProperties: false
      title: GeneralAddress
      additionalProperties: false
    common.type.v1.USAddress:
      type: object
      properties:
        street1:
          type: string
          title: street1
          maxLength: 255
          minLength: 1
          additionalProperties: false
        street2:
          type: string
          title: street2
          maxLength: 255
          additionalProperties: false
        countryCode:
          type: string
          title: country_code
          maxLength: 3
          minLength: 2
          additionalProperties: false
        country:
          type: string
          title: country
          maxLength: 100
          additionalProperties: false
        stateCode:
          type: string
          title: state_code
          maxLength: 10
          minLength: 1
          additionalProperties: false
        state:
          type: string
          title: state
          maxLength: 100
          additionalProperties: false
        city:
          type: string
          title: city
          maxLength: 100
          additionalProperties: false
        zipCode:
          type: string
          title: zip_code
          maxLength: 10
          minLength: 4
          additionalProperties: false
        firstName:
          type: string
          title: first_name
          maxLength: 100
          additionalProperties: false
        lastName:
          type: string
          title: last_name
          maxLength: 100
          additionalProperties: false
        phoneNo:
          type: string
          title: phone_no
          maxLength: 15
          pattern: ^(?:\+?\d{1,3})?[-.\s()]*\d{1,4}[-.\s()]*\d{1,4}[-.\s()]*\d{1,4}[-.\s()]*\d{1,9}$
          additionalProperties: false
        email:
          type: string
          title: email
          maxLength: 255
          pattern: ^$|^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$
          additionalProperties: false
        note:
          type: string
          title: note
          maxLength: 500
          additionalProperties: false
      title: USAddress
      additionalProperties: false
    connect.error:
      type: object
      properties:
        code:
          type: string
          examples:
            - CodeNotFound
          enum:
            - CodeCanceled
            - CodeUnknown
            - CodeInvalidArgument
            - CodeDeadlineExceeded
            - CodeNotFound
            - CodeAlreadyExists
            - CodePermissionDenied
            - CodeResourceExhausted
            - CodeFailedPrecondition
            - CodeAborted
            - CodeOutOfRange
            - CodeInternal
            - CodeUnavailable
            - CodeDataLoss
            - CodeUnauthenticated
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        detail:
          $ref: '#/components/schemas/google.protobuf.Any'
      title: Connect Error
      additionalProperties: true
      description: 'Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation'
    google.protobuf.Any:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
          format: binary
        debug:
          type: object
          additionalProperties: true
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      in: header
      name: Authorization
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    CookieAuth:
      type: apiKey
      scheme: bearer
      in: cookie
      name: accessToken
security: []
externalDocs:
  description: "Find out more about Gearment API v3"
  url: "https://gearment.com/integration/api-docs.html"
