openapi: 3.1.0
info:
  contact:
    email: engineering@gearment.com
    name: Gearment Engineering Team
    url: https://gearment.com
  license: {}
  termsOfService: "https://gearment.com/integration/api-terms-of-service.html"
  title: "common.type.v1"
  version: "3.0.0"
servers:
  - url: "https://api.dev.geadev.com/{serviceName}"
    description: "Staging Server"
    variables:
      serviceName:
        default: "iam"
        enum:
          - iam
          - product
          - seller
        description: "The service name"
  - url: "http://localhost:{servicePort}"
    description: "Local Server"
    variables:
      servicePort:
        default: "9000"
        description: "The port number"
paths: {}
components:
  schemas:
    common.type.v1.Money:
      type: object
      properties:
        currencyCode:
          type: string
          title: currency_code
          additionalProperties: false
          description: 'The three-letter currency code defined in ISO 4217. @gotags: mapstructure:"currency_code"'
        units:
          oneOf:
            - type: string
            - type: number
          title: units
          additionalProperties: false
          description: |-
            The whole units of the amount.
             For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar. @gotags: mapstructure:"units"
        nanos:
          type: integer
          title: nanos
          additionalProperties: false
          description: |-
            Number of nano (10^-9) units of the amount.
             The value must be between -999,999,999 and +999,999,999 inclusive.
             If `units` is positive, `nanos` must be positive or zero.
             If `units` is zero, `nanos` can be positive, zero, or negative.
             If `units` is negative, `nanos` must be negative or zero.
             For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000. @gotags: mapstructure:"nanos"
      title: Money
      additionalProperties: false
      description: Represents an amount of money with its currency type.
    connect.error:
      type: object
      properties:
        code:
          type: string
          examples:
            - CodeNotFound
          enum:
            - CodeCanceled
            - CodeUnknown
            - CodeInvalidArgument
            - CodeDeadlineExceeded
            - CodeNotFound
            - CodeAlreadyExists
            - CodePermissionDenied
            - CodeResourceExhausted
            - CodeFailedPrecondition
            - CodeAborted
            - CodeOutOfRange
            - CodeInternal
            - CodeUnavailable
            - CodeDataLoss
            - CodeUnauthenticated
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        detail:
          $ref: '#/components/schemas/google.protobuf.Any'
      title: Connect Error
      additionalProperties: true
      description: 'Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation'
    google.protobuf.Any:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
          format: binary
        debug:
          type: object
          additionalProperties: true
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      in: header
      name: Authorization
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    CookieAuth:
      type: apiKey
      scheme: bearer
      in: cookie
      name: accessToken
security: []
externalDocs:
  description: "Find out more about Gearment API v3"
  url: "https://gearment.com/integration/api-docs.html"
