// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/webhook/v1/vendor_webhook.proto

package webhookv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookAPI_RegisterNewWebhook_FullMethodName = "/api.webhook.v1.WebhookAPI/RegisterNewWebhook"
)

// WebhookAPIClient is the client API for WebhookAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebhookAPIClient interface {
	RegisterNewWebhook(ctx context.Context, in *RegisterNewWebhookRequest, opts ...grpc.CallOption) (*RegisterNewWebhookResponse, error)
}

type webhookAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookAPIClient(cc grpc.ClientConnInterface) WebhookAPIClient {
	return &webhookAPIClient{cc}
}

func (c *webhookAPIClient) RegisterNewWebhook(ctx context.Context, in *RegisterNewWebhookRequest, opts ...grpc.CallOption) (*RegisterNewWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNewWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookAPI_RegisterNewWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookAPIServer is the server API for WebhookAPI service.
// All implementations should embed UnimplementedWebhookAPIServer
// for forward compatibility.
type WebhookAPIServer interface {
	RegisterNewWebhook(context.Context, *RegisterNewWebhookRequest) (*RegisterNewWebhookResponse, error)
}

// UnimplementedWebhookAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookAPIServer struct{}

func (UnimplementedWebhookAPIServer) RegisterNewWebhook(context.Context, *RegisterNewWebhookRequest) (*RegisterNewWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNewWebhook not implemented")
}
func (UnimplementedWebhookAPIServer) testEmbeddedByValue() {}

// UnsafeWebhookAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookAPIServer will
// result in compilation errors.
type UnsafeWebhookAPIServer interface {
	mustEmbedUnimplementedWebhookAPIServer()
}

func RegisterWebhookAPIServer(s grpc.ServiceRegistrar, srv WebhookAPIServer) {
	// If the following call pancis, it indicates UnimplementedWebhookAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookAPI_ServiceDesc, srv)
}

func _WebhookAPI_RegisterNewWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNewWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookAPIServer).RegisterNewWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookAPI_RegisterNewWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookAPIServer).RegisterNewWebhook(ctx, req.(*RegisterNewWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookAPI_ServiceDesc is the grpc.ServiceDesc for WebhookAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.webhook.v1.WebhookAPI",
	HandlerType: (*WebhookAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNewWebhook",
			Handler:    _WebhookAPI_RegisterNewWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/webhook/v1/vendor_webhook.proto",
}
