// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/oms/v1/shipping.proto

package omsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalShippingAPI_InternalListOrderLabelsByOrdIDs_FullMethodName = "/api.oms.v1.InternalShippingAPI/InternalListOrderLabelsByOrdIDs"
	InternalShippingAPI_InternalPushTrackingInfoUpdates_FullMethodName = "/api.oms.v1.InternalShippingAPI/InternalPushTrackingInfoUpdates"
)

// InternalShippingAPIClient is the client API for InternalShippingAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalShippingAPIClient interface {
	InternalListOrderLabelsByOrdIDs(ctx context.Context, in *InternalListOrderLabelsByOrdIDsRequest, opts ...grpc.CallOption) (*InternalListOrderLabelsByOrdIDsResponse, error)
	InternalPushTrackingInfoUpdates(ctx context.Context, in *InternalPushTrackingInfoUpdatesRequest, opts ...grpc.CallOption) (*InternalPushTrackingInfoUpdatesResponse, error)
}

type internalShippingAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalShippingAPIClient(cc grpc.ClientConnInterface) InternalShippingAPIClient {
	return &internalShippingAPIClient{cc}
}

func (c *internalShippingAPIClient) InternalListOrderLabelsByOrdIDs(ctx context.Context, in *InternalListOrderLabelsByOrdIDsRequest, opts ...grpc.CallOption) (*InternalListOrderLabelsByOrdIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalListOrderLabelsByOrdIDsResponse)
	err := c.cc.Invoke(ctx, InternalShippingAPI_InternalListOrderLabelsByOrdIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalShippingAPIClient) InternalPushTrackingInfoUpdates(ctx context.Context, in *InternalPushTrackingInfoUpdatesRequest, opts ...grpc.CallOption) (*InternalPushTrackingInfoUpdatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalPushTrackingInfoUpdatesResponse)
	err := c.cc.Invoke(ctx, InternalShippingAPI_InternalPushTrackingInfoUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalShippingAPIServer is the server API for InternalShippingAPI service.
// All implementations should embed UnimplementedInternalShippingAPIServer
// for forward compatibility.
type InternalShippingAPIServer interface {
	InternalListOrderLabelsByOrdIDs(context.Context, *InternalListOrderLabelsByOrdIDsRequest) (*InternalListOrderLabelsByOrdIDsResponse, error)
	InternalPushTrackingInfoUpdates(context.Context, *InternalPushTrackingInfoUpdatesRequest) (*InternalPushTrackingInfoUpdatesResponse, error)
}

// UnimplementedInternalShippingAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalShippingAPIServer struct{}

func (UnimplementedInternalShippingAPIServer) InternalListOrderLabelsByOrdIDs(context.Context, *InternalListOrderLabelsByOrdIDsRequest) (*InternalListOrderLabelsByOrdIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalListOrderLabelsByOrdIDs not implemented")
}
func (UnimplementedInternalShippingAPIServer) InternalPushTrackingInfoUpdates(context.Context, *InternalPushTrackingInfoUpdatesRequest) (*InternalPushTrackingInfoUpdatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalPushTrackingInfoUpdates not implemented")
}
func (UnimplementedInternalShippingAPIServer) testEmbeddedByValue() {}

// UnsafeInternalShippingAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalShippingAPIServer will
// result in compilation errors.
type UnsafeInternalShippingAPIServer interface {
	mustEmbedUnimplementedInternalShippingAPIServer()
}

func RegisterInternalShippingAPIServer(s grpc.ServiceRegistrar, srv InternalShippingAPIServer) {
	// If the following call pancis, it indicates UnimplementedInternalShippingAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalShippingAPI_ServiceDesc, srv)
}

func _InternalShippingAPI_InternalListOrderLabelsByOrdIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalListOrderLabelsByOrdIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalShippingAPIServer).InternalListOrderLabelsByOrdIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalShippingAPI_InternalListOrderLabelsByOrdIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalShippingAPIServer).InternalListOrderLabelsByOrdIDs(ctx, req.(*InternalListOrderLabelsByOrdIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalShippingAPI_InternalPushTrackingInfoUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalPushTrackingInfoUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalShippingAPIServer).InternalPushTrackingInfoUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalShippingAPI_InternalPushTrackingInfoUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalShippingAPIServer).InternalPushTrackingInfoUpdates(ctx, req.(*InternalPushTrackingInfoUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalShippingAPI_ServiceDesc is the grpc.ServiceDesc for InternalShippingAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalShippingAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.oms.v1.InternalShippingAPI",
	HandlerType: (*InternalShippingAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalListOrderLabelsByOrdIDs",
			Handler:    _InternalShippingAPI_InternalListOrderLabelsByOrdIDs_Handler,
		},
		{
			MethodName: "InternalPushTrackingInfoUpdates",
			Handler:    _InternalShippingAPI_InternalPushTrackingInfoUpdates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/oms/v1/shipping.proto",
}
