// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/shipping/v1/shipping_external.proto

package shippingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShippingExternalAPI_ExternalUpdateShippingTracking_FullMethodName = "/api.shipping.v1.ShippingExternalAPI/ExternalUpdateShippingTracking"
)

// ShippingExternalAPIClient is the client API for ShippingExternalAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShippingExternalAPIClient interface {
	ExternalUpdateShippingTracking(ctx context.Context, in *ExternalUpdateShippingTrackingRequest, opts ...grpc.CallOption) (*ExternalUpdateShippingTrackingResponse, error)
}

type shippingExternalAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingExternalAPIClient(cc grpc.ClientConnInterface) ShippingExternalAPIClient {
	return &shippingExternalAPIClient{cc}
}

func (c *shippingExternalAPIClient) ExternalUpdateShippingTracking(ctx context.Context, in *ExternalUpdateShippingTrackingRequest, opts ...grpc.CallOption) (*ExternalUpdateShippingTrackingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalUpdateShippingTrackingResponse)
	err := c.cc.Invoke(ctx, ShippingExternalAPI_ExternalUpdateShippingTracking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingExternalAPIServer is the server API for ShippingExternalAPI service.
// All implementations should embed UnimplementedShippingExternalAPIServer
// for forward compatibility.
type ShippingExternalAPIServer interface {
	ExternalUpdateShippingTracking(context.Context, *ExternalUpdateShippingTrackingRequest) (*ExternalUpdateShippingTrackingResponse, error)
}

// UnimplementedShippingExternalAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShippingExternalAPIServer struct{}

func (UnimplementedShippingExternalAPIServer) ExternalUpdateShippingTracking(context.Context, *ExternalUpdateShippingTrackingRequest) (*ExternalUpdateShippingTrackingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExternalUpdateShippingTracking not implemented")
}
func (UnimplementedShippingExternalAPIServer) testEmbeddedByValue() {}

// UnsafeShippingExternalAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShippingExternalAPIServer will
// result in compilation errors.
type UnsafeShippingExternalAPIServer interface {
	mustEmbedUnimplementedShippingExternalAPIServer()
}

func RegisterShippingExternalAPIServer(s grpc.ServiceRegistrar, srv ShippingExternalAPIServer) {
	// If the following call pancis, it indicates UnimplementedShippingExternalAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShippingExternalAPI_ServiceDesc, srv)
}

func _ShippingExternalAPI_ExternalUpdateShippingTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalUpdateShippingTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingExternalAPIServer).ExternalUpdateShippingTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingExternalAPI_ExternalUpdateShippingTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingExternalAPIServer).ExternalUpdateShippingTracking(ctx, req.(*ExternalUpdateShippingTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShippingExternalAPI_ServiceDesc is the grpc.ServiceDesc for ShippingExternalAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShippingExternalAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.shipping.v1.ShippingExternalAPI",
	HandlerType: (*ShippingExternalAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExternalUpdateShippingTracking",
			Handler:    _ShippingExternalAPI_ExternalUpdateShippingTracking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/shipping/v1/shipping_external.proto",
}
