// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/shipping/v1/shipping_internal.proto

package shippingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShippingInternalAPI_InternalPurchaseShippingLabel_FullMethodName                   = "/api.shipping.v1.ShippingInternalAPI/InternalPurchaseShippingLabel"
	ShippingInternalAPI_InternalCancelShippingLabel_FullMethodName                     = "/api.shipping.v1.ShippingInternalAPI/InternalCancelShippingLabel"
	ShippingInternalAPI_InternalVoidGofoLabel_FullMethodName                           = "/api.shipping.v1.ShippingInternalAPI/InternalVoidGofoLabel"
	ShippingInternalAPI_InternalCreateUSPSScanForm_FullMethodName                      = "/api.shipping.v1.ShippingInternalAPI/InternalCreateUSPSScanForm"
	ShippingInternalAPI_InternalListShipmentInfoByOrderRefs_FullMethodName             = "/api.shipping.v1.ShippingInternalAPI/InternalListShipmentInfoByOrderRefs"
	ShippingInternalAPI_InternalGetLatestTrackingStatusByOrderRefs_FullMethodName      = "/api.shipping.v1.ShippingInternalAPI/InternalGetLatestTrackingStatusByOrderRefs"
	ShippingInternalAPI_InternalEstimateShippingRate_FullMethodName                    = "/api.shipping.v1.ShippingInternalAPI/InternalEstimateShippingRate"
	ShippingInternalAPI_InternalListShippingCostLedgerByTrackingNumbers_FullMethodName = "/api.shipping.v1.ShippingInternalAPI/InternalListShippingCostLedgerByTrackingNumbers"
)

// ShippingInternalAPIClient is the client API for ShippingInternalAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShippingInternalAPIClient interface {
	InternalPurchaseShippingLabel(ctx context.Context, in *InternalPurchaseShippingLabelRequest, opts ...grpc.CallOption) (*InternalPurchaseShippingLabelResponse, error)
	InternalCancelShippingLabel(ctx context.Context, in *InternalCancelShippingLabelRequest, opts ...grpc.CallOption) (*InternalCancelShippingLabelResponse, error)
	InternalVoidGofoLabel(ctx context.Context, in *InternalVoidGofoLabelRequest, opts ...grpc.CallOption) (*InternalVoidGofoLabelResponse, error)
	InternalCreateUSPSScanForm(ctx context.Context, in *InternalCreateUSPSScanFormRequest, opts ...grpc.CallOption) (*InternalCreateUSPSScanFormResponse, error)
	InternalListShipmentInfoByOrderRefs(ctx context.Context, in *InternalListShipmentInfoByOrderRefsRequest, opts ...grpc.CallOption) (*InternalListShipmentInfoByOrderRefsResponse, error)
	InternalGetLatestTrackingStatusByOrderRefs(ctx context.Context, in *InternalGetLatestTrackingStatusByOrderRefsRequest, opts ...grpc.CallOption) (*InternalGetLatestTrackingStatusByOrderRefsResponse, error)
	InternalEstimateShippingRate(ctx context.Context, in *InternalEstimateShippingRateRequest, opts ...grpc.CallOption) (*InternalEstimateShippingRateResponse, error)
	InternalListShippingCostLedgerByTrackingNumbers(ctx context.Context, in *InternalListShippingCostLedgerByTrackingNumbersRequest, opts ...grpc.CallOption) (*InternalListShippingCostLedgerByTrackingNumbersResponse, error)
}

type shippingInternalAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingInternalAPIClient(cc grpc.ClientConnInterface) ShippingInternalAPIClient {
	return &shippingInternalAPIClient{cc}
}

func (c *shippingInternalAPIClient) InternalPurchaseShippingLabel(ctx context.Context, in *InternalPurchaseShippingLabelRequest, opts ...grpc.CallOption) (*InternalPurchaseShippingLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalPurchaseShippingLabelResponse)
	err := c.cc.Invoke(ctx, ShippingInternalAPI_InternalPurchaseShippingLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingInternalAPIClient) InternalCancelShippingLabel(ctx context.Context, in *InternalCancelShippingLabelRequest, opts ...grpc.CallOption) (*InternalCancelShippingLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalCancelShippingLabelResponse)
	err := c.cc.Invoke(ctx, ShippingInternalAPI_InternalCancelShippingLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingInternalAPIClient) InternalVoidGofoLabel(ctx context.Context, in *InternalVoidGofoLabelRequest, opts ...grpc.CallOption) (*InternalVoidGofoLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalVoidGofoLabelResponse)
	err := c.cc.Invoke(ctx, ShippingInternalAPI_InternalVoidGofoLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingInternalAPIClient) InternalCreateUSPSScanForm(ctx context.Context, in *InternalCreateUSPSScanFormRequest, opts ...grpc.CallOption) (*InternalCreateUSPSScanFormResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalCreateUSPSScanFormResponse)
	err := c.cc.Invoke(ctx, ShippingInternalAPI_InternalCreateUSPSScanForm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingInternalAPIClient) InternalListShipmentInfoByOrderRefs(ctx context.Context, in *InternalListShipmentInfoByOrderRefsRequest, opts ...grpc.CallOption) (*InternalListShipmentInfoByOrderRefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalListShipmentInfoByOrderRefsResponse)
	err := c.cc.Invoke(ctx, ShippingInternalAPI_InternalListShipmentInfoByOrderRefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingInternalAPIClient) InternalGetLatestTrackingStatusByOrderRefs(ctx context.Context, in *InternalGetLatestTrackingStatusByOrderRefsRequest, opts ...grpc.CallOption) (*InternalGetLatestTrackingStatusByOrderRefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalGetLatestTrackingStatusByOrderRefsResponse)
	err := c.cc.Invoke(ctx, ShippingInternalAPI_InternalGetLatestTrackingStatusByOrderRefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingInternalAPIClient) InternalEstimateShippingRate(ctx context.Context, in *InternalEstimateShippingRateRequest, opts ...grpc.CallOption) (*InternalEstimateShippingRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalEstimateShippingRateResponse)
	err := c.cc.Invoke(ctx, ShippingInternalAPI_InternalEstimateShippingRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingInternalAPIClient) InternalListShippingCostLedgerByTrackingNumbers(ctx context.Context, in *InternalListShippingCostLedgerByTrackingNumbersRequest, opts ...grpc.CallOption) (*InternalListShippingCostLedgerByTrackingNumbersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalListShippingCostLedgerByTrackingNumbersResponse)
	err := c.cc.Invoke(ctx, ShippingInternalAPI_InternalListShippingCostLedgerByTrackingNumbers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingInternalAPIServer is the server API for ShippingInternalAPI service.
// All implementations should embed UnimplementedShippingInternalAPIServer
// for forward compatibility.
type ShippingInternalAPIServer interface {
	InternalPurchaseShippingLabel(context.Context, *InternalPurchaseShippingLabelRequest) (*InternalPurchaseShippingLabelResponse, error)
	InternalCancelShippingLabel(context.Context, *InternalCancelShippingLabelRequest) (*InternalCancelShippingLabelResponse, error)
	InternalVoidGofoLabel(context.Context, *InternalVoidGofoLabelRequest) (*InternalVoidGofoLabelResponse, error)
	InternalCreateUSPSScanForm(context.Context, *InternalCreateUSPSScanFormRequest) (*InternalCreateUSPSScanFormResponse, error)
	InternalListShipmentInfoByOrderRefs(context.Context, *InternalListShipmentInfoByOrderRefsRequest) (*InternalListShipmentInfoByOrderRefsResponse, error)
	InternalGetLatestTrackingStatusByOrderRefs(context.Context, *InternalGetLatestTrackingStatusByOrderRefsRequest) (*InternalGetLatestTrackingStatusByOrderRefsResponse, error)
	InternalEstimateShippingRate(context.Context, *InternalEstimateShippingRateRequest) (*InternalEstimateShippingRateResponse, error)
	InternalListShippingCostLedgerByTrackingNumbers(context.Context, *InternalListShippingCostLedgerByTrackingNumbersRequest) (*InternalListShippingCostLedgerByTrackingNumbersResponse, error)
}

// UnimplementedShippingInternalAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShippingInternalAPIServer struct{}

func (UnimplementedShippingInternalAPIServer) InternalPurchaseShippingLabel(context.Context, *InternalPurchaseShippingLabelRequest) (*InternalPurchaseShippingLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalPurchaseShippingLabel not implemented")
}
func (UnimplementedShippingInternalAPIServer) InternalCancelShippingLabel(context.Context, *InternalCancelShippingLabelRequest) (*InternalCancelShippingLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalCancelShippingLabel not implemented")
}
func (UnimplementedShippingInternalAPIServer) InternalVoidGofoLabel(context.Context, *InternalVoidGofoLabelRequest) (*InternalVoidGofoLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalVoidGofoLabel not implemented")
}
func (UnimplementedShippingInternalAPIServer) InternalCreateUSPSScanForm(context.Context, *InternalCreateUSPSScanFormRequest) (*InternalCreateUSPSScanFormResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalCreateUSPSScanForm not implemented")
}
func (UnimplementedShippingInternalAPIServer) InternalListShipmentInfoByOrderRefs(context.Context, *InternalListShipmentInfoByOrderRefsRequest) (*InternalListShipmentInfoByOrderRefsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalListShipmentInfoByOrderRefs not implemented")
}
func (UnimplementedShippingInternalAPIServer) InternalGetLatestTrackingStatusByOrderRefs(context.Context, *InternalGetLatestTrackingStatusByOrderRefsRequest) (*InternalGetLatestTrackingStatusByOrderRefsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalGetLatestTrackingStatusByOrderRefs not implemented")
}
func (UnimplementedShippingInternalAPIServer) InternalEstimateShippingRate(context.Context, *InternalEstimateShippingRateRequest) (*InternalEstimateShippingRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalEstimateShippingRate not implemented")
}
func (UnimplementedShippingInternalAPIServer) InternalListShippingCostLedgerByTrackingNumbers(context.Context, *InternalListShippingCostLedgerByTrackingNumbersRequest) (*InternalListShippingCostLedgerByTrackingNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalListShippingCostLedgerByTrackingNumbers not implemented")
}
func (UnimplementedShippingInternalAPIServer) testEmbeddedByValue() {}

// UnsafeShippingInternalAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShippingInternalAPIServer will
// result in compilation errors.
type UnsafeShippingInternalAPIServer interface {
	mustEmbedUnimplementedShippingInternalAPIServer()
}

func RegisterShippingInternalAPIServer(s grpc.ServiceRegistrar, srv ShippingInternalAPIServer) {
	// If the following call pancis, it indicates UnimplementedShippingInternalAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShippingInternalAPI_ServiceDesc, srv)
}

func _ShippingInternalAPI_InternalPurchaseShippingLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalPurchaseShippingLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingInternalAPIServer).InternalPurchaseShippingLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingInternalAPI_InternalPurchaseShippingLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingInternalAPIServer).InternalPurchaseShippingLabel(ctx, req.(*InternalPurchaseShippingLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingInternalAPI_InternalCancelShippingLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalCancelShippingLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingInternalAPIServer).InternalCancelShippingLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingInternalAPI_InternalCancelShippingLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingInternalAPIServer).InternalCancelShippingLabel(ctx, req.(*InternalCancelShippingLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingInternalAPI_InternalVoidGofoLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalVoidGofoLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingInternalAPIServer).InternalVoidGofoLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingInternalAPI_InternalVoidGofoLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingInternalAPIServer).InternalVoidGofoLabel(ctx, req.(*InternalVoidGofoLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingInternalAPI_InternalCreateUSPSScanForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalCreateUSPSScanFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingInternalAPIServer).InternalCreateUSPSScanForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingInternalAPI_InternalCreateUSPSScanForm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingInternalAPIServer).InternalCreateUSPSScanForm(ctx, req.(*InternalCreateUSPSScanFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingInternalAPI_InternalListShipmentInfoByOrderRefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalListShipmentInfoByOrderRefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingInternalAPIServer).InternalListShipmentInfoByOrderRefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingInternalAPI_InternalListShipmentInfoByOrderRefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingInternalAPIServer).InternalListShipmentInfoByOrderRefs(ctx, req.(*InternalListShipmentInfoByOrderRefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingInternalAPI_InternalGetLatestTrackingStatusByOrderRefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalGetLatestTrackingStatusByOrderRefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingInternalAPIServer).InternalGetLatestTrackingStatusByOrderRefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingInternalAPI_InternalGetLatestTrackingStatusByOrderRefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingInternalAPIServer).InternalGetLatestTrackingStatusByOrderRefs(ctx, req.(*InternalGetLatestTrackingStatusByOrderRefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingInternalAPI_InternalEstimateShippingRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalEstimateShippingRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingInternalAPIServer).InternalEstimateShippingRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingInternalAPI_InternalEstimateShippingRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingInternalAPIServer).InternalEstimateShippingRate(ctx, req.(*InternalEstimateShippingRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingInternalAPI_InternalListShippingCostLedgerByTrackingNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalListShippingCostLedgerByTrackingNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingInternalAPIServer).InternalListShippingCostLedgerByTrackingNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingInternalAPI_InternalListShippingCostLedgerByTrackingNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingInternalAPIServer).InternalListShippingCostLedgerByTrackingNumbers(ctx, req.(*InternalListShippingCostLedgerByTrackingNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShippingInternalAPI_ServiceDesc is the grpc.ServiceDesc for ShippingInternalAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShippingInternalAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.shipping.v1.ShippingInternalAPI",
	HandlerType: (*ShippingInternalAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalPurchaseShippingLabel",
			Handler:    _ShippingInternalAPI_InternalPurchaseShippingLabel_Handler,
		},
		{
			MethodName: "InternalCancelShippingLabel",
			Handler:    _ShippingInternalAPI_InternalCancelShippingLabel_Handler,
		},
		{
			MethodName: "InternalVoidGofoLabel",
			Handler:    _ShippingInternalAPI_InternalVoidGofoLabel_Handler,
		},
		{
			MethodName: "InternalCreateUSPSScanForm",
			Handler:    _ShippingInternalAPI_InternalCreateUSPSScanForm_Handler,
		},
		{
			MethodName: "InternalListShipmentInfoByOrderRefs",
			Handler:    _ShippingInternalAPI_InternalListShipmentInfoByOrderRefs_Handler,
		},
		{
			MethodName: "InternalGetLatestTrackingStatusByOrderRefs",
			Handler:    _ShippingInternalAPI_InternalGetLatestTrackingStatusByOrderRefs_Handler,
		},
		{
			MethodName: "InternalEstimateShippingRate",
			Handler:    _ShippingInternalAPI_InternalEstimateShippingRate_Handler,
		},
		{
			MethodName: "InternalListShippingCostLedgerByTrackingNumbers",
			Handler:    _ShippingInternalAPI_InternalListShippingCostLedgerByTrackingNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/shipping/v1/shipping_internal.proto",
}
