// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/iam/v1/operation_issue_mcp_internal.proto

package iamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperationIssueMCPAuthInternalAPI_SystemAuthorizeOperationIssueMCP_FullMethodName = "/api.iam.v1.OperationIssueMCPAuthInternalAPI/SystemAuthorizeOperationIssueMCP"
)

// OperationIssueMCPAuthInternalAPIClient is the client API for OperationIssueMCPAuthInternalAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OperationIssueMCPAuthInternalAPI is intentionally available only to the
// operation-issue MCP system client. It turns an already verified OIDC subject
// into the staff actor that POD may audit. It never accepts an access token.
type OperationIssueMCPAuthInternalAPIClient interface {
	SystemAuthorizeOperationIssueMCP(ctx context.Context, in *SystemAuthorizeOperationIssueMCPRequest, opts ...grpc.CallOption) (*SystemAuthorizeOperationIssueMCPResponse, error)
}

type operationIssueMCPAuthInternalAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationIssueMCPAuthInternalAPIClient(cc grpc.ClientConnInterface) OperationIssueMCPAuthInternalAPIClient {
	return &operationIssueMCPAuthInternalAPIClient{cc}
}

func (c *operationIssueMCPAuthInternalAPIClient) SystemAuthorizeOperationIssueMCP(ctx context.Context, in *SystemAuthorizeOperationIssueMCPRequest, opts ...grpc.CallOption) (*SystemAuthorizeOperationIssueMCPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemAuthorizeOperationIssueMCPResponse)
	err := c.cc.Invoke(ctx, OperationIssueMCPAuthInternalAPI_SystemAuthorizeOperationIssueMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationIssueMCPAuthInternalAPIServer is the server API for OperationIssueMCPAuthInternalAPI service.
// All implementations should embed UnimplementedOperationIssueMCPAuthInternalAPIServer
// for forward compatibility.
//
// OperationIssueMCPAuthInternalAPI is intentionally available only to the
// operation-issue MCP system client. It turns an already verified OIDC subject
// into the staff actor that POD may audit. It never accepts an access token.
type OperationIssueMCPAuthInternalAPIServer interface {
	SystemAuthorizeOperationIssueMCP(context.Context, *SystemAuthorizeOperationIssueMCPRequest) (*SystemAuthorizeOperationIssueMCPResponse, error)
}

// UnimplementedOperationIssueMCPAuthInternalAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationIssueMCPAuthInternalAPIServer struct{}

func (UnimplementedOperationIssueMCPAuthInternalAPIServer) SystemAuthorizeOperationIssueMCP(context.Context, *SystemAuthorizeOperationIssueMCPRequest) (*SystemAuthorizeOperationIssueMCPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemAuthorizeOperationIssueMCP not implemented")
}
func (UnimplementedOperationIssueMCPAuthInternalAPIServer) testEmbeddedByValue() {}

// UnsafeOperationIssueMCPAuthInternalAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationIssueMCPAuthInternalAPIServer will
// result in compilation errors.
type UnsafeOperationIssueMCPAuthInternalAPIServer interface {
	mustEmbedUnimplementedOperationIssueMCPAuthInternalAPIServer()
}

func RegisterOperationIssueMCPAuthInternalAPIServer(s grpc.ServiceRegistrar, srv OperationIssueMCPAuthInternalAPIServer) {
	// If the following call pancis, it indicates UnimplementedOperationIssueMCPAuthInternalAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationIssueMCPAuthInternalAPI_ServiceDesc, srv)
}

func _OperationIssueMCPAuthInternalAPI_SystemAuthorizeOperationIssueMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemAuthorizeOperationIssueMCPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationIssueMCPAuthInternalAPIServer).SystemAuthorizeOperationIssueMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationIssueMCPAuthInternalAPI_SystemAuthorizeOperationIssueMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationIssueMCPAuthInternalAPIServer).SystemAuthorizeOperationIssueMCP(ctx, req.(*SystemAuthorizeOperationIssueMCPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperationIssueMCPAuthInternalAPI_ServiceDesc is the grpc.ServiceDesc for OperationIssueMCPAuthInternalAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationIssueMCPAuthInternalAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.iam.v1.OperationIssueMCPAuthInternalAPI",
	HandlerType: (*OperationIssueMCPAuthInternalAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SystemAuthorizeOperationIssueMCP",
			Handler:    _OperationIssueMCPAuthInternalAPI_SystemAuthorizeOperationIssueMCP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/iam/v1/operation_issue_mcp_internal.proto",
}
