// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/iam/v1/staff_account.proto

package iamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StaffAccountAPI_StaffInviteNewStaff_FullMethodName           = "/api.iam.v1.StaffAccountAPI/StaffInviteNewStaff"
	StaffAccountAPI_StaffLogin_FullMethodName                    = "/api.iam.v1.StaffAccountAPI/StaffLogin"
	StaffAccountAPI_StaffLogout_FullMethodName                   = "/api.iam.v1.StaffAccountAPI/StaffLogout"
	StaffAccountAPI_StaffCreatePassword_FullMethodName           = "/api.iam.v1.StaffAccountAPI/StaffCreatePassword"
	StaffAccountAPI_StaffResetPassword_FullMethodName            = "/api.iam.v1.StaffAccountAPI/StaffResetPassword"
	StaffAccountAPI_StaffRefreshAccessToken_FullMethodName       = "/api.iam.v1.StaffAccountAPI/StaffRefreshAccessToken"
	StaffAccountAPI_StaffReInviteStaff_FullMethodName            = "/api.iam.v1.StaffAccountAPI/StaffReInviteStaff"
	StaffAccountAPI_StaffGetStaffProfile_FullMethodName          = "/api.iam.v1.StaffAccountAPI/StaffGetStaffProfile"
	StaffAccountAPI_StaffGetSelfProfile_FullMethodName           = "/api.iam.v1.StaffAccountAPI/StaffGetSelfProfile"
	StaffAccountAPI_StaffCreateNewStaffAccount_FullMethodName    = "/api.iam.v1.StaffAccountAPI/StaffCreateNewStaffAccount"
	StaffAccountAPI_StaffDeactivateInternalStaff_FullMethodName  = "/api.iam.v1.StaffAccountAPI/StaffDeactivateInternalStaff"
	StaffAccountAPI_StaffActivateInternalStaff_FullMethodName    = "/api.iam.v1.StaffAccountAPI/StaffActivateInternalStaff"
	StaffAccountAPI_StaffListStaffForFiltering_FullMethodName    = "/api.iam.v1.StaffAccountAPI/StaffListStaffForFiltering"
	StaffAccountAPI_StaffForgotPassword_FullMethodName           = "/api.iam.v1.StaffAccountAPI/StaffForgotPassword"
	StaffAccountAPI_StaffPreCompletePasswordReset_FullMethodName = "/api.iam.v1.StaffAccountAPI/StaffPreCompletePasswordReset"
	StaffAccountAPI_StaffCompletePasswordReset_FullMethodName    = "/api.iam.v1.StaffAccountAPI/StaffCompletePasswordReset"
)

// StaffAccountAPIClient is the client API for StaffAccountAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaffAccountAPIClient interface {
	StaffInviteNewStaff(ctx context.Context, in *StaffInviteNewStaffRequest, opts ...grpc.CallOption) (*StaffInviteNewStaffResponse, error)
	StaffLogin(ctx context.Context, in *StaffLoginRequest, opts ...grpc.CallOption) (*StaffLoginResponse, error)
	StaffLogout(ctx context.Context, in *StaffLogoutRequest, opts ...grpc.CallOption) (*StaffLogoutResponse, error)
	StaffCreatePassword(ctx context.Context, in *StaffCreatePasswordRequest, opts ...grpc.CallOption) (*StaffCreatePasswordResponse, error)
	StaffResetPassword(ctx context.Context, in *StaffResetPasswordRequest, opts ...grpc.CallOption) (*StaffResetPasswordResponse, error)
	StaffRefreshAccessToken(ctx context.Context, in *StaffRefreshAccessTokenRequest, opts ...grpc.CallOption) (*StaffRefreshAccessTokenResponse, error)
	StaffReInviteStaff(ctx context.Context, in *StaffReInviteStaffRequest, opts ...grpc.CallOption) (*StaffReInviteStaffResponse, error)
	StaffGetStaffProfile(ctx context.Context, in *StaffGetStaffProfileRequest, opts ...grpc.CallOption) (*StaffGetStaffProfileResponse, error)
	StaffGetSelfProfile(ctx context.Context, in *StaffGetSelfProfileRequest, opts ...grpc.CallOption) (*StaffGetSelfProfileResponse, error)
	StaffCreateNewStaffAccount(ctx context.Context, in *StaffCreateNewStaffAccountRequest, opts ...grpc.CallOption) (*StaffCreateNewStaffAccountResponse, error)
	StaffDeactivateInternalStaff(ctx context.Context, in *StaffDeactivateInternalStaffRequest, opts ...grpc.CallOption) (*StaffDeactivateInternalStaffResponse, error)
	StaffActivateInternalStaff(ctx context.Context, in *StaffActivateInternalStaffRequest, opts ...grpc.CallOption) (*StaffActivateInternalStaffResponse, error)
	StaffListStaffForFiltering(ctx context.Context, in *StaffListStaffForFilteringRequest, opts ...grpc.CallOption) (*StaffListStaffForFilteringResponse, error)
	StaffForgotPassword(ctx context.Context, in *StaffForgotPasswordRequest, opts ...grpc.CallOption) (*StaffForgotPasswordResponse, error)
	StaffPreCompletePasswordReset(ctx context.Context, in *StaffPreCompletePasswordResetRequest, opts ...grpc.CallOption) (*StaffPreCompletePasswordResetResponse, error)
	StaffCompletePasswordReset(ctx context.Context, in *StaffCompletePasswordResetRequest, opts ...grpc.CallOption) (*StaffCompletePasswordResetResponse, error)
}

type staffAccountAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewStaffAccountAPIClient(cc grpc.ClientConnInterface) StaffAccountAPIClient {
	return &staffAccountAPIClient{cc}
}

func (c *staffAccountAPIClient) StaffInviteNewStaff(ctx context.Context, in *StaffInviteNewStaffRequest, opts ...grpc.CallOption) (*StaffInviteNewStaffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffInviteNewStaffResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffInviteNewStaff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffLogin(ctx context.Context, in *StaffLoginRequest, opts ...grpc.CallOption) (*StaffLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffLoginResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffLogout(ctx context.Context, in *StaffLogoutRequest, opts ...grpc.CallOption) (*StaffLogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffLogoutResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffCreatePassword(ctx context.Context, in *StaffCreatePasswordRequest, opts ...grpc.CallOption) (*StaffCreatePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffCreatePasswordResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffCreatePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffResetPassword(ctx context.Context, in *StaffResetPasswordRequest, opts ...grpc.CallOption) (*StaffResetPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffResetPasswordResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffRefreshAccessToken(ctx context.Context, in *StaffRefreshAccessTokenRequest, opts ...grpc.CallOption) (*StaffRefreshAccessTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffRefreshAccessTokenResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffRefreshAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffReInviteStaff(ctx context.Context, in *StaffReInviteStaffRequest, opts ...grpc.CallOption) (*StaffReInviteStaffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffReInviteStaffResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffReInviteStaff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffGetStaffProfile(ctx context.Context, in *StaffGetStaffProfileRequest, opts ...grpc.CallOption) (*StaffGetStaffProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffGetStaffProfileResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffGetStaffProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffGetSelfProfile(ctx context.Context, in *StaffGetSelfProfileRequest, opts ...grpc.CallOption) (*StaffGetSelfProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffGetSelfProfileResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffGetSelfProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffCreateNewStaffAccount(ctx context.Context, in *StaffCreateNewStaffAccountRequest, opts ...grpc.CallOption) (*StaffCreateNewStaffAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffCreateNewStaffAccountResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffCreateNewStaffAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffDeactivateInternalStaff(ctx context.Context, in *StaffDeactivateInternalStaffRequest, opts ...grpc.CallOption) (*StaffDeactivateInternalStaffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffDeactivateInternalStaffResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffDeactivateInternalStaff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffActivateInternalStaff(ctx context.Context, in *StaffActivateInternalStaffRequest, opts ...grpc.CallOption) (*StaffActivateInternalStaffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffActivateInternalStaffResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffActivateInternalStaff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffListStaffForFiltering(ctx context.Context, in *StaffListStaffForFilteringRequest, opts ...grpc.CallOption) (*StaffListStaffForFilteringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListStaffForFilteringResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffListStaffForFiltering_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffForgotPassword(ctx context.Context, in *StaffForgotPasswordRequest, opts ...grpc.CallOption) (*StaffForgotPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffForgotPasswordResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffForgotPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffPreCompletePasswordReset(ctx context.Context, in *StaffPreCompletePasswordResetRequest, opts ...grpc.CallOption) (*StaffPreCompletePasswordResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffPreCompletePasswordResetResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffPreCompletePasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffAccountAPIClient) StaffCompletePasswordReset(ctx context.Context, in *StaffCompletePasswordResetRequest, opts ...grpc.CallOption) (*StaffCompletePasswordResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffCompletePasswordResetResponse)
	err := c.cc.Invoke(ctx, StaffAccountAPI_StaffCompletePasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaffAccountAPIServer is the server API for StaffAccountAPI service.
// All implementations should embed UnimplementedStaffAccountAPIServer
// for forward compatibility.
type StaffAccountAPIServer interface {
	StaffInviteNewStaff(context.Context, *StaffInviteNewStaffRequest) (*StaffInviteNewStaffResponse, error)
	StaffLogin(context.Context, *StaffLoginRequest) (*StaffLoginResponse, error)
	StaffLogout(context.Context, *StaffLogoutRequest) (*StaffLogoutResponse, error)
	StaffCreatePassword(context.Context, *StaffCreatePasswordRequest) (*StaffCreatePasswordResponse, error)
	StaffResetPassword(context.Context, *StaffResetPasswordRequest) (*StaffResetPasswordResponse, error)
	StaffRefreshAccessToken(context.Context, *StaffRefreshAccessTokenRequest) (*StaffRefreshAccessTokenResponse, error)
	StaffReInviteStaff(context.Context, *StaffReInviteStaffRequest) (*StaffReInviteStaffResponse, error)
	StaffGetStaffProfile(context.Context, *StaffGetStaffProfileRequest) (*StaffGetStaffProfileResponse, error)
	StaffGetSelfProfile(context.Context, *StaffGetSelfProfileRequest) (*StaffGetSelfProfileResponse, error)
	StaffCreateNewStaffAccount(context.Context, *StaffCreateNewStaffAccountRequest) (*StaffCreateNewStaffAccountResponse, error)
	StaffDeactivateInternalStaff(context.Context, *StaffDeactivateInternalStaffRequest) (*StaffDeactivateInternalStaffResponse, error)
	StaffActivateInternalStaff(context.Context, *StaffActivateInternalStaffRequest) (*StaffActivateInternalStaffResponse, error)
	StaffListStaffForFiltering(context.Context, *StaffListStaffForFilteringRequest) (*StaffListStaffForFilteringResponse, error)
	StaffForgotPassword(context.Context, *StaffForgotPasswordRequest) (*StaffForgotPasswordResponse, error)
	StaffPreCompletePasswordReset(context.Context, *StaffPreCompletePasswordResetRequest) (*StaffPreCompletePasswordResetResponse, error)
	StaffCompletePasswordReset(context.Context, *StaffCompletePasswordResetRequest) (*StaffCompletePasswordResetResponse, error)
}

// UnimplementedStaffAccountAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStaffAccountAPIServer struct{}

func (UnimplementedStaffAccountAPIServer) StaffInviteNewStaff(context.Context, *StaffInviteNewStaffRequest) (*StaffInviteNewStaffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffInviteNewStaff not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffLogin(context.Context, *StaffLoginRequest) (*StaffLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffLogin not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffLogout(context.Context, *StaffLogoutRequest) (*StaffLogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffLogout not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffCreatePassword(context.Context, *StaffCreatePasswordRequest) (*StaffCreatePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffCreatePassword not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffResetPassword(context.Context, *StaffResetPasswordRequest) (*StaffResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffResetPassword not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffRefreshAccessToken(context.Context, *StaffRefreshAccessTokenRequest) (*StaffRefreshAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffRefreshAccessToken not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffReInviteStaff(context.Context, *StaffReInviteStaffRequest) (*StaffReInviteStaffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffReInviteStaff not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffGetStaffProfile(context.Context, *StaffGetStaffProfileRequest) (*StaffGetStaffProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffGetStaffProfile not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffGetSelfProfile(context.Context, *StaffGetSelfProfileRequest) (*StaffGetSelfProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffGetSelfProfile not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffCreateNewStaffAccount(context.Context, *StaffCreateNewStaffAccountRequest) (*StaffCreateNewStaffAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffCreateNewStaffAccount not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffDeactivateInternalStaff(context.Context, *StaffDeactivateInternalStaffRequest) (*StaffDeactivateInternalStaffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffDeactivateInternalStaff not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffActivateInternalStaff(context.Context, *StaffActivateInternalStaffRequest) (*StaffActivateInternalStaffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffActivateInternalStaff not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffListStaffForFiltering(context.Context, *StaffListStaffForFilteringRequest) (*StaffListStaffForFilteringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListStaffForFiltering not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffForgotPassword(context.Context, *StaffForgotPasswordRequest) (*StaffForgotPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffForgotPassword not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffPreCompletePasswordReset(context.Context, *StaffPreCompletePasswordResetRequest) (*StaffPreCompletePasswordResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffPreCompletePasswordReset not implemented")
}
func (UnimplementedStaffAccountAPIServer) StaffCompletePasswordReset(context.Context, *StaffCompletePasswordResetRequest) (*StaffCompletePasswordResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffCompletePasswordReset not implemented")
}
func (UnimplementedStaffAccountAPIServer) testEmbeddedByValue() {}

// UnsafeStaffAccountAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaffAccountAPIServer will
// result in compilation errors.
type UnsafeStaffAccountAPIServer interface {
	mustEmbedUnimplementedStaffAccountAPIServer()
}

func RegisterStaffAccountAPIServer(s grpc.ServiceRegistrar, srv StaffAccountAPIServer) {
	// If the following call pancis, it indicates UnimplementedStaffAccountAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StaffAccountAPI_ServiceDesc, srv)
}

func _StaffAccountAPI_StaffInviteNewStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffInviteNewStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffInviteNewStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffInviteNewStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffInviteNewStaff(ctx, req.(*StaffInviteNewStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffLogin(ctx, req.(*StaffLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffLogout(ctx, req.(*StaffLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffCreatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffCreatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffCreatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffCreatePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffCreatePassword(ctx, req.(*StaffCreatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffResetPassword(ctx, req.(*StaffResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffRefreshAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffRefreshAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffRefreshAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffRefreshAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffRefreshAccessToken(ctx, req.(*StaffRefreshAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffReInviteStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffReInviteStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffReInviteStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffReInviteStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffReInviteStaff(ctx, req.(*StaffReInviteStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffGetStaffProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffGetStaffProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffGetStaffProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffGetStaffProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffGetStaffProfile(ctx, req.(*StaffGetStaffProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffGetSelfProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffGetSelfProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffGetSelfProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffGetSelfProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffGetSelfProfile(ctx, req.(*StaffGetSelfProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffCreateNewStaffAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffCreateNewStaffAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffCreateNewStaffAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffCreateNewStaffAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffCreateNewStaffAccount(ctx, req.(*StaffCreateNewStaffAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffDeactivateInternalStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffDeactivateInternalStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffDeactivateInternalStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffDeactivateInternalStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffDeactivateInternalStaff(ctx, req.(*StaffDeactivateInternalStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffActivateInternalStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffActivateInternalStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffActivateInternalStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffActivateInternalStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffActivateInternalStaff(ctx, req.(*StaffActivateInternalStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffListStaffForFiltering_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListStaffForFilteringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffListStaffForFiltering(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffListStaffForFiltering_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffListStaffForFiltering(ctx, req.(*StaffListStaffForFilteringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffForgotPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffForgotPassword(ctx, req.(*StaffForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffPreCompletePasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffPreCompletePasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffPreCompletePasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffPreCompletePasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffPreCompletePasswordReset(ctx, req.(*StaffPreCompletePasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffAccountAPI_StaffCompletePasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffCompletePasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffAccountAPIServer).StaffCompletePasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffAccountAPI_StaffCompletePasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffAccountAPIServer).StaffCompletePasswordReset(ctx, req.(*StaffCompletePasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StaffAccountAPI_ServiceDesc is the grpc.ServiceDesc for StaffAccountAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StaffAccountAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.iam.v1.StaffAccountAPI",
	HandlerType: (*StaffAccountAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StaffInviteNewStaff",
			Handler:    _StaffAccountAPI_StaffInviteNewStaff_Handler,
		},
		{
			MethodName: "StaffLogin",
			Handler:    _StaffAccountAPI_StaffLogin_Handler,
		},
		{
			MethodName: "StaffLogout",
			Handler:    _StaffAccountAPI_StaffLogout_Handler,
		},
		{
			MethodName: "StaffCreatePassword",
			Handler:    _StaffAccountAPI_StaffCreatePassword_Handler,
		},
		{
			MethodName: "StaffResetPassword",
			Handler:    _StaffAccountAPI_StaffResetPassword_Handler,
		},
		{
			MethodName: "StaffRefreshAccessToken",
			Handler:    _StaffAccountAPI_StaffRefreshAccessToken_Handler,
		},
		{
			MethodName: "StaffReInviteStaff",
			Handler:    _StaffAccountAPI_StaffReInviteStaff_Handler,
		},
		{
			MethodName: "StaffGetStaffProfile",
			Handler:    _StaffAccountAPI_StaffGetStaffProfile_Handler,
		},
		{
			MethodName: "StaffGetSelfProfile",
			Handler:    _StaffAccountAPI_StaffGetSelfProfile_Handler,
		},
		{
			MethodName: "StaffCreateNewStaffAccount",
			Handler:    _StaffAccountAPI_StaffCreateNewStaffAccount_Handler,
		},
		{
			MethodName: "StaffDeactivateInternalStaff",
			Handler:    _StaffAccountAPI_StaffDeactivateInternalStaff_Handler,
		},
		{
			MethodName: "StaffActivateInternalStaff",
			Handler:    _StaffAccountAPI_StaffActivateInternalStaff_Handler,
		},
		{
			MethodName: "StaffListStaffForFiltering",
			Handler:    _StaffAccountAPI_StaffListStaffForFiltering_Handler,
		},
		{
			MethodName: "StaffForgotPassword",
			Handler:    _StaffAccountAPI_StaffForgotPassword_Handler,
		},
		{
			MethodName: "StaffPreCompletePasswordReset",
			Handler:    _StaffAccountAPI_StaffPreCompletePasswordReset_Handler,
		},
		{
			MethodName: "StaffCompletePasswordReset",
			Handler:    _StaffAccountAPI_StaffCompletePasswordReset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/iam/v1/staff_account.proto",
}
