// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/iam/v1/user_legacy.proto

package iamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserLegacyAPI_LegacyCheckEmailRegistered_FullMethodName     = "/api.iam.v1.UserLegacyAPI/LegacyCheckEmailRegistered"
	UserLegacyAPI_LegacyGetOmsCustomer_FullMethodName           = "/api.iam.v1.UserLegacyAPI/LegacyGetOmsCustomer"
	UserLegacyAPI_LegacyResetPasswordOmsCustomer_FullMethodName = "/api.iam.v1.UserLegacyAPI/LegacyResetPasswordOmsCustomer"
)

// UserLegacyAPIClient is the client API for UserLegacyAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserLegacyAPIClient interface {
	LegacyCheckEmailRegistered(ctx context.Context, in *LegacyCheckEmailRegisteredRequest, opts ...grpc.CallOption) (*LegacyCheckEmailRegisteredResponse, error)
	LegacyGetOmsCustomer(ctx context.Context, in *LegacyGetOmsCustomerRequest, opts ...grpc.CallOption) (*LegacyGetOmsCustomerResponse, error)
	LegacyResetPasswordOmsCustomer(ctx context.Context, in *LegacyResetPasswordOmsCustomerRequest, opts ...grpc.CallOption) (*LegacyResetPasswordOmsCustomerResponse, error)
}

type userLegacyAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewUserLegacyAPIClient(cc grpc.ClientConnInterface) UserLegacyAPIClient {
	return &userLegacyAPIClient{cc}
}

func (c *userLegacyAPIClient) LegacyCheckEmailRegistered(ctx context.Context, in *LegacyCheckEmailRegisteredRequest, opts ...grpc.CallOption) (*LegacyCheckEmailRegisteredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LegacyCheckEmailRegisteredResponse)
	err := c.cc.Invoke(ctx, UserLegacyAPI_LegacyCheckEmailRegistered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLegacyAPIClient) LegacyGetOmsCustomer(ctx context.Context, in *LegacyGetOmsCustomerRequest, opts ...grpc.CallOption) (*LegacyGetOmsCustomerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LegacyGetOmsCustomerResponse)
	err := c.cc.Invoke(ctx, UserLegacyAPI_LegacyGetOmsCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLegacyAPIClient) LegacyResetPasswordOmsCustomer(ctx context.Context, in *LegacyResetPasswordOmsCustomerRequest, opts ...grpc.CallOption) (*LegacyResetPasswordOmsCustomerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LegacyResetPasswordOmsCustomerResponse)
	err := c.cc.Invoke(ctx, UserLegacyAPI_LegacyResetPasswordOmsCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserLegacyAPIServer is the server API for UserLegacyAPI service.
// All implementations should embed UnimplementedUserLegacyAPIServer
// for forward compatibility.
type UserLegacyAPIServer interface {
	LegacyCheckEmailRegistered(context.Context, *LegacyCheckEmailRegisteredRequest) (*LegacyCheckEmailRegisteredResponse, error)
	LegacyGetOmsCustomer(context.Context, *LegacyGetOmsCustomerRequest) (*LegacyGetOmsCustomerResponse, error)
	LegacyResetPasswordOmsCustomer(context.Context, *LegacyResetPasswordOmsCustomerRequest) (*LegacyResetPasswordOmsCustomerResponse, error)
}

// UnimplementedUserLegacyAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserLegacyAPIServer struct{}

func (UnimplementedUserLegacyAPIServer) LegacyCheckEmailRegistered(context.Context, *LegacyCheckEmailRegisteredRequest) (*LegacyCheckEmailRegisteredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegacyCheckEmailRegistered not implemented")
}
func (UnimplementedUserLegacyAPIServer) LegacyGetOmsCustomer(context.Context, *LegacyGetOmsCustomerRequest) (*LegacyGetOmsCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegacyGetOmsCustomer not implemented")
}
func (UnimplementedUserLegacyAPIServer) LegacyResetPasswordOmsCustomer(context.Context, *LegacyResetPasswordOmsCustomerRequest) (*LegacyResetPasswordOmsCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegacyResetPasswordOmsCustomer not implemented")
}
func (UnimplementedUserLegacyAPIServer) testEmbeddedByValue() {}

// UnsafeUserLegacyAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserLegacyAPIServer will
// result in compilation errors.
type UnsafeUserLegacyAPIServer interface {
	mustEmbedUnimplementedUserLegacyAPIServer()
}

func RegisterUserLegacyAPIServer(s grpc.ServiceRegistrar, srv UserLegacyAPIServer) {
	// If the following call pancis, it indicates UnimplementedUserLegacyAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserLegacyAPI_ServiceDesc, srv)
}

func _UserLegacyAPI_LegacyCheckEmailRegistered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LegacyCheckEmailRegisteredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLegacyAPIServer).LegacyCheckEmailRegistered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserLegacyAPI_LegacyCheckEmailRegistered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLegacyAPIServer).LegacyCheckEmailRegistered(ctx, req.(*LegacyCheckEmailRegisteredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLegacyAPI_LegacyGetOmsCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LegacyGetOmsCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLegacyAPIServer).LegacyGetOmsCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserLegacyAPI_LegacyGetOmsCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLegacyAPIServer).LegacyGetOmsCustomer(ctx, req.(*LegacyGetOmsCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLegacyAPI_LegacyResetPasswordOmsCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LegacyResetPasswordOmsCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLegacyAPIServer).LegacyResetPasswordOmsCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserLegacyAPI_LegacyResetPasswordOmsCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLegacyAPIServer).LegacyResetPasswordOmsCustomer(ctx, req.(*LegacyResetPasswordOmsCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserLegacyAPI_ServiceDesc is the grpc.ServiceDesc for UserLegacyAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserLegacyAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.iam.v1.UserLegacyAPI",
	HandlerType: (*UserLegacyAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LegacyCheckEmailRegistered",
			Handler:    _UserLegacyAPI_LegacyCheckEmailRegistered_Handler,
		},
		{
			MethodName: "LegacyGetOmsCustomer",
			Handler:    _UserLegacyAPI_LegacyGetOmsCustomer_Handler,
		},
		{
			MethodName: "LegacyResetPasswordOmsCustomer",
			Handler:    _UserLegacyAPI_LegacyResetPasswordOmsCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/iam/v1/user_legacy.proto",
}
