// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/ffm/v1/cross_dock_admin.proto

package ffmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrossDockingFulfillmentAdminAPI_StaffListShippingPlan_FullMethodName                 = "/api.ffm.v1.CrossDockingFulfillmentAdminAPI/StaffListShippingPlan"
	CrossDockingFulfillmentAdminAPI_StaffGetShippingPlan_FullMethodName                  = "/api.ffm.v1.CrossDockingFulfillmentAdminAPI/StaffGetShippingPlan"
	CrossDockingFulfillmentAdminAPI_StaffConfirmShippingPlanPaid_FullMethodName          = "/api.ffm.v1.CrossDockingFulfillmentAdminAPI/StaffConfirmShippingPlanPaid"
	CrossDockingFulfillmentAdminAPI_StaffUpdateShippingParcelTrackingInfo_FullMethodName = "/api.ffm.v1.CrossDockingFulfillmentAdminAPI/StaffUpdateShippingParcelTrackingInfo"
	CrossDockingFulfillmentAdminAPI_StaffUpdateShippingParcelHandled_FullMethodName      = "/api.ffm.v1.CrossDockingFulfillmentAdminAPI/StaffUpdateShippingParcelHandled"
	CrossDockingFulfillmentAdminAPI_StaffListShippingParcel_FullMethodName               = "/api.ffm.v1.CrossDockingFulfillmentAdminAPI/StaffListShippingParcel"
)

// CrossDockingFulfillmentAdminAPIClient is the client API for CrossDockingFulfillmentAdminAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrossDockingFulfillmentAdminAPIClient interface {
	StaffListShippingPlan(ctx context.Context, in *StaffListShippingPlanRequest, opts ...grpc.CallOption) (*StaffListShippingPlanResponse, error)
	StaffGetShippingPlan(ctx context.Context, in *StaffGetShippingPlanRequest, opts ...grpc.CallOption) (*StaffGetShippingPlanResponse, error)
	StaffConfirmShippingPlanPaid(ctx context.Context, in *StaffConfirmShippingPlanPaidRequest, opts ...grpc.CallOption) (*StaffConfirmShippingPlanPaidResponse, error)
	StaffUpdateShippingParcelTrackingInfo(ctx context.Context, in *StaffUpdateShippingParcelTrackingInfoRequest, opts ...grpc.CallOption) (*StaffUpdateShippingParcelTrackingInfoResponse, error)
	StaffUpdateShippingParcelHandled(ctx context.Context, in *StaffUpdateShippingParcelHandledRequest, opts ...grpc.CallOption) (*StaffUpdateShippingParcelHandledResponse, error)
	StaffListShippingParcel(ctx context.Context, in *StaffListShippingParcelRequest, opts ...grpc.CallOption) (*StaffListShippingParcelResponse, error)
}

type crossDockingFulfillmentAdminAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCrossDockingFulfillmentAdminAPIClient(cc grpc.ClientConnInterface) CrossDockingFulfillmentAdminAPIClient {
	return &crossDockingFulfillmentAdminAPIClient{cc}
}

func (c *crossDockingFulfillmentAdminAPIClient) StaffListShippingPlan(ctx context.Context, in *StaffListShippingPlanRequest, opts ...grpc.CallOption) (*StaffListShippingPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListShippingPlanResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAdminAPI_StaffListShippingPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAdminAPIClient) StaffGetShippingPlan(ctx context.Context, in *StaffGetShippingPlanRequest, opts ...grpc.CallOption) (*StaffGetShippingPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffGetShippingPlanResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAdminAPI_StaffGetShippingPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAdminAPIClient) StaffConfirmShippingPlanPaid(ctx context.Context, in *StaffConfirmShippingPlanPaidRequest, opts ...grpc.CallOption) (*StaffConfirmShippingPlanPaidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffConfirmShippingPlanPaidResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAdminAPI_StaffConfirmShippingPlanPaid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAdminAPIClient) StaffUpdateShippingParcelTrackingInfo(ctx context.Context, in *StaffUpdateShippingParcelTrackingInfoRequest, opts ...grpc.CallOption) (*StaffUpdateShippingParcelTrackingInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffUpdateShippingParcelTrackingInfoResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAdminAPI_StaffUpdateShippingParcelTrackingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAdminAPIClient) StaffUpdateShippingParcelHandled(ctx context.Context, in *StaffUpdateShippingParcelHandledRequest, opts ...grpc.CallOption) (*StaffUpdateShippingParcelHandledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffUpdateShippingParcelHandledResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAdminAPI_StaffUpdateShippingParcelHandled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAdminAPIClient) StaffListShippingParcel(ctx context.Context, in *StaffListShippingParcelRequest, opts ...grpc.CallOption) (*StaffListShippingParcelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListShippingParcelResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAdminAPI_StaffListShippingParcel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrossDockingFulfillmentAdminAPIServer is the server API for CrossDockingFulfillmentAdminAPI service.
// All implementations should embed UnimplementedCrossDockingFulfillmentAdminAPIServer
// for forward compatibility.
type CrossDockingFulfillmentAdminAPIServer interface {
	StaffListShippingPlan(context.Context, *StaffListShippingPlanRequest) (*StaffListShippingPlanResponse, error)
	StaffGetShippingPlan(context.Context, *StaffGetShippingPlanRequest) (*StaffGetShippingPlanResponse, error)
	StaffConfirmShippingPlanPaid(context.Context, *StaffConfirmShippingPlanPaidRequest) (*StaffConfirmShippingPlanPaidResponse, error)
	StaffUpdateShippingParcelTrackingInfo(context.Context, *StaffUpdateShippingParcelTrackingInfoRequest) (*StaffUpdateShippingParcelTrackingInfoResponse, error)
	StaffUpdateShippingParcelHandled(context.Context, *StaffUpdateShippingParcelHandledRequest) (*StaffUpdateShippingParcelHandledResponse, error)
	StaffListShippingParcel(context.Context, *StaffListShippingParcelRequest) (*StaffListShippingParcelResponse, error)
}

// UnimplementedCrossDockingFulfillmentAdminAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrossDockingFulfillmentAdminAPIServer struct{}

func (UnimplementedCrossDockingFulfillmentAdminAPIServer) StaffListShippingPlan(context.Context, *StaffListShippingPlanRequest) (*StaffListShippingPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListShippingPlan not implemented")
}
func (UnimplementedCrossDockingFulfillmentAdminAPIServer) StaffGetShippingPlan(context.Context, *StaffGetShippingPlanRequest) (*StaffGetShippingPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffGetShippingPlan not implemented")
}
func (UnimplementedCrossDockingFulfillmentAdminAPIServer) StaffConfirmShippingPlanPaid(context.Context, *StaffConfirmShippingPlanPaidRequest) (*StaffConfirmShippingPlanPaidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffConfirmShippingPlanPaid not implemented")
}
func (UnimplementedCrossDockingFulfillmentAdminAPIServer) StaffUpdateShippingParcelTrackingInfo(context.Context, *StaffUpdateShippingParcelTrackingInfoRequest) (*StaffUpdateShippingParcelTrackingInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffUpdateShippingParcelTrackingInfo not implemented")
}
func (UnimplementedCrossDockingFulfillmentAdminAPIServer) StaffUpdateShippingParcelHandled(context.Context, *StaffUpdateShippingParcelHandledRequest) (*StaffUpdateShippingParcelHandledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffUpdateShippingParcelHandled not implemented")
}
func (UnimplementedCrossDockingFulfillmentAdminAPIServer) StaffListShippingParcel(context.Context, *StaffListShippingParcelRequest) (*StaffListShippingParcelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListShippingParcel not implemented")
}
func (UnimplementedCrossDockingFulfillmentAdminAPIServer) testEmbeddedByValue() {}

// UnsafeCrossDockingFulfillmentAdminAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrossDockingFulfillmentAdminAPIServer will
// result in compilation errors.
type UnsafeCrossDockingFulfillmentAdminAPIServer interface {
	mustEmbedUnimplementedCrossDockingFulfillmentAdminAPIServer()
}

func RegisterCrossDockingFulfillmentAdminAPIServer(s grpc.ServiceRegistrar, srv CrossDockingFulfillmentAdminAPIServer) {
	// If the following call pancis, it indicates UnimplementedCrossDockingFulfillmentAdminAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrossDockingFulfillmentAdminAPI_ServiceDesc, srv)
}

func _CrossDockingFulfillmentAdminAPI_StaffListShippingPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListShippingPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffListShippingPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAdminAPI_StaffListShippingPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffListShippingPlan(ctx, req.(*StaffListShippingPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAdminAPI_StaffGetShippingPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffGetShippingPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffGetShippingPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAdminAPI_StaffGetShippingPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffGetShippingPlan(ctx, req.(*StaffGetShippingPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAdminAPI_StaffConfirmShippingPlanPaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffConfirmShippingPlanPaidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffConfirmShippingPlanPaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAdminAPI_StaffConfirmShippingPlanPaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffConfirmShippingPlanPaid(ctx, req.(*StaffConfirmShippingPlanPaidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAdminAPI_StaffUpdateShippingParcelTrackingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffUpdateShippingParcelTrackingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffUpdateShippingParcelTrackingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAdminAPI_StaffUpdateShippingParcelTrackingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffUpdateShippingParcelTrackingInfo(ctx, req.(*StaffUpdateShippingParcelTrackingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAdminAPI_StaffUpdateShippingParcelHandled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffUpdateShippingParcelHandledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffUpdateShippingParcelHandled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAdminAPI_StaffUpdateShippingParcelHandled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffUpdateShippingParcelHandled(ctx, req.(*StaffUpdateShippingParcelHandledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAdminAPI_StaffListShippingParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListShippingParcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffListShippingParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAdminAPI_StaffListShippingParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAdminAPIServer).StaffListShippingParcel(ctx, req.(*StaffListShippingParcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrossDockingFulfillmentAdminAPI_ServiceDesc is the grpc.ServiceDesc for CrossDockingFulfillmentAdminAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrossDockingFulfillmentAdminAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ffm.v1.CrossDockingFulfillmentAdminAPI",
	HandlerType: (*CrossDockingFulfillmentAdminAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StaffListShippingPlan",
			Handler:    _CrossDockingFulfillmentAdminAPI_StaffListShippingPlan_Handler,
		},
		{
			MethodName: "StaffGetShippingPlan",
			Handler:    _CrossDockingFulfillmentAdminAPI_StaffGetShippingPlan_Handler,
		},
		{
			MethodName: "StaffConfirmShippingPlanPaid",
			Handler:    _CrossDockingFulfillmentAdminAPI_StaffConfirmShippingPlanPaid_Handler,
		},
		{
			MethodName: "StaffUpdateShippingParcelTrackingInfo",
			Handler:    _CrossDockingFulfillmentAdminAPI_StaffUpdateShippingParcelTrackingInfo_Handler,
		},
		{
			MethodName: "StaffUpdateShippingParcelHandled",
			Handler:    _CrossDockingFulfillmentAdminAPI_StaffUpdateShippingParcelHandled_Handler,
		},
		{
			MethodName: "StaffListShippingParcel",
			Handler:    _CrossDockingFulfillmentAdminAPI_StaffListShippingParcel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ffm/v1/cross_dock_admin.proto",
}
