// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/ffm/v1/cross_dock.proto

package ffmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrossDockingFulfillmentAPI_UserCreateShippingPlan_FullMethodName           = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserCreateShippingPlan"
	CrossDockingFulfillmentAPI_UserListShippingPlan_FullMethodName             = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserListShippingPlan"
	CrossDockingFulfillmentAPI_UserGetShippingPlan_FullMethodName              = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserGetShippingPlan"
	CrossDockingFulfillmentAPI_UserUpdateShippingPlanRoute_FullMethodName      = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserUpdateShippingPlanRoute"
	CrossDockingFulfillmentAPI_UserCancelShippingPlan_FullMethodName           = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserCancelShippingPlan"
	CrossDockingFulfillmentAPI_UserConfirmShippingPlan_FullMethodName          = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserConfirmShippingPlan"
	CrossDockingFulfillmentAPI_UserGetShippingPlanQuotation_FullMethodName     = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserGetShippingPlanQuotation"
	CrossDockingFulfillmentAPI_UserUpdateShippingBox_FullMethodName            = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserUpdateShippingBox"
	CrossDockingFulfillmentAPI_UserUpdateShippingParcel_FullMethodName         = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserUpdateShippingParcel"
	CrossDockingFulfillmentAPI_UserListShippingLocation_FullMethodName         = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserListShippingLocation"
	CrossDockingFulfillmentAPI_UserAddShippingLocation_FullMethodName          = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserAddShippingLocation"
	CrossDockingFulfillmentAPI_UserRemoveShippingLocation_FullMethodName       = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserRemoveShippingLocation"
	CrossDockingFulfillmentAPI_UserListPackagingBox_FullMethodName             = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserListPackagingBox"
	CrossDockingFulfillmentAPI_UserConfirmShippingParcelPacking_FullMethodName = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserConfirmShippingParcelPacking"
	CrossDockingFulfillmentAPI_UserConfirmShippingPlanPacked_FullMethodName    = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserConfirmShippingPlanPacked"
	CrossDockingFulfillmentAPI_UserConfirmShippingPlanShipped_FullMethodName   = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserConfirmShippingPlanShipped"
	CrossDockingFulfillmentAPI_UserGetShippingPlanPaymentDetail_FullMethodName = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserGetShippingPlanPaymentDetail"
	CrossDockingFulfillmentAPI_UserReorderShippingParcel_FullMethodName        = "/api.ffm.v1.CrossDockingFulfillmentAPI/UserReorderShippingParcel"
)

// CrossDockingFulfillmentAPIClient is the client API for CrossDockingFulfillmentAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrossDockingFulfillmentAPIClient interface {
	UserCreateShippingPlan(ctx context.Context, in *UserCreateShippingPlanRequest, opts ...grpc.CallOption) (*UserCreateShippingPlanResponse, error)
	UserListShippingPlan(ctx context.Context, in *UserListShippingPlanRequest, opts ...grpc.CallOption) (*UserListShippingPlanResponse, error)
	UserGetShippingPlan(ctx context.Context, in *UserGetShippingPlanRequest, opts ...grpc.CallOption) (*UserGetShippingPlanResponse, error)
	UserUpdateShippingPlanRoute(ctx context.Context, in *UserUpdateShippingPlanRouteRequest, opts ...grpc.CallOption) (*UserUpdateShippingPlanRouteResponse, error)
	UserCancelShippingPlan(ctx context.Context, in *UserCancelShippingPlanRequest, opts ...grpc.CallOption) (*UserCancelShippingPlanResponse, error)
	UserConfirmShippingPlan(ctx context.Context, in *UserConfirmShippingPlanRequest, opts ...grpc.CallOption) (*UserConfirmShippingPlanResponse, error)
	UserGetShippingPlanQuotation(ctx context.Context, in *UserGetShippingPlanQuotationRequest, opts ...grpc.CallOption) (*UserGetShippingPlanQuotationResponse, error)
	UserUpdateShippingBox(ctx context.Context, in *UserUpdateShippingBoxRequest, opts ...grpc.CallOption) (*UserUpdateShippingBoxResponse, error)
	UserUpdateShippingParcel(ctx context.Context, in *UserUpdateShippingParcelRequest, opts ...grpc.CallOption) (*UserUpdateShippingParcelResponse, error)
	UserListShippingLocation(ctx context.Context, in *UserListShippingLocationRequest, opts ...grpc.CallOption) (*UserListShippingLocationResponse, error)
	UserAddShippingLocation(ctx context.Context, in *UserAddShippingLocationRequest, opts ...grpc.CallOption) (*UserAddShippingLocationResponse, error)
	UserRemoveShippingLocation(ctx context.Context, in *UserRemoveShippingLocationRequest, opts ...grpc.CallOption) (*UserRemoveShippingLocationResponse, error)
	UserListPackagingBox(ctx context.Context, in *UserListPackagingBoxRequest, opts ...grpc.CallOption) (*UserListPackagingBoxResponse, error)
	UserConfirmShippingParcelPacking(ctx context.Context, in *UserConfirmShippingParcelPackingRequest, opts ...grpc.CallOption) (*UserConfirmShippingParcelPackingResponse, error)
	UserConfirmShippingPlanPacked(ctx context.Context, in *UserConfirmShippingPlanPackedRequest, opts ...grpc.CallOption) (*UserConfirmShippingPlanPackedResponse, error)
	UserConfirmShippingPlanShipped(ctx context.Context, in *UserConfirmShippingPlanShippedRequest, opts ...grpc.CallOption) (*UserConfirmShippingPlanShippedResponse, error)
	UserGetShippingPlanPaymentDetail(ctx context.Context, in *UserGetShippingPlanPaymentDetailRequest, opts ...grpc.CallOption) (*UserGetShippingPlanPaymentDetailResponse, error)
	UserReorderShippingParcel(ctx context.Context, in *UserReorderShippingParcelRequest, opts ...grpc.CallOption) (*UserReorderShippingParcelResponse, error)
}

type crossDockingFulfillmentAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCrossDockingFulfillmentAPIClient(cc grpc.ClientConnInterface) CrossDockingFulfillmentAPIClient {
	return &crossDockingFulfillmentAPIClient{cc}
}

func (c *crossDockingFulfillmentAPIClient) UserCreateShippingPlan(ctx context.Context, in *UserCreateShippingPlanRequest, opts ...grpc.CallOption) (*UserCreateShippingPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCreateShippingPlanResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserCreateShippingPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserListShippingPlan(ctx context.Context, in *UserListShippingPlanRequest, opts ...grpc.CallOption) (*UserListShippingPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListShippingPlanResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserListShippingPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserGetShippingPlan(ctx context.Context, in *UserGetShippingPlanRequest, opts ...grpc.CallOption) (*UserGetShippingPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetShippingPlanResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserGetShippingPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserUpdateShippingPlanRoute(ctx context.Context, in *UserUpdateShippingPlanRouteRequest, opts ...grpc.CallOption) (*UserUpdateShippingPlanRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUpdateShippingPlanRouteResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserUpdateShippingPlanRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserCancelShippingPlan(ctx context.Context, in *UserCancelShippingPlanRequest, opts ...grpc.CallOption) (*UserCancelShippingPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCancelShippingPlanResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserCancelShippingPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserConfirmShippingPlan(ctx context.Context, in *UserConfirmShippingPlanRequest, opts ...grpc.CallOption) (*UserConfirmShippingPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserConfirmShippingPlanResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserConfirmShippingPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserGetShippingPlanQuotation(ctx context.Context, in *UserGetShippingPlanQuotationRequest, opts ...grpc.CallOption) (*UserGetShippingPlanQuotationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetShippingPlanQuotationResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserGetShippingPlanQuotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserUpdateShippingBox(ctx context.Context, in *UserUpdateShippingBoxRequest, opts ...grpc.CallOption) (*UserUpdateShippingBoxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUpdateShippingBoxResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserUpdateShippingBox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserUpdateShippingParcel(ctx context.Context, in *UserUpdateShippingParcelRequest, opts ...grpc.CallOption) (*UserUpdateShippingParcelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUpdateShippingParcelResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserUpdateShippingParcel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserListShippingLocation(ctx context.Context, in *UserListShippingLocationRequest, opts ...grpc.CallOption) (*UserListShippingLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListShippingLocationResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserListShippingLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserAddShippingLocation(ctx context.Context, in *UserAddShippingLocationRequest, opts ...grpc.CallOption) (*UserAddShippingLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAddShippingLocationResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserAddShippingLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserRemoveShippingLocation(ctx context.Context, in *UserRemoveShippingLocationRequest, opts ...grpc.CallOption) (*UserRemoveShippingLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRemoveShippingLocationResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserRemoveShippingLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserListPackagingBox(ctx context.Context, in *UserListPackagingBoxRequest, opts ...grpc.CallOption) (*UserListPackagingBoxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListPackagingBoxResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserListPackagingBox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserConfirmShippingParcelPacking(ctx context.Context, in *UserConfirmShippingParcelPackingRequest, opts ...grpc.CallOption) (*UserConfirmShippingParcelPackingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserConfirmShippingParcelPackingResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserConfirmShippingParcelPacking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserConfirmShippingPlanPacked(ctx context.Context, in *UserConfirmShippingPlanPackedRequest, opts ...grpc.CallOption) (*UserConfirmShippingPlanPackedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserConfirmShippingPlanPackedResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserConfirmShippingPlanPacked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserConfirmShippingPlanShipped(ctx context.Context, in *UserConfirmShippingPlanShippedRequest, opts ...grpc.CallOption) (*UserConfirmShippingPlanShippedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserConfirmShippingPlanShippedResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserConfirmShippingPlanShipped_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserGetShippingPlanPaymentDetail(ctx context.Context, in *UserGetShippingPlanPaymentDetailRequest, opts ...grpc.CallOption) (*UserGetShippingPlanPaymentDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetShippingPlanPaymentDetailResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserGetShippingPlanPaymentDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossDockingFulfillmentAPIClient) UserReorderShippingParcel(ctx context.Context, in *UserReorderShippingParcelRequest, opts ...grpc.CallOption) (*UserReorderShippingParcelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserReorderShippingParcelResponse)
	err := c.cc.Invoke(ctx, CrossDockingFulfillmentAPI_UserReorderShippingParcel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrossDockingFulfillmentAPIServer is the server API for CrossDockingFulfillmentAPI service.
// All implementations should embed UnimplementedCrossDockingFulfillmentAPIServer
// for forward compatibility.
type CrossDockingFulfillmentAPIServer interface {
	UserCreateShippingPlan(context.Context, *UserCreateShippingPlanRequest) (*UserCreateShippingPlanResponse, error)
	UserListShippingPlan(context.Context, *UserListShippingPlanRequest) (*UserListShippingPlanResponse, error)
	UserGetShippingPlan(context.Context, *UserGetShippingPlanRequest) (*UserGetShippingPlanResponse, error)
	UserUpdateShippingPlanRoute(context.Context, *UserUpdateShippingPlanRouteRequest) (*UserUpdateShippingPlanRouteResponse, error)
	UserCancelShippingPlan(context.Context, *UserCancelShippingPlanRequest) (*UserCancelShippingPlanResponse, error)
	UserConfirmShippingPlan(context.Context, *UserConfirmShippingPlanRequest) (*UserConfirmShippingPlanResponse, error)
	UserGetShippingPlanQuotation(context.Context, *UserGetShippingPlanQuotationRequest) (*UserGetShippingPlanQuotationResponse, error)
	UserUpdateShippingBox(context.Context, *UserUpdateShippingBoxRequest) (*UserUpdateShippingBoxResponse, error)
	UserUpdateShippingParcel(context.Context, *UserUpdateShippingParcelRequest) (*UserUpdateShippingParcelResponse, error)
	UserListShippingLocation(context.Context, *UserListShippingLocationRequest) (*UserListShippingLocationResponse, error)
	UserAddShippingLocation(context.Context, *UserAddShippingLocationRequest) (*UserAddShippingLocationResponse, error)
	UserRemoveShippingLocation(context.Context, *UserRemoveShippingLocationRequest) (*UserRemoveShippingLocationResponse, error)
	UserListPackagingBox(context.Context, *UserListPackagingBoxRequest) (*UserListPackagingBoxResponse, error)
	UserConfirmShippingParcelPacking(context.Context, *UserConfirmShippingParcelPackingRequest) (*UserConfirmShippingParcelPackingResponse, error)
	UserConfirmShippingPlanPacked(context.Context, *UserConfirmShippingPlanPackedRequest) (*UserConfirmShippingPlanPackedResponse, error)
	UserConfirmShippingPlanShipped(context.Context, *UserConfirmShippingPlanShippedRequest) (*UserConfirmShippingPlanShippedResponse, error)
	UserGetShippingPlanPaymentDetail(context.Context, *UserGetShippingPlanPaymentDetailRequest) (*UserGetShippingPlanPaymentDetailResponse, error)
	UserReorderShippingParcel(context.Context, *UserReorderShippingParcelRequest) (*UserReorderShippingParcelResponse, error)
}

// UnimplementedCrossDockingFulfillmentAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrossDockingFulfillmentAPIServer struct{}

func (UnimplementedCrossDockingFulfillmentAPIServer) UserCreateShippingPlan(context.Context, *UserCreateShippingPlanRequest) (*UserCreateShippingPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCreateShippingPlan not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserListShippingPlan(context.Context, *UserListShippingPlanRequest) (*UserListShippingPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListShippingPlan not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserGetShippingPlan(context.Context, *UserGetShippingPlanRequest) (*UserGetShippingPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetShippingPlan not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserUpdateShippingPlanRoute(context.Context, *UserUpdateShippingPlanRouteRequest) (*UserUpdateShippingPlanRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUpdateShippingPlanRoute not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserCancelShippingPlan(context.Context, *UserCancelShippingPlanRequest) (*UserCancelShippingPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCancelShippingPlan not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserConfirmShippingPlan(context.Context, *UserConfirmShippingPlanRequest) (*UserConfirmShippingPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserConfirmShippingPlan not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserGetShippingPlanQuotation(context.Context, *UserGetShippingPlanQuotationRequest) (*UserGetShippingPlanQuotationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetShippingPlanQuotation not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserUpdateShippingBox(context.Context, *UserUpdateShippingBoxRequest) (*UserUpdateShippingBoxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUpdateShippingBox not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserUpdateShippingParcel(context.Context, *UserUpdateShippingParcelRequest) (*UserUpdateShippingParcelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUpdateShippingParcel not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserListShippingLocation(context.Context, *UserListShippingLocationRequest) (*UserListShippingLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListShippingLocation not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserAddShippingLocation(context.Context, *UserAddShippingLocationRequest) (*UserAddShippingLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAddShippingLocation not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserRemoveShippingLocation(context.Context, *UserRemoveShippingLocationRequest) (*UserRemoveShippingLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRemoveShippingLocation not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserListPackagingBox(context.Context, *UserListPackagingBoxRequest) (*UserListPackagingBoxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListPackagingBox not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserConfirmShippingParcelPacking(context.Context, *UserConfirmShippingParcelPackingRequest) (*UserConfirmShippingParcelPackingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserConfirmShippingParcelPacking not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserConfirmShippingPlanPacked(context.Context, *UserConfirmShippingPlanPackedRequest) (*UserConfirmShippingPlanPackedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserConfirmShippingPlanPacked not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserConfirmShippingPlanShipped(context.Context, *UserConfirmShippingPlanShippedRequest) (*UserConfirmShippingPlanShippedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserConfirmShippingPlanShipped not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserGetShippingPlanPaymentDetail(context.Context, *UserGetShippingPlanPaymentDetailRequest) (*UserGetShippingPlanPaymentDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetShippingPlanPaymentDetail not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) UserReorderShippingParcel(context.Context, *UserReorderShippingParcelRequest) (*UserReorderShippingParcelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserReorderShippingParcel not implemented")
}
func (UnimplementedCrossDockingFulfillmentAPIServer) testEmbeddedByValue() {}

// UnsafeCrossDockingFulfillmentAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrossDockingFulfillmentAPIServer will
// result in compilation errors.
type UnsafeCrossDockingFulfillmentAPIServer interface {
	mustEmbedUnimplementedCrossDockingFulfillmentAPIServer()
}

func RegisterCrossDockingFulfillmentAPIServer(s grpc.ServiceRegistrar, srv CrossDockingFulfillmentAPIServer) {
	// If the following call pancis, it indicates UnimplementedCrossDockingFulfillmentAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrossDockingFulfillmentAPI_ServiceDesc, srv)
}

func _CrossDockingFulfillmentAPI_UserCreateShippingPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateShippingPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserCreateShippingPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserCreateShippingPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserCreateShippingPlan(ctx, req.(*UserCreateShippingPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserListShippingPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListShippingPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserListShippingPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserListShippingPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserListShippingPlan(ctx, req.(*UserListShippingPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserGetShippingPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetShippingPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserGetShippingPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserGetShippingPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserGetShippingPlan(ctx, req.(*UserGetShippingPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserUpdateShippingPlanRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateShippingPlanRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserUpdateShippingPlanRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserUpdateShippingPlanRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserUpdateShippingPlanRoute(ctx, req.(*UserUpdateShippingPlanRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserCancelShippingPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCancelShippingPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserCancelShippingPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserCancelShippingPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserCancelShippingPlan(ctx, req.(*UserCancelShippingPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserConfirmShippingPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserConfirmShippingPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserConfirmShippingPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserConfirmShippingPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserConfirmShippingPlan(ctx, req.(*UserConfirmShippingPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserGetShippingPlanQuotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetShippingPlanQuotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserGetShippingPlanQuotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserGetShippingPlanQuotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserGetShippingPlanQuotation(ctx, req.(*UserGetShippingPlanQuotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserUpdateShippingBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateShippingBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserUpdateShippingBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserUpdateShippingBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserUpdateShippingBox(ctx, req.(*UserUpdateShippingBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserUpdateShippingParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateShippingParcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserUpdateShippingParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserUpdateShippingParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserUpdateShippingParcel(ctx, req.(*UserUpdateShippingParcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserListShippingLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListShippingLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserListShippingLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserListShippingLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserListShippingLocation(ctx, req.(*UserListShippingLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserAddShippingLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddShippingLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserAddShippingLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserAddShippingLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserAddShippingLocation(ctx, req.(*UserAddShippingLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserRemoveShippingLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRemoveShippingLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserRemoveShippingLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserRemoveShippingLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserRemoveShippingLocation(ctx, req.(*UserRemoveShippingLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserListPackagingBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListPackagingBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserListPackagingBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserListPackagingBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserListPackagingBox(ctx, req.(*UserListPackagingBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserConfirmShippingParcelPacking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserConfirmShippingParcelPackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserConfirmShippingParcelPacking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserConfirmShippingParcelPacking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserConfirmShippingParcelPacking(ctx, req.(*UserConfirmShippingParcelPackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserConfirmShippingPlanPacked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserConfirmShippingPlanPackedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserConfirmShippingPlanPacked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserConfirmShippingPlanPacked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserConfirmShippingPlanPacked(ctx, req.(*UserConfirmShippingPlanPackedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserConfirmShippingPlanShipped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserConfirmShippingPlanShippedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserConfirmShippingPlanShipped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserConfirmShippingPlanShipped_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserConfirmShippingPlanShipped(ctx, req.(*UserConfirmShippingPlanShippedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserGetShippingPlanPaymentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetShippingPlanPaymentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserGetShippingPlanPaymentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserGetShippingPlanPaymentDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserGetShippingPlanPaymentDetail(ctx, req.(*UserGetShippingPlanPaymentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossDockingFulfillmentAPI_UserReorderShippingParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReorderShippingParcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossDockingFulfillmentAPIServer).UserReorderShippingParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossDockingFulfillmentAPI_UserReorderShippingParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossDockingFulfillmentAPIServer).UserReorderShippingParcel(ctx, req.(*UserReorderShippingParcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrossDockingFulfillmentAPI_ServiceDesc is the grpc.ServiceDesc for CrossDockingFulfillmentAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrossDockingFulfillmentAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ffm.v1.CrossDockingFulfillmentAPI",
	HandlerType: (*CrossDockingFulfillmentAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserCreateShippingPlan",
			Handler:    _CrossDockingFulfillmentAPI_UserCreateShippingPlan_Handler,
		},
		{
			MethodName: "UserListShippingPlan",
			Handler:    _CrossDockingFulfillmentAPI_UserListShippingPlan_Handler,
		},
		{
			MethodName: "UserGetShippingPlan",
			Handler:    _CrossDockingFulfillmentAPI_UserGetShippingPlan_Handler,
		},
		{
			MethodName: "UserUpdateShippingPlanRoute",
			Handler:    _CrossDockingFulfillmentAPI_UserUpdateShippingPlanRoute_Handler,
		},
		{
			MethodName: "UserCancelShippingPlan",
			Handler:    _CrossDockingFulfillmentAPI_UserCancelShippingPlan_Handler,
		},
		{
			MethodName: "UserConfirmShippingPlan",
			Handler:    _CrossDockingFulfillmentAPI_UserConfirmShippingPlan_Handler,
		},
		{
			MethodName: "UserGetShippingPlanQuotation",
			Handler:    _CrossDockingFulfillmentAPI_UserGetShippingPlanQuotation_Handler,
		},
		{
			MethodName: "UserUpdateShippingBox",
			Handler:    _CrossDockingFulfillmentAPI_UserUpdateShippingBox_Handler,
		},
		{
			MethodName: "UserUpdateShippingParcel",
			Handler:    _CrossDockingFulfillmentAPI_UserUpdateShippingParcel_Handler,
		},
		{
			MethodName: "UserListShippingLocation",
			Handler:    _CrossDockingFulfillmentAPI_UserListShippingLocation_Handler,
		},
		{
			MethodName: "UserAddShippingLocation",
			Handler:    _CrossDockingFulfillmentAPI_UserAddShippingLocation_Handler,
		},
		{
			MethodName: "UserRemoveShippingLocation",
			Handler:    _CrossDockingFulfillmentAPI_UserRemoveShippingLocation_Handler,
		},
		{
			MethodName: "UserListPackagingBox",
			Handler:    _CrossDockingFulfillmentAPI_UserListPackagingBox_Handler,
		},
		{
			MethodName: "UserConfirmShippingParcelPacking",
			Handler:    _CrossDockingFulfillmentAPI_UserConfirmShippingParcelPacking_Handler,
		},
		{
			MethodName: "UserConfirmShippingPlanPacked",
			Handler:    _CrossDockingFulfillmentAPI_UserConfirmShippingPlanPacked_Handler,
		},
		{
			MethodName: "UserConfirmShippingPlanShipped",
			Handler:    _CrossDockingFulfillmentAPI_UserConfirmShippingPlanShipped_Handler,
		},
		{
			MethodName: "UserGetShippingPlanPaymentDetail",
			Handler:    _CrossDockingFulfillmentAPI_UserGetShippingPlanPaymentDetail_Handler,
		},
		{
			MethodName: "UserReorderShippingParcel",
			Handler:    _CrossDockingFulfillmentAPI_UserReorderShippingParcel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ffm/v1/cross_dock.proto",
}
