// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/ffm/v1/fulfillment.proto

package ffmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FFMOrderAPI_UserListOrder_FullMethodName              = "/api.ffm.v1.FFMOrderAPI/UserListOrder"
	FFMOrderAPI_UserGetOrder_FullMethodName               = "/api.ffm.v1.FFMOrderAPI/UserGetOrder"
	FFMOrderAPI_UserImportOrder_FullMethodName            = "/api.ffm.v1.FFMOrderAPI/UserImportOrder"
	FFMOrderAPI_UserConfirmOrder_FullMethodName           = "/api.ffm.v1.FFMOrderAPI/UserConfirmOrder"
	FFMOrderAPI_UserCancelOrder_FullMethodName            = "/api.ffm.v1.FFMOrderAPI/UserCancelOrder"
	FFMOrderAPI_UserCountOrderStatus_FullMethodName       = "/api.ffm.v1.FFMOrderAPI/UserCountOrderStatus"
	FFMOrderAPI_UserListOrderImportSession_FullMethodName = "/api.ffm.v1.FFMOrderAPI/UserListOrderImportSession"
)

// FFMOrderAPIClient is the client API for FFMOrderAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FFMOrderAPI is a service that provides fulfillment management for orders.
// Listing	Show created orders in the system: order name, platform, refId, tracking_no, status, create date
// Listing	Filter	Allow filtering by: order name, refID, product, status, tracking_no, date range created, platform
// Import order		Allow importing orders using a template
type FFMOrderAPIClient interface {
	UserListOrder(ctx context.Context, in *UserListOrderRequest, opts ...grpc.CallOption) (*UserListOrderResponse, error)
	UserGetOrder(ctx context.Context, in *UserGetOrderRequest, opts ...grpc.CallOption) (*UserGetOrderResponse, error)
	UserImportOrder(ctx context.Context, in *UserImportOrderRequest, opts ...grpc.CallOption) (*UserImportOrderResponse, error)
	UserConfirmOrder(ctx context.Context, in *UserConfirmOrderRequest, opts ...grpc.CallOption) (*UserConfirmOrderResponse, error)
	UserCancelOrder(ctx context.Context, in *UserCancelOrderRequest, opts ...grpc.CallOption) (*UserCancelOrderResponse, error)
	UserCountOrderStatus(ctx context.Context, in *UserCountOrderStatusRequest, opts ...grpc.CallOption) (*UserCountOrderStatusResponse, error)
	UserListOrderImportSession(ctx context.Context, in *UserListOrderImportSessionRequest, opts ...grpc.CallOption) (*UserListOrderImportSessionResponse, error)
}

type fFMOrderAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewFFMOrderAPIClient(cc grpc.ClientConnInterface) FFMOrderAPIClient {
	return &fFMOrderAPIClient{cc}
}

func (c *fFMOrderAPIClient) UserListOrder(ctx context.Context, in *UserListOrderRequest, opts ...grpc.CallOption) (*UserListOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListOrderResponse)
	err := c.cc.Invoke(ctx, FFMOrderAPI_UserListOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMOrderAPIClient) UserGetOrder(ctx context.Context, in *UserGetOrderRequest, opts ...grpc.CallOption) (*UserGetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetOrderResponse)
	err := c.cc.Invoke(ctx, FFMOrderAPI_UserGetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMOrderAPIClient) UserImportOrder(ctx context.Context, in *UserImportOrderRequest, opts ...grpc.CallOption) (*UserImportOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserImportOrderResponse)
	err := c.cc.Invoke(ctx, FFMOrderAPI_UserImportOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMOrderAPIClient) UserConfirmOrder(ctx context.Context, in *UserConfirmOrderRequest, opts ...grpc.CallOption) (*UserConfirmOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserConfirmOrderResponse)
	err := c.cc.Invoke(ctx, FFMOrderAPI_UserConfirmOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMOrderAPIClient) UserCancelOrder(ctx context.Context, in *UserCancelOrderRequest, opts ...grpc.CallOption) (*UserCancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCancelOrderResponse)
	err := c.cc.Invoke(ctx, FFMOrderAPI_UserCancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMOrderAPIClient) UserCountOrderStatus(ctx context.Context, in *UserCountOrderStatusRequest, opts ...grpc.CallOption) (*UserCountOrderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCountOrderStatusResponse)
	err := c.cc.Invoke(ctx, FFMOrderAPI_UserCountOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMOrderAPIClient) UserListOrderImportSession(ctx context.Context, in *UserListOrderImportSessionRequest, opts ...grpc.CallOption) (*UserListOrderImportSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListOrderImportSessionResponse)
	err := c.cc.Invoke(ctx, FFMOrderAPI_UserListOrderImportSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FFMOrderAPIServer is the server API for FFMOrderAPI service.
// All implementations should embed UnimplementedFFMOrderAPIServer
// for forward compatibility.
//
// FFMOrderAPI is a service that provides fulfillment management for orders.
// Listing	Show created orders in the system: order name, platform, refId, tracking_no, status, create date
// Listing	Filter	Allow filtering by: order name, refID, product, status, tracking_no, date range created, platform
// Import order		Allow importing orders using a template
type FFMOrderAPIServer interface {
	UserListOrder(context.Context, *UserListOrderRequest) (*UserListOrderResponse, error)
	UserGetOrder(context.Context, *UserGetOrderRequest) (*UserGetOrderResponse, error)
	UserImportOrder(context.Context, *UserImportOrderRequest) (*UserImportOrderResponse, error)
	UserConfirmOrder(context.Context, *UserConfirmOrderRequest) (*UserConfirmOrderResponse, error)
	UserCancelOrder(context.Context, *UserCancelOrderRequest) (*UserCancelOrderResponse, error)
	UserCountOrderStatus(context.Context, *UserCountOrderStatusRequest) (*UserCountOrderStatusResponse, error)
	UserListOrderImportSession(context.Context, *UserListOrderImportSessionRequest) (*UserListOrderImportSessionResponse, error)
}

// UnimplementedFFMOrderAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFFMOrderAPIServer struct{}

func (UnimplementedFFMOrderAPIServer) UserListOrder(context.Context, *UserListOrderRequest) (*UserListOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListOrder not implemented")
}
func (UnimplementedFFMOrderAPIServer) UserGetOrder(context.Context, *UserGetOrderRequest) (*UserGetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetOrder not implemented")
}
func (UnimplementedFFMOrderAPIServer) UserImportOrder(context.Context, *UserImportOrderRequest) (*UserImportOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserImportOrder not implemented")
}
func (UnimplementedFFMOrderAPIServer) UserConfirmOrder(context.Context, *UserConfirmOrderRequest) (*UserConfirmOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserConfirmOrder not implemented")
}
func (UnimplementedFFMOrderAPIServer) UserCancelOrder(context.Context, *UserCancelOrderRequest) (*UserCancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCancelOrder not implemented")
}
func (UnimplementedFFMOrderAPIServer) UserCountOrderStatus(context.Context, *UserCountOrderStatusRequest) (*UserCountOrderStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCountOrderStatus not implemented")
}
func (UnimplementedFFMOrderAPIServer) UserListOrderImportSession(context.Context, *UserListOrderImportSessionRequest) (*UserListOrderImportSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListOrderImportSession not implemented")
}
func (UnimplementedFFMOrderAPIServer) testEmbeddedByValue() {}

// UnsafeFFMOrderAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FFMOrderAPIServer will
// result in compilation errors.
type UnsafeFFMOrderAPIServer interface {
	mustEmbedUnimplementedFFMOrderAPIServer()
}

func RegisterFFMOrderAPIServer(s grpc.ServiceRegistrar, srv FFMOrderAPIServer) {
	// If the following call pancis, it indicates UnimplementedFFMOrderAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FFMOrderAPI_ServiceDesc, srv)
}

func _FFMOrderAPI_UserListOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMOrderAPIServer).UserListOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMOrderAPI_UserListOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMOrderAPIServer).UserListOrder(ctx, req.(*UserListOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMOrderAPI_UserGetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMOrderAPIServer).UserGetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMOrderAPI_UserGetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMOrderAPIServer).UserGetOrder(ctx, req.(*UserGetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMOrderAPI_UserImportOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserImportOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMOrderAPIServer).UserImportOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMOrderAPI_UserImportOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMOrderAPIServer).UserImportOrder(ctx, req.(*UserImportOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMOrderAPI_UserConfirmOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserConfirmOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMOrderAPIServer).UserConfirmOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMOrderAPI_UserConfirmOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMOrderAPIServer).UserConfirmOrder(ctx, req.(*UserConfirmOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMOrderAPI_UserCancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMOrderAPIServer).UserCancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMOrderAPI_UserCancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMOrderAPIServer).UserCancelOrder(ctx, req.(*UserCancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMOrderAPI_UserCountOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCountOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMOrderAPIServer).UserCountOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMOrderAPI_UserCountOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMOrderAPIServer).UserCountOrderStatus(ctx, req.(*UserCountOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMOrderAPI_UserListOrderImportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListOrderImportSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMOrderAPIServer).UserListOrderImportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMOrderAPI_UserListOrderImportSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMOrderAPIServer).UserListOrderImportSession(ctx, req.(*UserListOrderImportSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FFMOrderAPI_ServiceDesc is the grpc.ServiceDesc for FFMOrderAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FFMOrderAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ffm.v1.FFMOrderAPI",
	HandlerType: (*FFMOrderAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserListOrder",
			Handler:    _FFMOrderAPI_UserListOrder_Handler,
		},
		{
			MethodName: "UserGetOrder",
			Handler:    _FFMOrderAPI_UserGetOrder_Handler,
		},
		{
			MethodName: "UserImportOrder",
			Handler:    _FFMOrderAPI_UserImportOrder_Handler,
		},
		{
			MethodName: "UserConfirmOrder",
			Handler:    _FFMOrderAPI_UserConfirmOrder_Handler,
		},
		{
			MethodName: "UserCancelOrder",
			Handler:    _FFMOrderAPI_UserCancelOrder_Handler,
		},
		{
			MethodName: "UserCountOrderStatus",
			Handler:    _FFMOrderAPI_UserCountOrderStatus_Handler,
		},
		{
			MethodName: "UserListOrderImportSession",
			Handler:    _FFMOrderAPI_UserListOrderImportSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ffm/v1/fulfillment.proto",
}
