// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/ffm/v1/product.proto

package ffmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FFMProductAPI_UserListProductVariant_FullMethodName       = "/api.ffm.v1.FFMProductAPI/UserListProductVariant"
	FFMProductAPI_UserGetProductVariant_FullMethodName        = "/api.ffm.v1.FFMProductAPI/UserGetProductVariant"
	FFMProductAPI_UserListProductImportSession_FullMethodName = "/api.ffm.v1.FFMProductAPI/UserListProductImportSession"
	FFMProductAPI_UserImportProduct_FullMethodName            = "/api.ffm.v1.FFMProductAPI/UserImportProduct"
	FFMProductAPI_UserUpdateProductVariant_FullMethodName     = "/api.ffm.v1.FFMProductAPI/UserUpdateProductVariant"
	FFMProductAPI_UserSubmitProductVariant_FullMethodName     = "/api.ffm.v1.FFMProductAPI/UserSubmitProductVariant"
)

// FFMProductAPIClient is the client API for FFMProductAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FFMProductAPIClient interface {
	// Show list of created products, with pagination, sort by columns: Image, product name, sku, catalog, create date, actions
	UserListProductVariant(ctx context.Context, in *UserListProductVariantRequest, opts ...grpc.CallOption) (*UserListProductVariantResponse, error)
	UserGetProductVariant(ctx context.Context, in *UserGetProductVariantRequest, opts ...grpc.CallOption) (*UserGetProductVariantResponse, error)
	UserListProductImportSession(ctx context.Context, in *UserListProductImportSessionRequest, opts ...grpc.CallOption) (*UserListProductImportSessionResponse, error)
	UserImportProduct(ctx context.Context, in *UserImportProductRequest, opts ...grpc.CallOption) (*UserImportProductResponse, error)
	UserUpdateProductVariant(ctx context.Context, in *UserUpdateProductVariantRequest, opts ...grpc.CallOption) (*UserUpdateProductVariantResponse, error)
	UserSubmitProductVariant(ctx context.Context, in *UserSubmitProductVariantRequest, opts ...grpc.CallOption) (*UserSubmitProductVariantResponse, error)
}

type fFMProductAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewFFMProductAPIClient(cc grpc.ClientConnInterface) FFMProductAPIClient {
	return &fFMProductAPIClient{cc}
}

func (c *fFMProductAPIClient) UserListProductVariant(ctx context.Context, in *UserListProductVariantRequest, opts ...grpc.CallOption) (*UserListProductVariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListProductVariantResponse)
	err := c.cc.Invoke(ctx, FFMProductAPI_UserListProductVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMProductAPIClient) UserGetProductVariant(ctx context.Context, in *UserGetProductVariantRequest, opts ...grpc.CallOption) (*UserGetProductVariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetProductVariantResponse)
	err := c.cc.Invoke(ctx, FFMProductAPI_UserGetProductVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMProductAPIClient) UserListProductImportSession(ctx context.Context, in *UserListProductImportSessionRequest, opts ...grpc.CallOption) (*UserListProductImportSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListProductImportSessionResponse)
	err := c.cc.Invoke(ctx, FFMProductAPI_UserListProductImportSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMProductAPIClient) UserImportProduct(ctx context.Context, in *UserImportProductRequest, opts ...grpc.CallOption) (*UserImportProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserImportProductResponse)
	err := c.cc.Invoke(ctx, FFMProductAPI_UserImportProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMProductAPIClient) UserUpdateProductVariant(ctx context.Context, in *UserUpdateProductVariantRequest, opts ...grpc.CallOption) (*UserUpdateProductVariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUpdateProductVariantResponse)
	err := c.cc.Invoke(ctx, FFMProductAPI_UserUpdateProductVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFMProductAPIClient) UserSubmitProductVariant(ctx context.Context, in *UserSubmitProductVariantRequest, opts ...grpc.CallOption) (*UserSubmitProductVariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSubmitProductVariantResponse)
	err := c.cc.Invoke(ctx, FFMProductAPI_UserSubmitProductVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FFMProductAPIServer is the server API for FFMProductAPI service.
// All implementations should embed UnimplementedFFMProductAPIServer
// for forward compatibility.
type FFMProductAPIServer interface {
	// Show list of created products, with pagination, sort by columns: Image, product name, sku, catalog, create date, actions
	UserListProductVariant(context.Context, *UserListProductVariantRequest) (*UserListProductVariantResponse, error)
	UserGetProductVariant(context.Context, *UserGetProductVariantRequest) (*UserGetProductVariantResponse, error)
	UserListProductImportSession(context.Context, *UserListProductImportSessionRequest) (*UserListProductImportSessionResponse, error)
	UserImportProduct(context.Context, *UserImportProductRequest) (*UserImportProductResponse, error)
	UserUpdateProductVariant(context.Context, *UserUpdateProductVariantRequest) (*UserUpdateProductVariantResponse, error)
	UserSubmitProductVariant(context.Context, *UserSubmitProductVariantRequest) (*UserSubmitProductVariantResponse, error)
}

// UnimplementedFFMProductAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFFMProductAPIServer struct{}

func (UnimplementedFFMProductAPIServer) UserListProductVariant(context.Context, *UserListProductVariantRequest) (*UserListProductVariantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListProductVariant not implemented")
}
func (UnimplementedFFMProductAPIServer) UserGetProductVariant(context.Context, *UserGetProductVariantRequest) (*UserGetProductVariantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetProductVariant not implemented")
}
func (UnimplementedFFMProductAPIServer) UserListProductImportSession(context.Context, *UserListProductImportSessionRequest) (*UserListProductImportSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListProductImportSession not implemented")
}
func (UnimplementedFFMProductAPIServer) UserImportProduct(context.Context, *UserImportProductRequest) (*UserImportProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserImportProduct not implemented")
}
func (UnimplementedFFMProductAPIServer) UserUpdateProductVariant(context.Context, *UserUpdateProductVariantRequest) (*UserUpdateProductVariantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUpdateProductVariant not implemented")
}
func (UnimplementedFFMProductAPIServer) UserSubmitProductVariant(context.Context, *UserSubmitProductVariantRequest) (*UserSubmitProductVariantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserSubmitProductVariant not implemented")
}
func (UnimplementedFFMProductAPIServer) testEmbeddedByValue() {}

// UnsafeFFMProductAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FFMProductAPIServer will
// result in compilation errors.
type UnsafeFFMProductAPIServer interface {
	mustEmbedUnimplementedFFMProductAPIServer()
}

func RegisterFFMProductAPIServer(s grpc.ServiceRegistrar, srv FFMProductAPIServer) {
	// If the following call pancis, it indicates UnimplementedFFMProductAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FFMProductAPI_ServiceDesc, srv)
}

func _FFMProductAPI_UserListProductVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListProductVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMProductAPIServer).UserListProductVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMProductAPI_UserListProductVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMProductAPIServer).UserListProductVariant(ctx, req.(*UserListProductVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMProductAPI_UserGetProductVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetProductVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMProductAPIServer).UserGetProductVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMProductAPI_UserGetProductVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMProductAPIServer).UserGetProductVariant(ctx, req.(*UserGetProductVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMProductAPI_UserListProductImportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListProductImportSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMProductAPIServer).UserListProductImportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMProductAPI_UserListProductImportSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMProductAPIServer).UserListProductImportSession(ctx, req.(*UserListProductImportSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMProductAPI_UserImportProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserImportProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMProductAPIServer).UserImportProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMProductAPI_UserImportProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMProductAPIServer).UserImportProduct(ctx, req.(*UserImportProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMProductAPI_UserUpdateProductVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateProductVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMProductAPIServer).UserUpdateProductVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMProductAPI_UserUpdateProductVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMProductAPIServer).UserUpdateProductVariant(ctx, req.(*UserUpdateProductVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFMProductAPI_UserSubmitProductVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSubmitProductVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFMProductAPIServer).UserSubmitProductVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFMProductAPI_UserSubmitProductVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFMProductAPIServer).UserSubmitProductVariant(ctx, req.(*UserSubmitProductVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FFMProductAPI_ServiceDesc is the grpc.ServiceDesc for FFMProductAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FFMProductAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ffm.v1.FFMProductAPI",
	HandlerType: (*FFMProductAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserListProductVariant",
			Handler:    _FFMProductAPI_UserListProductVariant_Handler,
		},
		{
			MethodName: "UserGetProductVariant",
			Handler:    _FFMProductAPI_UserGetProductVariant_Handler,
		},
		{
			MethodName: "UserListProductImportSession",
			Handler:    _FFMProductAPI_UserListProductImportSession_Handler,
		},
		{
			MethodName: "UserImportProduct",
			Handler:    _FFMProductAPI_UserImportProduct_Handler,
		},
		{
			MethodName: "UserUpdateProductVariant",
			Handler:    _FFMProductAPI_UserUpdateProductVariant_Handler,
		},
		{
			MethodName: "UserSubmitProductVariant",
			Handler:    _FFMProductAPI_UserSubmitProductVariant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ffm/v1/product.proto",
}
