// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/order/v1/api_vendor_wallet.proto

package orderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VendorWalletAPI_VendorGetWallet_FullMethodName = "/api.order.v1.VendorWalletAPI/VendorGetWallet"
)

// VendorWalletAPIClient is the client API for VendorWalletAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VendorWalletAPIClient interface {
	VendorGetWallet(ctx context.Context, in *VendorGetWalletRequest, opts ...grpc.CallOption) (*VendorGetWalletResponse, error)
}

type vendorWalletAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewVendorWalletAPIClient(cc grpc.ClientConnInterface) VendorWalletAPIClient {
	return &vendorWalletAPIClient{cc}
}

func (c *vendorWalletAPIClient) VendorGetWallet(ctx context.Context, in *VendorGetWalletRequest, opts ...grpc.CallOption) (*VendorGetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorGetWalletResponse)
	err := c.cc.Invoke(ctx, VendorWalletAPI_VendorGetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VendorWalletAPIServer is the server API for VendorWalletAPI service.
// All implementations should embed UnimplementedVendorWalletAPIServer
// for forward compatibility.
type VendorWalletAPIServer interface {
	VendorGetWallet(context.Context, *VendorGetWalletRequest) (*VendorGetWalletResponse, error)
}

// UnimplementedVendorWalletAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVendorWalletAPIServer struct{}

func (UnimplementedVendorWalletAPIServer) VendorGetWallet(context.Context, *VendorGetWalletRequest) (*VendorGetWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VendorGetWallet not implemented")
}
func (UnimplementedVendorWalletAPIServer) testEmbeddedByValue() {}

// UnsafeVendorWalletAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VendorWalletAPIServer will
// result in compilation errors.
type UnsafeVendorWalletAPIServer interface {
	mustEmbedUnimplementedVendorWalletAPIServer()
}

func RegisterVendorWalletAPIServer(s grpc.ServiceRegistrar, srv VendorWalletAPIServer) {
	// If the following call pancis, it indicates UnimplementedVendorWalletAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VendorWalletAPI_ServiceDesc, srv)
}

func _VendorWalletAPI_VendorGetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendorGetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorWalletAPIServer).VendorGetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorWalletAPI_VendorGetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorWalletAPIServer).VendorGetWallet(ctx, req.(*VendorGetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VendorWalletAPI_ServiceDesc is the grpc.ServiceDesc for VendorWalletAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VendorWalletAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.order.v1.VendorWalletAPI",
	HandlerType: (*VendorWalletAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VendorGetWallet",
			Handler:    _VendorWalletAPI_VendorGetWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/order/v1/api_vendor_wallet.proto",
}
