// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/order/v1/data_vendor_order_price.proto

package orderv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/gearment/gea-next/vendorsdk/common/type/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VendorOrderPriceCalculation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorOrderPriceCalculation) Reset() {
	*x = VendorOrderPriceCalculation{}
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOrderPriceCalculation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOrderPriceCalculation) ProtoMessage() {}

func (x *VendorOrderPriceCalculation) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOrderPriceCalculation.ProtoReflect.Descriptor instead.
func (*VendorOrderPriceCalculation) Descriptor() ([]byte, []int) {
	return file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP(), []int{0}
}

type VendorOrderPriceCalculation_Billing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IOSS number for EU tax compliance
	IossNumber string `protobuf:"bytes,1,opt,name=ioss_number,json=iossNumber,proto3" json:"ioss_number,omitempty"`
	// Tax identification number
	TaxNumber     string `protobuf:"bytes,2,opt,name=tax_number,json=taxNumber,proto3" json:"tax_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorOrderPriceCalculation_Billing) Reset() {
	*x = VendorOrderPriceCalculation_Billing{}
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOrderPriceCalculation_Billing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOrderPriceCalculation_Billing) ProtoMessage() {}

func (x *VendorOrderPriceCalculation_Billing) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOrderPriceCalculation_Billing.ProtoReflect.Descriptor instead.
func (*VendorOrderPriceCalculation_Billing) Descriptor() ([]byte, []int) {
	return file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP(), []int{0, 0}
}

func (x *VendorOrderPriceCalculation_Billing) GetIossNumber() string {
	if x != nil {
		return x.IossNumber
	}
	return ""
}

func (x *VendorOrderPriceCalculation_Billing) GetTaxNumber() string {
	if x != nil {
		return x.TaxNumber
	}
	return ""
}

type VendorOrderPriceCalculation_Shipping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shipping address information
	Address *VendorOrderPriceCalculation_Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Pre-purchased shipping label (optional)
	Label         *VendorOrderPriceCalculation_Label `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorOrderPriceCalculation_Shipping) Reset() {
	*x = VendorOrderPriceCalculation_Shipping{}
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOrderPriceCalculation_Shipping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOrderPriceCalculation_Shipping) ProtoMessage() {}

func (x *VendorOrderPriceCalculation_Shipping) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOrderPriceCalculation_Shipping.ProtoReflect.Descriptor instead.
func (*VendorOrderPriceCalculation_Shipping) Descriptor() ([]byte, []int) {
	return file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP(), []int{0, 1}
}

func (x *VendorOrderPriceCalculation_Shipping) GetAddress() *VendorOrderPriceCalculation_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *VendorOrderPriceCalculation_Shipping) GetLabel() *VendorOrderPriceCalculation_Label {
	if x != nil {
		return x.Label
	}
	return nil
}

type VendorOrderPriceCalculation_Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shipping method
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// State/province code (ISO 3166-2)
	StateCode string `protobuf:"bytes,2,opt,name=state_code,json=stateCode,proto3" json:"state_code,omitempty"`
	// Country code (ISO 3166-1 alpha-2)
	CountryCode string `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// Street address line 1
	Street1 string `protobuf:"bytes,4,opt,name=street1,proto3" json:"street1,omitempty"`
	// Street address line 2
	Street2       string `protobuf:"bytes,5,opt,name=street2,proto3" json:"street2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorOrderPriceCalculation_Address) Reset() {
	*x = VendorOrderPriceCalculation_Address{}
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOrderPriceCalculation_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOrderPriceCalculation_Address) ProtoMessage() {}

func (x *VendorOrderPriceCalculation_Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOrderPriceCalculation_Address.ProtoReflect.Descriptor instead.
func (*VendorOrderPriceCalculation_Address) Descriptor() ([]byte, []int) {
	return file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP(), []int{0, 2}
}

func (x *VendorOrderPriceCalculation_Address) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *VendorOrderPriceCalculation_Address) GetStateCode() string {
	if x != nil {
		return x.StateCode
	}
	return ""
}

func (x *VendorOrderPriceCalculation_Address) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *VendorOrderPriceCalculation_Address) GetStreet1() string {
	if x != nil {
		return x.Street1
	}
	return ""
}

func (x *VendorOrderPriceCalculation_Address) GetStreet2() string {
	if x != nil {
		return x.Street2
	}
	return ""
}

type VendorOrderPriceCalculation_Label struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL to pre-purchased shipping label (PDF or image)
	Url           string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorOrderPriceCalculation_Label) Reset() {
	*x = VendorOrderPriceCalculation_Label{}
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOrderPriceCalculation_Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOrderPriceCalculation_Label) ProtoMessage() {}

func (x *VendorOrderPriceCalculation_Label) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOrderPriceCalculation_Label.ProtoReflect.Descriptor instead.
func (*VendorOrderPriceCalculation_Label) Descriptor() ([]byte, []int) {
	return file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP(), []int{0, 3}
}

func (x *VendorOrderPriceCalculation_Label) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type VendorOrderPriceCalculation_LineItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Product variant ID from catalog
	VariantId string `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	// Quantity to order
	Quantity int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Print locations on the product
	PrintLocations []string `protobuf:"bytes,3,rep,name=print_locations,json=printLocations,proto3" json:"print_locations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VendorOrderPriceCalculation_LineItem) Reset() {
	*x = VendorOrderPriceCalculation_LineItem{}
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOrderPriceCalculation_LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOrderPriceCalculation_LineItem) ProtoMessage() {}

func (x *VendorOrderPriceCalculation_LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOrderPriceCalculation_LineItem.ProtoReflect.Descriptor instead.
func (*VendorOrderPriceCalculation_LineItem) Descriptor() ([]byte, []int) {
	return file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP(), []int{0, 4}
}

func (x *VendorOrderPriceCalculation_LineItem) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *VendorOrderPriceCalculation_LineItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *VendorOrderPriceCalculation_LineItem) GetPrintLocations() []string {
	if x != nil {
		return x.PrintLocations
	}
	return nil
}

type VendorOrderPriceCalculation_GiftMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the gift message
	GiftMessageId string `protobuf:"bytes,1,opt,name=gift_message_id,json=giftMessageId,proto3" json:"gift_message_id,omitempty"`
	// Gift message text content (max 300 characters)
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorOrderPriceCalculation_GiftMessage) Reset() {
	*x = VendorOrderPriceCalculation_GiftMessage{}
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOrderPriceCalculation_GiftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOrderPriceCalculation_GiftMessage) ProtoMessage() {}

func (x *VendorOrderPriceCalculation_GiftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOrderPriceCalculation_GiftMessage.ProtoReflect.Descriptor instead.
func (*VendorOrderPriceCalculation_GiftMessage) Descriptor() ([]byte, []int) {
	return file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP(), []int{0, 5}
}

func (x *VendorOrderPriceCalculation_GiftMessage) GetGiftMessageId() string {
	if x != nil {
		return x.GiftMessageId
	}
	return ""
}

func (x *VendorOrderPriceCalculation_GiftMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type VendorOrderPriceCalculation_FeePriceQuote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID this fee applies to
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Line item ID this fee applies to
	LineItemId string `protobuf:"bytes,2,opt,name=line_item_id,json=lineItemId,proto3" json:"line_item_id,omitempty"`
	// Fee code/identifier (e.g., "RUSH_FEE", "GIFT_MESSAGE_FEE")
	FeeCode string `protobuf:"bytes,3,opt,name=fee_code,json=feeCode,proto3" json:"fee_code,omitempty"`
	// Fee amount
	Amount        *v1.Money `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorOrderPriceCalculation_FeePriceQuote) Reset() {
	*x = VendorOrderPriceCalculation_FeePriceQuote{}
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOrderPriceCalculation_FeePriceQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOrderPriceCalculation_FeePriceQuote) ProtoMessage() {}

func (x *VendorOrderPriceCalculation_FeePriceQuote) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOrderPriceCalculation_FeePriceQuote.ProtoReflect.Descriptor instead.
func (*VendorOrderPriceCalculation_FeePriceQuote) Descriptor() ([]byte, []int) {
	return file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP(), []int{0, 6}
}

func (x *VendorOrderPriceCalculation_FeePriceQuote) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *VendorOrderPriceCalculation_FeePriceQuote) GetLineItemId() string {
	if x != nil {
		return x.LineItemId
	}
	return ""
}

func (x *VendorOrderPriceCalculation_FeePriceQuote) GetFeeCode() string {
	if x != nil {
		return x.FeeCode
	}
	return ""
}

func (x *VendorOrderPriceCalculation_FeePriceQuote) GetAmount() *v1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

type VendorOrderPriceCalculation_LineItemPriceQuote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Line item subtotal (item_price × quantity, before tax/fees/discount)
	LineSubTotal *v1.Money `protobuf:"bytes,1,opt,name=line_sub_total,json=lineSubTotal,proto3" json:"line_sub_total,omitempty"`
	// Tax for this line item
	LineTax *v1.Money `protobuf:"bytes,2,opt,name=line_tax,json=lineTax,proto3" json:"line_tax,omitempty"`
	// Additional fees for this line item
	LineFee *v1.Money `protobuf:"bytes,3,opt,name=line_fee,json=lineFee,proto3" json:"line_fee,omitempty"`
	// Discount applied to this line item
	LineDiscount *v1.Money `protobuf:"bytes,4,opt,name=line_discount,json=lineDiscount,proto3" json:"line_discount,omitempty"`
	// Total for this line item (subtotal + tax + fee - discount)
	LineTotal *v1.Money `protobuf:"bytes,5,opt,name=line_total,json=lineTotal,proto3" json:"line_total,omitempty"`
	// Unit price per item
	ItemPrice *v1.Money `protobuf:"bytes,6,opt,name=item_price,json=itemPrice,proto3" json:"item_price,omitempty"`
	// Per-item fee
	ItemFee *v1.Money `protobuf:"bytes,7,opt,name=item_fee,json=itemFee,proto3" json:"item_fee,omitempty"`
	// Per-item discount
	ItemDiscount *v1.Money `protobuf:"bytes,8,opt,name=item_discount,json=itemDiscount,proto3" json:"item_discount,omitempty"`
	// Quantity of items
	ItemQuantity int32 `protobuf:"varint,9,opt,name=item_quantity,json=itemQuantity,proto3" json:"item_quantity,omitempty"`
	// Internal line item ID
	Id int64 `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	// Base price per unit (before fees/discount)
	UnitBasePrice *v1.Money `protobuf:"bytes,11,opt,name=unit_base_price,json=unitBasePrice,proto3" json:"unit_base_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) Reset() {
	*x = VendorOrderPriceCalculation_LineItemPriceQuote{}
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOrderPriceCalculation_LineItemPriceQuote) ProtoMessage() {}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOrderPriceCalculation_LineItemPriceQuote.ProtoReflect.Descriptor instead.
func (*VendorOrderPriceCalculation_LineItemPriceQuote) Descriptor() ([]byte, []int) {
	return file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP(), []int{0, 7}
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetLineSubTotal() *v1.Money {
	if x != nil {
		return x.LineSubTotal
	}
	return nil
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetLineTax() *v1.Money {
	if x != nil {
		return x.LineTax
	}
	return nil
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetLineFee() *v1.Money {
	if x != nil {
		return x.LineFee
	}
	return nil
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetLineDiscount() *v1.Money {
	if x != nil {
		return x.LineDiscount
	}
	return nil
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetLineTotal() *v1.Money {
	if x != nil {
		return x.LineTotal
	}
	return nil
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetItemPrice() *v1.Money {
	if x != nil {
		return x.ItemPrice
	}
	return nil
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetItemFee() *v1.Money {
	if x != nil {
		return x.ItemFee
	}
	return nil
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetItemDiscount() *v1.Money {
	if x != nil {
		return x.ItemDiscount
	}
	return nil
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetItemQuantity() int32 {
	if x != nil {
		return x.ItemQuantity
	}
	return 0
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VendorOrderPriceCalculation_LineItemPriceQuote) GetUnitBasePrice() *v1.Money {
	if x != nil {
		return x.UnitBasePrice
	}
	return nil
}

type VendorOrderPriceCalculation_OrderPriceQuote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total shipping fee for the order
	OrderShippingFee *v1.Money `protobuf:"bytes,1,opt,name=order_shipping_fee,json=orderShippingFee,proto3" json:"order_shipping_fee,omitempty"`
	// Additional processing fees
	OrderFee *v1.Money `protobuf:"bytes,2,opt,name=order_fee,json=orderFee,proto3" json:"order_fee,omitempty"`
	// Total tax for the order
	OrderTax *v1.Money `protobuf:"bytes,3,opt,name=order_tax,json=orderTax,proto3" json:"order_tax,omitempty"`
	// Order subtotal (sum of all line items before tax/fees/discount)
	OrderSubTotal *v1.Money `protobuf:"bytes,4,opt,name=order_sub_total,json=orderSubTotal,proto3" json:"order_sub_total,omitempty"`
	// Final order total (subtotal + shipping + tax + fees - discount)
	OrderTotal *v1.Money `protobuf:"bytes,5,opt,name=order_total,json=orderTotal,proto3" json:"order_total,omitempty"`
	// Total discount applied to the order
	OrderDiscount *v1.Money `protobuf:"bytes,6,opt,name=order_discount,json=orderDiscount,proto3" json:"order_discount,omitempty"`
	// Price breakdown for each line item
	LineItems []*VendorOrderPriceCalculation_LineItemPriceQuote `protobuf:"bytes,7,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	// Detailed fee breakdown
	Fees []*VendorOrderPriceCalculation_FeePriceQuote `protobuf:"bytes,8,rep,name=fees,proto3" json:"fees,omitempty"`
	// Gift message fee (if applicable)
	OrderGiftMessageFee *v1.Money `protobuf:"bytes,9,opt,name=order_gift_message_fee,json=orderGiftMessageFee,proto3" json:"order_gift_message_fee,omitempty"`
	// Order handling fee
	OrderHandleFee *v1.Money `protobuf:"bytes,10,opt,name=order_handle_fee,json=orderHandleFee,proto3" json:"order_handle_fee,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) Reset() {
	*x = VendorOrderPriceCalculation_OrderPriceQuote{}
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOrderPriceCalculation_OrderPriceQuote) ProtoMessage() {}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_data_vendor_order_price_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOrderPriceCalculation_OrderPriceQuote.ProtoReflect.Descriptor instead.
func (*VendorOrderPriceCalculation_OrderPriceQuote) Descriptor() ([]byte, []int) {
	return file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP(), []int{0, 8}
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) GetOrderShippingFee() *v1.Money {
	if x != nil {
		return x.OrderShippingFee
	}
	return nil
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) GetOrderFee() *v1.Money {
	if x != nil {
		return x.OrderFee
	}
	return nil
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) GetOrderTax() *v1.Money {
	if x != nil {
		return x.OrderTax
	}
	return nil
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) GetOrderSubTotal() *v1.Money {
	if x != nil {
		return x.OrderSubTotal
	}
	return nil
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) GetOrderTotal() *v1.Money {
	if x != nil {
		return x.OrderTotal
	}
	return nil
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) GetOrderDiscount() *v1.Money {
	if x != nil {
		return x.OrderDiscount
	}
	return nil
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) GetLineItems() []*VendorOrderPriceCalculation_LineItemPriceQuote {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) GetFees() []*VendorOrderPriceCalculation_FeePriceQuote {
	if x != nil {
		return x.Fees
	}
	return nil
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) GetOrderGiftMessageFee() *v1.Money {
	if x != nil {
		return x.OrderGiftMessageFee
	}
	return nil
}

func (x *VendorOrderPriceCalculation_OrderPriceQuote) GetOrderHandleFee() *v1.Money {
	if x != nil {
		return x.OrderHandleFee
	}
	return nil
}

var File_api_order_v1_data_vendor_order_price_proto protoreflect.FileDescriptor

const file_api_order_v1_data_vendor_order_price_proto_rawDesc = "" +
	"\n" +
	"*api/order/v1/data_vendor_order_price.proto\x12\fapi.order.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1acommon/type/v1/money.proto\"\x96\x15\n" +
	"\x1bVendorOrderPriceCalculation\x1at\n" +
	"\aBilling\x125\n" +
	"\vioss_number\x18\x01 \x01(\tB\x14\xbaH\x11r\x0f\x92\x02\fIM1234567890R\n" +
	"iossNumber\x122\n" +
	"\n" +
	"tax_number\x18\x02 \x01(\tB\x13\xbaH\x10r\x0e\x92\x02\vGB123456789R\ttaxNumber\x1a\x9e\x01\n" +
	"\bShipping\x12K\n" +
	"\aaddress\x18\x01 \x01(\v21.api.order.v1.VendorOrderPriceCalculation.AddressR\aaddress\x12E\n" +
	"\x05label\x18\x02 \x01(\v2/.api.order.v1.VendorOrderPriceCalculation.LabelR\x05label\x1a\xcb\x02\n" +
	"\aAddress\x12\xa7\x01\n" +
	"\x06method\x18\x01 \x01(\tB\x8e\x01\xbaH\x8a\x01r\x87\x01R\bstandardR\x0fMETHOD_STANDARDR\aeconomyR\x0eMETHOD_ECONOMYR\x05stampR\fMETHOD_STAMPR\x06groundR\rMETHOD_GROUNDR\bfastshipR\x10METHOD_FAST_SHIP\x92\x02\bstandardR\x06method\x12)\n" +
	"\n" +
	"state_code\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x92\x02\x02CAR\tstateCode\x12-\n" +
	"\fcountry_code\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x92\x02\x02USR\vcountryCode\x12\"\n" +
	"\astreet1\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\xac\x02R\astreet1\x12\x18\n" +
	"\astreet2\x18\x05 \x01(\tR\astreet2\x1aI\n" +
	"\x05Label\x12@\n" +
	"\x03url\x18\x01 \x01(\tB.\xbaH+r)\x92\x02&https://example.com/shipping-label.pdfR\x03url\x1a\x95\x03\n" +
	"\bLineItem\x129\n" +
	"\n" +
	"variant_id\x18\x01 \x01(\tB\x1a\xbaH\x17r\x15\x10\x01\x18\x1e\x92\x02\x0evariant_abc123R\tvariantId\x12%\n" +
	"\bquantity\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04@\x02 \x00R\bquantity\x12\xa6\x02\n" +
	"\x0fprint_locations\x18\x03 \x03(\tB\xfc\x01\xbaH\xf8\x01\x92\x01\xf4\x01\"\xf1\x01r\xee\x01R\x05frontR\x19PRINT_LOCATION_CODE_FRONTR\x04backR\x18PRINT_LOCATION_CODE_BACKR\vleft_sleeveR\x1fPRINT_LOCATION_CODE_LEFT_SLEEVER\fright_sleeveR PRINT_LOCATION_CODE_RIGHT_SLEEVER\x06pocketR\x1aPRINT_LOCATION_CODE_POCKETR\x05wholeR\x19PRINT_LOCATION_CODE_WHOLE\x92\x02\x05frontR\x0eprintLocations\x1a\xa6\x01\n" +
	"\vGiftMessage\x12@\n" +
	"\x0fgift_message_id\x18\x01 \x01(\tB\x18\xbaH\x15r\x13\x10\x01\x18\x1e\x92\x02\fgift_msg_123R\rgiftMessageId\x12U\n" +
	"\acontent\x18\x02 \x01(\tB;\xbaH8r6\x18\xac\x02\x92\x020Happy Birthday! Wishing you all the best. - JohnR\acontent\x1a\x96\x01\n" +
	"\rFeePriceQuote\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12 \n" +
	"\fline_item_id\x18\x02 \x01(\tR\n" +
	"lineItemId\x12\x19\n" +
	"\bfee_code\x18\x03 \x01(\tR\afeeCode\x12-\n" +
	"\x06amount\x18\x04 \x01(\v2\x15.common.type.v1.MoneyR\x06amount\x1a\xbf\x04\n" +
	"\x12LineItemPriceQuote\x12;\n" +
	"\x0eline_sub_total\x18\x01 \x01(\v2\x15.common.type.v1.MoneyR\flineSubTotal\x120\n" +
	"\bline_tax\x18\x02 \x01(\v2\x15.common.type.v1.MoneyR\alineTax\x120\n" +
	"\bline_fee\x18\x03 \x01(\v2\x15.common.type.v1.MoneyR\alineFee\x12:\n" +
	"\rline_discount\x18\x04 \x01(\v2\x15.common.type.v1.MoneyR\flineDiscount\x124\n" +
	"\n" +
	"line_total\x18\x05 \x01(\v2\x15.common.type.v1.MoneyR\tlineTotal\x124\n" +
	"\n" +
	"item_price\x18\x06 \x01(\v2\x15.common.type.v1.MoneyR\titemPrice\x120\n" +
	"\bitem_fee\x18\a \x01(\v2\x15.common.type.v1.MoneyR\aitemFee\x12:\n" +
	"\ritem_discount\x18\b \x01(\v2\x15.common.type.v1.MoneyR\fitemDiscount\x12#\n" +
	"\ritem_quantity\x18\t \x01(\x05R\fitemQuantity\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\x03R\x02id\x12=\n" +
	"\x0funit_base_price\x18\v \x01(\v2\x15.common.type.v1.MoneyR\runitBasePrice\x1a\xaa\x05\n" +
	"\x0fOrderPriceQuote\x12C\n" +
	"\x12order_shipping_fee\x18\x01 \x01(\v2\x15.common.type.v1.MoneyR\x10orderShippingFee\x122\n" +
	"\torder_fee\x18\x02 \x01(\v2\x15.common.type.v1.MoneyR\borderFee\x122\n" +
	"\torder_tax\x18\x03 \x01(\v2\x15.common.type.v1.MoneyR\borderTax\x12=\n" +
	"\x0forder_sub_total\x18\x04 \x01(\v2\x15.common.type.v1.MoneyR\rorderSubTotal\x126\n" +
	"\vorder_total\x18\x05 \x01(\v2\x15.common.type.v1.MoneyR\n" +
	"orderTotal\x12<\n" +
	"\x0eorder_discount\x18\x06 \x01(\v2\x15.common.type.v1.MoneyR\rorderDiscount\x12[\n" +
	"\n" +
	"line_items\x18\a \x03(\v2<.api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuoteR\tlineItems\x12K\n" +
	"\x04fees\x18\b \x03(\v27.api.order.v1.VendorOrderPriceCalculation.FeePriceQuoteR\x04fees\x12J\n" +
	"\x16order_gift_message_fee\x18\t \x01(\v2\x15.common.type.v1.MoneyR\x13orderGiftMessageFee\x12?\n" +
	"\x10order_handle_fee\x18\n" +
	" \x01(\v2\x15.common.type.v1.MoneyR\x0eorderHandleFeeB\xbc\x01\n" +
	"\x10com.api.order.v1B\x19DataVendorOrderPriceProtoP\x01Z;github.com/gearment/gea-next/vendorsdk/api/order/v1;orderv1\xa2\x02\x03AOX\xaa\x02\fApi.Order.V1\xca\x02\fApi\\Order\\V1\xe2\x02\x18Api\\Order\\V1\\GPBMetadata\xea\x02\x0eApi::Order::V1b\x06proto3"

var (
	file_api_order_v1_data_vendor_order_price_proto_rawDescOnce sync.Once
	file_api_order_v1_data_vendor_order_price_proto_rawDescData []byte
)

func file_api_order_v1_data_vendor_order_price_proto_rawDescGZIP() []byte {
	file_api_order_v1_data_vendor_order_price_proto_rawDescOnce.Do(func() {
		file_api_order_v1_data_vendor_order_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_v1_data_vendor_order_price_proto_rawDesc), len(file_api_order_v1_data_vendor_order_price_proto_rawDesc)))
	})
	return file_api_order_v1_data_vendor_order_price_proto_rawDescData
}

var file_api_order_v1_data_vendor_order_price_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_order_v1_data_vendor_order_price_proto_goTypes = []any{
	(*VendorOrderPriceCalculation)(nil),                    // 0: api.order.v1.VendorOrderPriceCalculation
	(*VendorOrderPriceCalculation_Billing)(nil),            // 1: api.order.v1.VendorOrderPriceCalculation.Billing
	(*VendorOrderPriceCalculation_Shipping)(nil),           // 2: api.order.v1.VendorOrderPriceCalculation.Shipping
	(*VendorOrderPriceCalculation_Address)(nil),            // 3: api.order.v1.VendorOrderPriceCalculation.Address
	(*VendorOrderPriceCalculation_Label)(nil),              // 4: api.order.v1.VendorOrderPriceCalculation.Label
	(*VendorOrderPriceCalculation_LineItem)(nil),           // 5: api.order.v1.VendorOrderPriceCalculation.LineItem
	(*VendorOrderPriceCalculation_GiftMessage)(nil),        // 6: api.order.v1.VendorOrderPriceCalculation.GiftMessage
	(*VendorOrderPriceCalculation_FeePriceQuote)(nil),      // 7: api.order.v1.VendorOrderPriceCalculation.FeePriceQuote
	(*VendorOrderPriceCalculation_LineItemPriceQuote)(nil), // 8: api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote
	(*VendorOrderPriceCalculation_OrderPriceQuote)(nil),    // 9: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote
	(*v1.Money)(nil), // 10: common.type.v1.Money
}
var file_api_order_v1_data_vendor_order_price_proto_depIdxs = []int32{
	3,  // 0: api.order.v1.VendorOrderPriceCalculation.Shipping.address:type_name -> api.order.v1.VendorOrderPriceCalculation.Address
	4,  // 1: api.order.v1.VendorOrderPriceCalculation.Shipping.label:type_name -> api.order.v1.VendorOrderPriceCalculation.Label
	10, // 2: api.order.v1.VendorOrderPriceCalculation.FeePriceQuote.amount:type_name -> common.type.v1.Money
	10, // 3: api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote.line_sub_total:type_name -> common.type.v1.Money
	10, // 4: api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote.line_tax:type_name -> common.type.v1.Money
	10, // 5: api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote.line_fee:type_name -> common.type.v1.Money
	10, // 6: api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote.line_discount:type_name -> common.type.v1.Money
	10, // 7: api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote.line_total:type_name -> common.type.v1.Money
	10, // 8: api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote.item_price:type_name -> common.type.v1.Money
	10, // 9: api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote.item_fee:type_name -> common.type.v1.Money
	10, // 10: api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote.item_discount:type_name -> common.type.v1.Money
	10, // 11: api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote.unit_base_price:type_name -> common.type.v1.Money
	10, // 12: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote.order_shipping_fee:type_name -> common.type.v1.Money
	10, // 13: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote.order_fee:type_name -> common.type.v1.Money
	10, // 14: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote.order_tax:type_name -> common.type.v1.Money
	10, // 15: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote.order_sub_total:type_name -> common.type.v1.Money
	10, // 16: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote.order_total:type_name -> common.type.v1.Money
	10, // 17: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote.order_discount:type_name -> common.type.v1.Money
	8,  // 18: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote.line_items:type_name -> api.order.v1.VendorOrderPriceCalculation.LineItemPriceQuote
	7,  // 19: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote.fees:type_name -> api.order.v1.VendorOrderPriceCalculation.FeePriceQuote
	10, // 20: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote.order_gift_message_fee:type_name -> common.type.v1.Money
	10, // 21: api.order.v1.VendorOrderPriceCalculation.OrderPriceQuote.order_handle_fee:type_name -> common.type.v1.Money
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_order_v1_data_vendor_order_price_proto_init() }
func file_api_order_v1_data_vendor_order_price_proto_init() {
	if File_api_order_v1_data_vendor_order_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_v1_data_vendor_order_price_proto_rawDesc), len(file_api_order_v1_data_vendor_order_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_order_v1_data_vendor_order_price_proto_goTypes,
		DependencyIndexes: file_api_order_v1_data_vendor_order_price_proto_depIdxs,
		MessageInfos:      file_api_order_v1_data_vendor_order_price_proto_msgTypes,
	}.Build()
	File_api_order_v1_data_vendor_order_price_proto = out.File
	file_api_order_v1_data_vendor_order_price_proto_goTypes = nil
	file_api_order_v1_data_vendor_order_price_proto_depIdxs = nil
}
