// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/order/v1/internal_vendor_order.proto

package orderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalVendorOrderAPI_InternalVendorListOrder_FullMethodName        = "/api.order.v1.InternalVendorOrderAPI/InternalVendorListOrder"
	InternalVendorOrderAPI_InternalVendorListOrderDraft_FullMethodName   = "/api.order.v1.InternalVendorOrderAPI/InternalVendorListOrderDraft"
	InternalVendorOrderAPI_InternalVendorCreateOrderDraft_FullMethodName = "/api.order.v1.InternalVendorOrderAPI/InternalVendorCreateOrderDraft"
	InternalVendorOrderAPI_InternalVendorGetPriceQuote_FullMethodName    = "/api.order.v1.InternalVendorOrderAPI/InternalVendorGetPriceQuote"
)

// InternalVendorOrderAPIClient is the client API for InternalVendorOrderAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalVendorOrderAPIClient interface {
	InternalVendorListOrder(ctx context.Context, in *InternalVendorListOrderRequest, opts ...grpc.CallOption) (*VendorListOrderResponse, error)
	InternalVendorListOrderDraft(ctx context.Context, in *InternalVendorListOrderDraftRequest, opts ...grpc.CallOption) (*VendorListOrderDraftResponse, error)
	InternalVendorCreateOrderDraft(ctx context.Context, in *InternalVendorCreateOrderDraftRequest, opts ...grpc.CallOption) (*InternalVendorCreateOrderDraftResponse, error)
	InternalVendorGetPriceQuote(ctx context.Context, in *InternalVendorGetPriceQuoteRequest, opts ...grpc.CallOption) (*VendorGetPriceQuoteResponse, error)
}

type internalVendorOrderAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalVendorOrderAPIClient(cc grpc.ClientConnInterface) InternalVendorOrderAPIClient {
	return &internalVendorOrderAPIClient{cc}
}

func (c *internalVendorOrderAPIClient) InternalVendorListOrder(ctx context.Context, in *InternalVendorListOrderRequest, opts ...grpc.CallOption) (*VendorListOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorListOrderResponse)
	err := c.cc.Invoke(ctx, InternalVendorOrderAPI_InternalVendorListOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalVendorOrderAPIClient) InternalVendorListOrderDraft(ctx context.Context, in *InternalVendorListOrderDraftRequest, opts ...grpc.CallOption) (*VendorListOrderDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorListOrderDraftResponse)
	err := c.cc.Invoke(ctx, InternalVendorOrderAPI_InternalVendorListOrderDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalVendorOrderAPIClient) InternalVendorCreateOrderDraft(ctx context.Context, in *InternalVendorCreateOrderDraftRequest, opts ...grpc.CallOption) (*InternalVendorCreateOrderDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalVendorCreateOrderDraftResponse)
	err := c.cc.Invoke(ctx, InternalVendorOrderAPI_InternalVendorCreateOrderDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalVendorOrderAPIClient) InternalVendorGetPriceQuote(ctx context.Context, in *InternalVendorGetPriceQuoteRequest, opts ...grpc.CallOption) (*VendorGetPriceQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorGetPriceQuoteResponse)
	err := c.cc.Invoke(ctx, InternalVendorOrderAPI_InternalVendorGetPriceQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalVendorOrderAPIServer is the server API for InternalVendorOrderAPI service.
// All implementations should embed UnimplementedInternalVendorOrderAPIServer
// for forward compatibility.
type InternalVendorOrderAPIServer interface {
	InternalVendorListOrder(context.Context, *InternalVendorListOrderRequest) (*VendorListOrderResponse, error)
	InternalVendorListOrderDraft(context.Context, *InternalVendorListOrderDraftRequest) (*VendorListOrderDraftResponse, error)
	InternalVendorCreateOrderDraft(context.Context, *InternalVendorCreateOrderDraftRequest) (*InternalVendorCreateOrderDraftResponse, error)
	InternalVendorGetPriceQuote(context.Context, *InternalVendorGetPriceQuoteRequest) (*VendorGetPriceQuoteResponse, error)
}

// UnimplementedInternalVendorOrderAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalVendorOrderAPIServer struct{}

func (UnimplementedInternalVendorOrderAPIServer) InternalVendorListOrder(context.Context, *InternalVendorListOrderRequest) (*VendorListOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalVendorListOrder not implemented")
}
func (UnimplementedInternalVendorOrderAPIServer) InternalVendorListOrderDraft(context.Context, *InternalVendorListOrderDraftRequest) (*VendorListOrderDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalVendorListOrderDraft not implemented")
}
func (UnimplementedInternalVendorOrderAPIServer) InternalVendorCreateOrderDraft(context.Context, *InternalVendorCreateOrderDraftRequest) (*InternalVendorCreateOrderDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalVendorCreateOrderDraft not implemented")
}
func (UnimplementedInternalVendorOrderAPIServer) InternalVendorGetPriceQuote(context.Context, *InternalVendorGetPriceQuoteRequest) (*VendorGetPriceQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalVendorGetPriceQuote not implemented")
}
func (UnimplementedInternalVendorOrderAPIServer) testEmbeddedByValue() {}

// UnsafeInternalVendorOrderAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalVendorOrderAPIServer will
// result in compilation errors.
type UnsafeInternalVendorOrderAPIServer interface {
	mustEmbedUnimplementedInternalVendorOrderAPIServer()
}

func RegisterInternalVendorOrderAPIServer(s grpc.ServiceRegistrar, srv InternalVendorOrderAPIServer) {
	// If the following call pancis, it indicates UnimplementedInternalVendorOrderAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalVendorOrderAPI_ServiceDesc, srv)
}

func _InternalVendorOrderAPI_InternalVendorListOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalVendorListOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalVendorOrderAPIServer).InternalVendorListOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalVendorOrderAPI_InternalVendorListOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalVendorOrderAPIServer).InternalVendorListOrder(ctx, req.(*InternalVendorListOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalVendorOrderAPI_InternalVendorListOrderDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalVendorListOrderDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalVendorOrderAPIServer).InternalVendorListOrderDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalVendorOrderAPI_InternalVendorListOrderDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalVendorOrderAPIServer).InternalVendorListOrderDraft(ctx, req.(*InternalVendorListOrderDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalVendorOrderAPI_InternalVendorCreateOrderDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalVendorCreateOrderDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalVendorOrderAPIServer).InternalVendorCreateOrderDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalVendorOrderAPI_InternalVendorCreateOrderDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalVendorOrderAPIServer).InternalVendorCreateOrderDraft(ctx, req.(*InternalVendorCreateOrderDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalVendorOrderAPI_InternalVendorGetPriceQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalVendorGetPriceQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalVendorOrderAPIServer).InternalVendorGetPriceQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalVendorOrderAPI_InternalVendorGetPriceQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalVendorOrderAPIServer).InternalVendorGetPriceQuote(ctx, req.(*InternalVendorGetPriceQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalVendorOrderAPI_ServiceDesc is the grpc.ServiceDesc for InternalVendorOrderAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalVendorOrderAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.order.v1.InternalVendorOrderAPI",
	HandlerType: (*InternalVendorOrderAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalVendorListOrder",
			Handler:    _InternalVendorOrderAPI_InternalVendorListOrder_Handler,
		},
		{
			MethodName: "InternalVendorListOrderDraft",
			Handler:    _InternalVendorOrderAPI_InternalVendorListOrderDraft_Handler,
		},
		{
			MethodName: "InternalVendorCreateOrderDraft",
			Handler:    _InternalVendorOrderAPI_InternalVendorCreateOrderDraft_Handler,
		},
		{
			MethodName: "InternalVendorGetPriceQuote",
			Handler:    _InternalVendorOrderAPI_InternalVendorGetPriceQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/order/v1/internal_vendor_order.proto",
}
