// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/pod/v1/internal_setting.proto

package podv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SellerSettingInternalAPI_InternalGetSellerConfig_FullMethodName  = "/api.pod.v1.SellerSettingInternalAPI/InternalGetSellerConfig"
	SellerSettingInternalAPI_InternalGetReturnAddress_FullMethodName = "/api.pod.v1.SellerSettingInternalAPI/InternalGetReturnAddress"
	SellerSettingInternalAPI_InternalListSellerConfig_FullMethodName = "/api.pod.v1.SellerSettingInternalAPI/InternalListSellerConfig"
)

// SellerSettingInternalAPIClient is the client API for SellerSettingInternalAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellerSettingInternalAPIClient interface {
	InternalGetSellerConfig(ctx context.Context, in *InternalGetSellerConfigRequest, opts ...grpc.CallOption) (*InternalGetSellerConfigResponse, error)
	InternalGetReturnAddress(ctx context.Context, in *InternalGetReturnAddressRequest, opts ...grpc.CallOption) (*InternalGetReturnAddressResponse, error)
	InternalListSellerConfig(ctx context.Context, in *InternalListSellerConfigRequest, opts ...grpc.CallOption) (*InternalListSellerConfigResponse, error)
}

type sellerSettingInternalAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSellerSettingInternalAPIClient(cc grpc.ClientConnInterface) SellerSettingInternalAPIClient {
	return &sellerSettingInternalAPIClient{cc}
}

func (c *sellerSettingInternalAPIClient) InternalGetSellerConfig(ctx context.Context, in *InternalGetSellerConfigRequest, opts ...grpc.CallOption) (*InternalGetSellerConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalGetSellerConfigResponse)
	err := c.cc.Invoke(ctx, SellerSettingInternalAPI_InternalGetSellerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerSettingInternalAPIClient) InternalGetReturnAddress(ctx context.Context, in *InternalGetReturnAddressRequest, opts ...grpc.CallOption) (*InternalGetReturnAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalGetReturnAddressResponse)
	err := c.cc.Invoke(ctx, SellerSettingInternalAPI_InternalGetReturnAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerSettingInternalAPIClient) InternalListSellerConfig(ctx context.Context, in *InternalListSellerConfigRequest, opts ...grpc.CallOption) (*InternalListSellerConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalListSellerConfigResponse)
	err := c.cc.Invoke(ctx, SellerSettingInternalAPI_InternalListSellerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellerSettingInternalAPIServer is the server API for SellerSettingInternalAPI service.
// All implementations should embed UnimplementedSellerSettingInternalAPIServer
// for forward compatibility.
type SellerSettingInternalAPIServer interface {
	InternalGetSellerConfig(context.Context, *InternalGetSellerConfigRequest) (*InternalGetSellerConfigResponse, error)
	InternalGetReturnAddress(context.Context, *InternalGetReturnAddressRequest) (*InternalGetReturnAddressResponse, error)
	InternalListSellerConfig(context.Context, *InternalListSellerConfigRequest) (*InternalListSellerConfigResponse, error)
}

// UnimplementedSellerSettingInternalAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSellerSettingInternalAPIServer struct{}

func (UnimplementedSellerSettingInternalAPIServer) InternalGetSellerConfig(context.Context, *InternalGetSellerConfigRequest) (*InternalGetSellerConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalGetSellerConfig not implemented")
}
func (UnimplementedSellerSettingInternalAPIServer) InternalGetReturnAddress(context.Context, *InternalGetReturnAddressRequest) (*InternalGetReturnAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalGetReturnAddress not implemented")
}
func (UnimplementedSellerSettingInternalAPIServer) InternalListSellerConfig(context.Context, *InternalListSellerConfigRequest) (*InternalListSellerConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalListSellerConfig not implemented")
}
func (UnimplementedSellerSettingInternalAPIServer) testEmbeddedByValue() {}

// UnsafeSellerSettingInternalAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellerSettingInternalAPIServer will
// result in compilation errors.
type UnsafeSellerSettingInternalAPIServer interface {
	mustEmbedUnimplementedSellerSettingInternalAPIServer()
}

func RegisterSellerSettingInternalAPIServer(s grpc.ServiceRegistrar, srv SellerSettingInternalAPIServer) {
	// If the following call pancis, it indicates UnimplementedSellerSettingInternalAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SellerSettingInternalAPI_ServiceDesc, srv)
}

func _SellerSettingInternalAPI_InternalGetSellerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalGetSellerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerSettingInternalAPIServer).InternalGetSellerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerSettingInternalAPI_InternalGetSellerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerSettingInternalAPIServer).InternalGetSellerConfig(ctx, req.(*InternalGetSellerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerSettingInternalAPI_InternalGetReturnAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalGetReturnAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerSettingInternalAPIServer).InternalGetReturnAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerSettingInternalAPI_InternalGetReturnAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerSettingInternalAPIServer).InternalGetReturnAddress(ctx, req.(*InternalGetReturnAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerSettingInternalAPI_InternalListSellerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalListSellerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerSettingInternalAPIServer).InternalListSellerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerSettingInternalAPI_InternalListSellerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerSettingInternalAPIServer).InternalListSellerConfig(ctx, req.(*InternalListSellerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SellerSettingInternalAPI_ServiceDesc is the grpc.ServiceDesc for SellerSettingInternalAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SellerSettingInternalAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.pod.v1.SellerSettingInternalAPI",
	HandlerType: (*SellerSettingInternalAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalGetSellerConfig",
			Handler:    _SellerSettingInternalAPI_InternalGetSellerConfig_Handler,
		},
		{
			MethodName: "InternalGetReturnAddress",
			Handler:    _SellerSettingInternalAPI_InternalGetReturnAddress_Handler,
		},
		{
			MethodName: "InternalListSellerConfig",
			Handler:    _SellerSettingInternalAPI_InternalListSellerConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pod/v1/internal_setting.proto",
}
