// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/pod/v1/order_import_admin.proto

package podv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderImportAdminAPI_StaffListOrderImportSession_FullMethodName             = "/api.pod.v1.OrderImportAdminAPI/StaffListOrderImportSession"
	OrderImportAdminAPI_StaffCountOrderImportSessionOrderStatus_FullMethodName = "/api.pod.v1.OrderImportAdminAPI/StaffCountOrderImportSessionOrderStatus"
	OrderImportAdminAPI_StaffListOrderImport_FullMethodName                    = "/api.pod.v1.OrderImportAdminAPI/StaffListOrderImport"
)

// OrderImportAdminAPIClient is the client API for OrderImportAdminAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderImportAdminAPIClient interface {
	StaffListOrderImportSession(ctx context.Context, in *StaffListOrderImportSessionRequest, opts ...grpc.CallOption) (*StaffListOrderImportSessionResponse, error)
	StaffCountOrderImportSessionOrderStatus(ctx context.Context, in *StaffCountOrderImportSessionOrderStatusRequest, opts ...grpc.CallOption) (*StaffCountOrderImportSessionOrderStatusResponse, error)
	StaffListOrderImport(ctx context.Context, in *StaffListOrderImportRequest, opts ...grpc.CallOption) (*StaffListOrderImportResponse, error)
}

type orderImportAdminAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderImportAdminAPIClient(cc grpc.ClientConnInterface) OrderImportAdminAPIClient {
	return &orderImportAdminAPIClient{cc}
}

func (c *orderImportAdminAPIClient) StaffListOrderImportSession(ctx context.Context, in *StaffListOrderImportSessionRequest, opts ...grpc.CallOption) (*StaffListOrderImportSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListOrderImportSessionResponse)
	err := c.cc.Invoke(ctx, OrderImportAdminAPI_StaffListOrderImportSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderImportAdminAPIClient) StaffCountOrderImportSessionOrderStatus(ctx context.Context, in *StaffCountOrderImportSessionOrderStatusRequest, opts ...grpc.CallOption) (*StaffCountOrderImportSessionOrderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffCountOrderImportSessionOrderStatusResponse)
	err := c.cc.Invoke(ctx, OrderImportAdminAPI_StaffCountOrderImportSessionOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderImportAdminAPIClient) StaffListOrderImport(ctx context.Context, in *StaffListOrderImportRequest, opts ...grpc.CallOption) (*StaffListOrderImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListOrderImportResponse)
	err := c.cc.Invoke(ctx, OrderImportAdminAPI_StaffListOrderImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderImportAdminAPIServer is the server API for OrderImportAdminAPI service.
// All implementations should embed UnimplementedOrderImportAdminAPIServer
// for forward compatibility.
type OrderImportAdminAPIServer interface {
	StaffListOrderImportSession(context.Context, *StaffListOrderImportSessionRequest) (*StaffListOrderImportSessionResponse, error)
	StaffCountOrderImportSessionOrderStatus(context.Context, *StaffCountOrderImportSessionOrderStatusRequest) (*StaffCountOrderImportSessionOrderStatusResponse, error)
	StaffListOrderImport(context.Context, *StaffListOrderImportRequest) (*StaffListOrderImportResponse, error)
}

// UnimplementedOrderImportAdminAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderImportAdminAPIServer struct{}

func (UnimplementedOrderImportAdminAPIServer) StaffListOrderImportSession(context.Context, *StaffListOrderImportSessionRequest) (*StaffListOrderImportSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListOrderImportSession not implemented")
}
func (UnimplementedOrderImportAdminAPIServer) StaffCountOrderImportSessionOrderStatus(context.Context, *StaffCountOrderImportSessionOrderStatusRequest) (*StaffCountOrderImportSessionOrderStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffCountOrderImportSessionOrderStatus not implemented")
}
func (UnimplementedOrderImportAdminAPIServer) StaffListOrderImport(context.Context, *StaffListOrderImportRequest) (*StaffListOrderImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListOrderImport not implemented")
}
func (UnimplementedOrderImportAdminAPIServer) testEmbeddedByValue() {}

// UnsafeOrderImportAdminAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderImportAdminAPIServer will
// result in compilation errors.
type UnsafeOrderImportAdminAPIServer interface {
	mustEmbedUnimplementedOrderImportAdminAPIServer()
}

func RegisterOrderImportAdminAPIServer(s grpc.ServiceRegistrar, srv OrderImportAdminAPIServer) {
	// If the following call pancis, it indicates UnimplementedOrderImportAdminAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderImportAdminAPI_ServiceDesc, srv)
}

func _OrderImportAdminAPI_StaffListOrderImportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListOrderImportSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderImportAdminAPIServer).StaffListOrderImportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderImportAdminAPI_StaffListOrderImportSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderImportAdminAPIServer).StaffListOrderImportSession(ctx, req.(*StaffListOrderImportSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderImportAdminAPI_StaffCountOrderImportSessionOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffCountOrderImportSessionOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderImportAdminAPIServer).StaffCountOrderImportSessionOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderImportAdminAPI_StaffCountOrderImportSessionOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderImportAdminAPIServer).StaffCountOrderImportSessionOrderStatus(ctx, req.(*StaffCountOrderImportSessionOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderImportAdminAPI_StaffListOrderImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListOrderImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderImportAdminAPIServer).StaffListOrderImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderImportAdminAPI_StaffListOrderImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderImportAdminAPIServer).StaffListOrderImport(ctx, req.(*StaffListOrderImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderImportAdminAPI_ServiceDesc is the grpc.ServiceDesc for OrderImportAdminAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderImportAdminAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.pod.v1.OrderImportAdminAPI",
	HandlerType: (*OrderImportAdminAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StaffListOrderImportSession",
			Handler:    _OrderImportAdminAPI_StaffListOrderImportSession_Handler,
		},
		{
			MethodName: "StaffCountOrderImportSessionOrderStatus",
			Handler:    _OrderImportAdminAPI_StaffCountOrderImportSessionOrderStatus_Handler,
		},
		{
			MethodName: "StaffListOrderImport",
			Handler:    _OrderImportAdminAPI_StaffListOrderImport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pod/v1/order_import_admin.proto",
}
