// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/pod/v1/seller_shipping_label.proto

package podv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SellerShippingLabelAPI_ListEnabledCarrierServices_FullMethodName = "/api.pod.v1.SellerShippingLabelAPI/ListEnabledCarrierServices"
	SellerShippingLabelAPI_EstimateLabelRates_FullMethodName         = "/api.pod.v1.SellerShippingLabelAPI/EstimateLabelRates"
	SellerShippingLabelAPI_PurchaseLabel_FullMethodName              = "/api.pod.v1.SellerShippingLabelAPI/PurchaseLabel"
	SellerShippingLabelAPI_GetLabel_FullMethodName                   = "/api.pod.v1.SellerShippingLabelAPI/GetLabel"
	SellerShippingLabelAPI_ListLabels_FullMethodName                 = "/api.pod.v1.SellerShippingLabelAPI/ListLabels"
	SellerShippingLabelAPI_CancelLabel_FullMethodName                = "/api.pod.v1.SellerShippingLabelAPI/CancelLabel"
	SellerShippingLabelAPI_ListLabelInvoices_FullMethodName          = "/api.pod.v1.SellerShippingLabelAPI/ListLabelInvoices"
	SellerShippingLabelAPI_GetLabelInvoice_FullMethodName            = "/api.pod.v1.SellerShippingLabelAPI/GetLabelInvoice"
	SellerShippingLabelAPI_ListSavedAddresses_FullMethodName         = "/api.pod.v1.SellerShippingLabelAPI/ListSavedAddresses"
	SellerShippingLabelAPI_UpsertSavedAddress_FullMethodName         = "/api.pod.v1.SellerShippingLabelAPI/UpsertSavedAddress"
	SellerShippingLabelAPI_DeleteSavedAddress_FullMethodName         = "/api.pod.v1.SellerShippingLabelAPI/DeleteSavedAddress"
)

// SellerShippingLabelAPIClient is the client API for SellerShippingLabelAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellerShippingLabelAPIClient interface {
	ListEnabledCarrierServices(ctx context.Context, in *ListEnabledCarrierServicesRequest, opts ...grpc.CallOption) (*ListEnabledCarrierServicesResponse, error)
	EstimateLabelRates(ctx context.Context, in *EstimateLabelRatesRequest, opts ...grpc.CallOption) (*EstimateLabelRatesResponse, error)
	PurchaseLabel(ctx context.Context, in *PurchaseLabelRequest, opts ...grpc.CallOption) (*PurchaseLabelResponse, error)
	GetLabel(ctx context.Context, in *GetLabelRequest, opts ...grpc.CallOption) (*GetLabelResponse, error)
	ListLabels(ctx context.Context, in *ListLabelsRequest, opts ...grpc.CallOption) (*ListLabelsResponse, error)
	CancelLabel(ctx context.Context, in *CancelLabelRequest, opts ...grpc.CallOption) (*CancelLabelResponse, error)
	ListLabelInvoices(ctx context.Context, in *ListLabelInvoicesRequest, opts ...grpc.CallOption) (*ListLabelInvoicesResponse, error)
	GetLabelInvoice(ctx context.Context, in *GetLabelInvoiceRequest, opts ...grpc.CallOption) (*GetLabelInvoiceResponse, error)
	ListSavedAddresses(ctx context.Context, in *ListSavedAddressesRequest, opts ...grpc.CallOption) (*ListSavedAddressesResponse, error)
	UpsertSavedAddress(ctx context.Context, in *UpsertSavedAddressRequest, opts ...grpc.CallOption) (*UpsertSavedAddressResponse, error)
	DeleteSavedAddress(ctx context.Context, in *DeleteSavedAddressRequest, opts ...grpc.CallOption) (*DeleteSavedAddressResponse, error)
}

type sellerShippingLabelAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSellerShippingLabelAPIClient(cc grpc.ClientConnInterface) SellerShippingLabelAPIClient {
	return &sellerShippingLabelAPIClient{cc}
}

func (c *sellerShippingLabelAPIClient) ListEnabledCarrierServices(ctx context.Context, in *ListEnabledCarrierServicesRequest, opts ...grpc.CallOption) (*ListEnabledCarrierServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnabledCarrierServicesResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_ListEnabledCarrierServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerShippingLabelAPIClient) EstimateLabelRates(ctx context.Context, in *EstimateLabelRatesRequest, opts ...grpc.CallOption) (*EstimateLabelRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateLabelRatesResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_EstimateLabelRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerShippingLabelAPIClient) PurchaseLabel(ctx context.Context, in *PurchaseLabelRequest, opts ...grpc.CallOption) (*PurchaseLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseLabelResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_PurchaseLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerShippingLabelAPIClient) GetLabel(ctx context.Context, in *GetLabelRequest, opts ...grpc.CallOption) (*GetLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLabelResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_GetLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerShippingLabelAPIClient) ListLabels(ctx context.Context, in *ListLabelsRequest, opts ...grpc.CallOption) (*ListLabelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLabelsResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_ListLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerShippingLabelAPIClient) CancelLabel(ctx context.Context, in *CancelLabelRequest, opts ...grpc.CallOption) (*CancelLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelLabelResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_CancelLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerShippingLabelAPIClient) ListLabelInvoices(ctx context.Context, in *ListLabelInvoicesRequest, opts ...grpc.CallOption) (*ListLabelInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLabelInvoicesResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_ListLabelInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerShippingLabelAPIClient) GetLabelInvoice(ctx context.Context, in *GetLabelInvoiceRequest, opts ...grpc.CallOption) (*GetLabelInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLabelInvoiceResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_GetLabelInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerShippingLabelAPIClient) ListSavedAddresses(ctx context.Context, in *ListSavedAddressesRequest, opts ...grpc.CallOption) (*ListSavedAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSavedAddressesResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_ListSavedAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerShippingLabelAPIClient) UpsertSavedAddress(ctx context.Context, in *UpsertSavedAddressRequest, opts ...grpc.CallOption) (*UpsertSavedAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertSavedAddressResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_UpsertSavedAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerShippingLabelAPIClient) DeleteSavedAddress(ctx context.Context, in *DeleteSavedAddressRequest, opts ...grpc.CallOption) (*DeleteSavedAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSavedAddressResponse)
	err := c.cc.Invoke(ctx, SellerShippingLabelAPI_DeleteSavedAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellerShippingLabelAPIServer is the server API for SellerShippingLabelAPI service.
// All implementations should embed UnimplementedSellerShippingLabelAPIServer
// for forward compatibility.
type SellerShippingLabelAPIServer interface {
	ListEnabledCarrierServices(context.Context, *ListEnabledCarrierServicesRequest) (*ListEnabledCarrierServicesResponse, error)
	EstimateLabelRates(context.Context, *EstimateLabelRatesRequest) (*EstimateLabelRatesResponse, error)
	PurchaseLabel(context.Context, *PurchaseLabelRequest) (*PurchaseLabelResponse, error)
	GetLabel(context.Context, *GetLabelRequest) (*GetLabelResponse, error)
	ListLabels(context.Context, *ListLabelsRequest) (*ListLabelsResponse, error)
	CancelLabel(context.Context, *CancelLabelRequest) (*CancelLabelResponse, error)
	ListLabelInvoices(context.Context, *ListLabelInvoicesRequest) (*ListLabelInvoicesResponse, error)
	GetLabelInvoice(context.Context, *GetLabelInvoiceRequest) (*GetLabelInvoiceResponse, error)
	ListSavedAddresses(context.Context, *ListSavedAddressesRequest) (*ListSavedAddressesResponse, error)
	UpsertSavedAddress(context.Context, *UpsertSavedAddressRequest) (*UpsertSavedAddressResponse, error)
	DeleteSavedAddress(context.Context, *DeleteSavedAddressRequest) (*DeleteSavedAddressResponse, error)
}

// UnimplementedSellerShippingLabelAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSellerShippingLabelAPIServer struct{}

func (UnimplementedSellerShippingLabelAPIServer) ListEnabledCarrierServices(context.Context, *ListEnabledCarrierServicesRequest) (*ListEnabledCarrierServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnabledCarrierServices not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) EstimateLabelRates(context.Context, *EstimateLabelRatesRequest) (*EstimateLabelRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateLabelRates not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) PurchaseLabel(context.Context, *PurchaseLabelRequest) (*PurchaseLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseLabel not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) GetLabel(context.Context, *GetLabelRequest) (*GetLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLabel not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) ListLabels(context.Context, *ListLabelsRequest) (*ListLabelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLabels not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) CancelLabel(context.Context, *CancelLabelRequest) (*CancelLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelLabel not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) ListLabelInvoices(context.Context, *ListLabelInvoicesRequest) (*ListLabelInvoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLabelInvoices not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) GetLabelInvoice(context.Context, *GetLabelInvoiceRequest) (*GetLabelInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLabelInvoice not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) ListSavedAddresses(context.Context, *ListSavedAddressesRequest) (*ListSavedAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSavedAddresses not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) UpsertSavedAddress(context.Context, *UpsertSavedAddressRequest) (*UpsertSavedAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertSavedAddress not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) DeleteSavedAddress(context.Context, *DeleteSavedAddressRequest) (*DeleteSavedAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSavedAddress not implemented")
}
func (UnimplementedSellerShippingLabelAPIServer) testEmbeddedByValue() {}

// UnsafeSellerShippingLabelAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellerShippingLabelAPIServer will
// result in compilation errors.
type UnsafeSellerShippingLabelAPIServer interface {
	mustEmbedUnimplementedSellerShippingLabelAPIServer()
}

func RegisterSellerShippingLabelAPIServer(s grpc.ServiceRegistrar, srv SellerShippingLabelAPIServer) {
	// If the following call pancis, it indicates UnimplementedSellerShippingLabelAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SellerShippingLabelAPI_ServiceDesc, srv)
}

func _SellerShippingLabelAPI_ListEnabledCarrierServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnabledCarrierServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).ListEnabledCarrierServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_ListEnabledCarrierServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).ListEnabledCarrierServices(ctx, req.(*ListEnabledCarrierServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerShippingLabelAPI_EstimateLabelRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateLabelRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).EstimateLabelRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_EstimateLabelRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).EstimateLabelRates(ctx, req.(*EstimateLabelRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerShippingLabelAPI_PurchaseLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).PurchaseLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_PurchaseLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).PurchaseLabel(ctx, req.(*PurchaseLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerShippingLabelAPI_GetLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).GetLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_GetLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).GetLabel(ctx, req.(*GetLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerShippingLabelAPI_ListLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).ListLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_ListLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).ListLabels(ctx, req.(*ListLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerShippingLabelAPI_CancelLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).CancelLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_CancelLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).CancelLabel(ctx, req.(*CancelLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerShippingLabelAPI_ListLabelInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLabelInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).ListLabelInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_ListLabelInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).ListLabelInvoices(ctx, req.(*ListLabelInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerShippingLabelAPI_GetLabelInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLabelInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).GetLabelInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_GetLabelInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).GetLabelInvoice(ctx, req.(*GetLabelInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerShippingLabelAPI_ListSavedAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSavedAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).ListSavedAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_ListSavedAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).ListSavedAddresses(ctx, req.(*ListSavedAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerShippingLabelAPI_UpsertSavedAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertSavedAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).UpsertSavedAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_UpsertSavedAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).UpsertSavedAddress(ctx, req.(*UpsertSavedAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerShippingLabelAPI_DeleteSavedAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSavedAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerShippingLabelAPIServer).DeleteSavedAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerShippingLabelAPI_DeleteSavedAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerShippingLabelAPIServer).DeleteSavedAddress(ctx, req.(*DeleteSavedAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SellerShippingLabelAPI_ServiceDesc is the grpc.ServiceDesc for SellerShippingLabelAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SellerShippingLabelAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.pod.v1.SellerShippingLabelAPI",
	HandlerType: (*SellerShippingLabelAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEnabledCarrierServices",
			Handler:    _SellerShippingLabelAPI_ListEnabledCarrierServices_Handler,
		},
		{
			MethodName: "EstimateLabelRates",
			Handler:    _SellerShippingLabelAPI_EstimateLabelRates_Handler,
		},
		{
			MethodName: "PurchaseLabel",
			Handler:    _SellerShippingLabelAPI_PurchaseLabel_Handler,
		},
		{
			MethodName: "GetLabel",
			Handler:    _SellerShippingLabelAPI_GetLabel_Handler,
		},
		{
			MethodName: "ListLabels",
			Handler:    _SellerShippingLabelAPI_ListLabels_Handler,
		},
		{
			MethodName: "CancelLabel",
			Handler:    _SellerShippingLabelAPI_CancelLabel_Handler,
		},
		{
			MethodName: "ListLabelInvoices",
			Handler:    _SellerShippingLabelAPI_ListLabelInvoices_Handler,
		},
		{
			MethodName: "GetLabelInvoice",
			Handler:    _SellerShippingLabelAPI_GetLabelInvoice_Handler,
		},
		{
			MethodName: "ListSavedAddresses",
			Handler:    _SellerShippingLabelAPI_ListSavedAddresses_Handler,
		},
		{
			MethodName: "UpsertSavedAddress",
			Handler:    _SellerShippingLabelAPI_UpsertSavedAddress_Handler,
		},
		{
			MethodName: "DeleteSavedAddress",
			Handler:    _SellerShippingLabelAPI_DeleteSavedAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pod/v1/seller_shipping_label.proto",
}

const (
	ShippingLabelAdminAPI_StaffGetTeamLabelConfig_FullMethodName    = "/api.pod.v1.ShippingLabelAdminAPI/StaffGetTeamLabelConfig"
	ShippingLabelAdminAPI_StaffUpdateTeamLabelConfig_FullMethodName = "/api.pod.v1.ShippingLabelAdminAPI/StaffUpdateTeamLabelConfig"
	ShippingLabelAdminAPI_StaffListSellerLabels_FullMethodName      = "/api.pod.v1.ShippingLabelAdminAPI/StaffListSellerLabels"
	ShippingLabelAdminAPI_StaffGetSellerLabel_FullMethodName        = "/api.pod.v1.ShippingLabelAdminAPI/StaffGetSellerLabel"
	ShippingLabelAdminAPI_StaffCancelSellerLabel_FullMethodName     = "/api.pod.v1.ShippingLabelAdminAPI/StaffCancelSellerLabel"
	ShippingLabelAdminAPI_StaffListLabelAccruals_FullMethodName     = "/api.pod.v1.ShippingLabelAdminAPI/StaffListLabelAccruals"
	ShippingLabelAdminAPI_StaffListLabelInvoices_FullMethodName     = "/api.pod.v1.ShippingLabelAdminAPI/StaffListLabelInvoices"
	ShippingLabelAdminAPI_StaffFinalizeLabelInvoice_FullMethodName  = "/api.pod.v1.ShippingLabelAdminAPI/StaffFinalizeLabelInvoice"
	ShippingLabelAdminAPI_StaffSettleLabelInvoice_FullMethodName    = "/api.pod.v1.ShippingLabelAdminAPI/StaffSettleLabelInvoice"
	ShippingLabelAdminAPI_StaffListLabelEvents_FullMethodName       = "/api.pod.v1.ShippingLabelAdminAPI/StaffListLabelEvents"
)

// ShippingLabelAdminAPIClient is the client API for ShippingLabelAdminAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShippingLabelAdminAPIClient interface {
	StaffGetTeamLabelConfig(ctx context.Context, in *StaffGetTeamLabelConfigRequest, opts ...grpc.CallOption) (*StaffGetTeamLabelConfigResponse, error)
	StaffUpdateTeamLabelConfig(ctx context.Context, in *StaffUpdateTeamLabelConfigRequest, opts ...grpc.CallOption) (*StaffUpdateTeamLabelConfigResponse, error)
	StaffListSellerLabels(ctx context.Context, in *StaffListSellerLabelsRequest, opts ...grpc.CallOption) (*StaffListSellerLabelsResponse, error)
	StaffGetSellerLabel(ctx context.Context, in *StaffGetSellerLabelRequest, opts ...grpc.CallOption) (*StaffGetSellerLabelResponse, error)
	StaffCancelSellerLabel(ctx context.Context, in *StaffCancelSellerLabelRequest, opts ...grpc.CallOption) (*StaffCancelSellerLabelResponse, error)
	StaffListLabelAccruals(ctx context.Context, in *StaffListLabelAccrualsRequest, opts ...grpc.CallOption) (*StaffListLabelAccrualsResponse, error)
	StaffListLabelInvoices(ctx context.Context, in *StaffListLabelInvoicesRequest, opts ...grpc.CallOption) (*StaffListLabelInvoicesResponse, error)
	StaffFinalizeLabelInvoice(ctx context.Context, in *StaffFinalizeLabelInvoiceRequest, opts ...grpc.CallOption) (*StaffFinalizeLabelInvoiceResponse, error)
	StaffSettleLabelInvoice(ctx context.Context, in *StaffSettleLabelInvoiceRequest, opts ...grpc.CallOption) (*StaffSettleLabelInvoiceResponse, error)
	StaffListLabelEvents(ctx context.Context, in *StaffListLabelEventsRequest, opts ...grpc.CallOption) (*StaffListLabelEventsResponse, error)
}

type shippingLabelAdminAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingLabelAdminAPIClient(cc grpc.ClientConnInterface) ShippingLabelAdminAPIClient {
	return &shippingLabelAdminAPIClient{cc}
}

func (c *shippingLabelAdminAPIClient) StaffGetTeamLabelConfig(ctx context.Context, in *StaffGetTeamLabelConfigRequest, opts ...grpc.CallOption) (*StaffGetTeamLabelConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffGetTeamLabelConfigResponse)
	err := c.cc.Invoke(ctx, ShippingLabelAdminAPI_StaffGetTeamLabelConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingLabelAdminAPIClient) StaffUpdateTeamLabelConfig(ctx context.Context, in *StaffUpdateTeamLabelConfigRequest, opts ...grpc.CallOption) (*StaffUpdateTeamLabelConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffUpdateTeamLabelConfigResponse)
	err := c.cc.Invoke(ctx, ShippingLabelAdminAPI_StaffUpdateTeamLabelConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingLabelAdminAPIClient) StaffListSellerLabels(ctx context.Context, in *StaffListSellerLabelsRequest, opts ...grpc.CallOption) (*StaffListSellerLabelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListSellerLabelsResponse)
	err := c.cc.Invoke(ctx, ShippingLabelAdminAPI_StaffListSellerLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingLabelAdminAPIClient) StaffGetSellerLabel(ctx context.Context, in *StaffGetSellerLabelRequest, opts ...grpc.CallOption) (*StaffGetSellerLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffGetSellerLabelResponse)
	err := c.cc.Invoke(ctx, ShippingLabelAdminAPI_StaffGetSellerLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingLabelAdminAPIClient) StaffCancelSellerLabel(ctx context.Context, in *StaffCancelSellerLabelRequest, opts ...grpc.CallOption) (*StaffCancelSellerLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffCancelSellerLabelResponse)
	err := c.cc.Invoke(ctx, ShippingLabelAdminAPI_StaffCancelSellerLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingLabelAdminAPIClient) StaffListLabelAccruals(ctx context.Context, in *StaffListLabelAccrualsRequest, opts ...grpc.CallOption) (*StaffListLabelAccrualsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListLabelAccrualsResponse)
	err := c.cc.Invoke(ctx, ShippingLabelAdminAPI_StaffListLabelAccruals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingLabelAdminAPIClient) StaffListLabelInvoices(ctx context.Context, in *StaffListLabelInvoicesRequest, opts ...grpc.CallOption) (*StaffListLabelInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListLabelInvoicesResponse)
	err := c.cc.Invoke(ctx, ShippingLabelAdminAPI_StaffListLabelInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingLabelAdminAPIClient) StaffFinalizeLabelInvoice(ctx context.Context, in *StaffFinalizeLabelInvoiceRequest, opts ...grpc.CallOption) (*StaffFinalizeLabelInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffFinalizeLabelInvoiceResponse)
	err := c.cc.Invoke(ctx, ShippingLabelAdminAPI_StaffFinalizeLabelInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingLabelAdminAPIClient) StaffSettleLabelInvoice(ctx context.Context, in *StaffSettleLabelInvoiceRequest, opts ...grpc.CallOption) (*StaffSettleLabelInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffSettleLabelInvoiceResponse)
	err := c.cc.Invoke(ctx, ShippingLabelAdminAPI_StaffSettleLabelInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingLabelAdminAPIClient) StaffListLabelEvents(ctx context.Context, in *StaffListLabelEventsRequest, opts ...grpc.CallOption) (*StaffListLabelEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListLabelEventsResponse)
	err := c.cc.Invoke(ctx, ShippingLabelAdminAPI_StaffListLabelEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingLabelAdminAPIServer is the server API for ShippingLabelAdminAPI service.
// All implementations should embed UnimplementedShippingLabelAdminAPIServer
// for forward compatibility.
type ShippingLabelAdminAPIServer interface {
	StaffGetTeamLabelConfig(context.Context, *StaffGetTeamLabelConfigRequest) (*StaffGetTeamLabelConfigResponse, error)
	StaffUpdateTeamLabelConfig(context.Context, *StaffUpdateTeamLabelConfigRequest) (*StaffUpdateTeamLabelConfigResponse, error)
	StaffListSellerLabels(context.Context, *StaffListSellerLabelsRequest) (*StaffListSellerLabelsResponse, error)
	StaffGetSellerLabel(context.Context, *StaffGetSellerLabelRequest) (*StaffGetSellerLabelResponse, error)
	StaffCancelSellerLabel(context.Context, *StaffCancelSellerLabelRequest) (*StaffCancelSellerLabelResponse, error)
	StaffListLabelAccruals(context.Context, *StaffListLabelAccrualsRequest) (*StaffListLabelAccrualsResponse, error)
	StaffListLabelInvoices(context.Context, *StaffListLabelInvoicesRequest) (*StaffListLabelInvoicesResponse, error)
	StaffFinalizeLabelInvoice(context.Context, *StaffFinalizeLabelInvoiceRequest) (*StaffFinalizeLabelInvoiceResponse, error)
	StaffSettleLabelInvoice(context.Context, *StaffSettleLabelInvoiceRequest) (*StaffSettleLabelInvoiceResponse, error)
	StaffListLabelEvents(context.Context, *StaffListLabelEventsRequest) (*StaffListLabelEventsResponse, error)
}

// UnimplementedShippingLabelAdminAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShippingLabelAdminAPIServer struct{}

func (UnimplementedShippingLabelAdminAPIServer) StaffGetTeamLabelConfig(context.Context, *StaffGetTeamLabelConfigRequest) (*StaffGetTeamLabelConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffGetTeamLabelConfig not implemented")
}
func (UnimplementedShippingLabelAdminAPIServer) StaffUpdateTeamLabelConfig(context.Context, *StaffUpdateTeamLabelConfigRequest) (*StaffUpdateTeamLabelConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffUpdateTeamLabelConfig not implemented")
}
func (UnimplementedShippingLabelAdminAPIServer) StaffListSellerLabels(context.Context, *StaffListSellerLabelsRequest) (*StaffListSellerLabelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListSellerLabels not implemented")
}
func (UnimplementedShippingLabelAdminAPIServer) StaffGetSellerLabel(context.Context, *StaffGetSellerLabelRequest) (*StaffGetSellerLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffGetSellerLabel not implemented")
}
func (UnimplementedShippingLabelAdminAPIServer) StaffCancelSellerLabel(context.Context, *StaffCancelSellerLabelRequest) (*StaffCancelSellerLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffCancelSellerLabel not implemented")
}
func (UnimplementedShippingLabelAdminAPIServer) StaffListLabelAccruals(context.Context, *StaffListLabelAccrualsRequest) (*StaffListLabelAccrualsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListLabelAccruals not implemented")
}
func (UnimplementedShippingLabelAdminAPIServer) StaffListLabelInvoices(context.Context, *StaffListLabelInvoicesRequest) (*StaffListLabelInvoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListLabelInvoices not implemented")
}
func (UnimplementedShippingLabelAdminAPIServer) StaffFinalizeLabelInvoice(context.Context, *StaffFinalizeLabelInvoiceRequest) (*StaffFinalizeLabelInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffFinalizeLabelInvoice not implemented")
}
func (UnimplementedShippingLabelAdminAPIServer) StaffSettleLabelInvoice(context.Context, *StaffSettleLabelInvoiceRequest) (*StaffSettleLabelInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffSettleLabelInvoice not implemented")
}
func (UnimplementedShippingLabelAdminAPIServer) StaffListLabelEvents(context.Context, *StaffListLabelEventsRequest) (*StaffListLabelEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListLabelEvents not implemented")
}
func (UnimplementedShippingLabelAdminAPIServer) testEmbeddedByValue() {}

// UnsafeShippingLabelAdminAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShippingLabelAdminAPIServer will
// result in compilation errors.
type UnsafeShippingLabelAdminAPIServer interface {
	mustEmbedUnimplementedShippingLabelAdminAPIServer()
}

func RegisterShippingLabelAdminAPIServer(s grpc.ServiceRegistrar, srv ShippingLabelAdminAPIServer) {
	// If the following call pancis, it indicates UnimplementedShippingLabelAdminAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShippingLabelAdminAPI_ServiceDesc, srv)
}

func _ShippingLabelAdminAPI_StaffGetTeamLabelConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffGetTeamLabelConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingLabelAdminAPIServer).StaffGetTeamLabelConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingLabelAdminAPI_StaffGetTeamLabelConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingLabelAdminAPIServer).StaffGetTeamLabelConfig(ctx, req.(*StaffGetTeamLabelConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingLabelAdminAPI_StaffUpdateTeamLabelConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffUpdateTeamLabelConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingLabelAdminAPIServer).StaffUpdateTeamLabelConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingLabelAdminAPI_StaffUpdateTeamLabelConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingLabelAdminAPIServer).StaffUpdateTeamLabelConfig(ctx, req.(*StaffUpdateTeamLabelConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingLabelAdminAPI_StaffListSellerLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListSellerLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingLabelAdminAPIServer).StaffListSellerLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingLabelAdminAPI_StaffListSellerLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingLabelAdminAPIServer).StaffListSellerLabels(ctx, req.(*StaffListSellerLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingLabelAdminAPI_StaffGetSellerLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffGetSellerLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingLabelAdminAPIServer).StaffGetSellerLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingLabelAdminAPI_StaffGetSellerLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingLabelAdminAPIServer).StaffGetSellerLabel(ctx, req.(*StaffGetSellerLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingLabelAdminAPI_StaffCancelSellerLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffCancelSellerLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingLabelAdminAPIServer).StaffCancelSellerLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingLabelAdminAPI_StaffCancelSellerLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingLabelAdminAPIServer).StaffCancelSellerLabel(ctx, req.(*StaffCancelSellerLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingLabelAdminAPI_StaffListLabelAccruals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListLabelAccrualsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingLabelAdminAPIServer).StaffListLabelAccruals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingLabelAdminAPI_StaffListLabelAccruals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingLabelAdminAPIServer).StaffListLabelAccruals(ctx, req.(*StaffListLabelAccrualsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingLabelAdminAPI_StaffListLabelInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListLabelInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingLabelAdminAPIServer).StaffListLabelInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingLabelAdminAPI_StaffListLabelInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingLabelAdminAPIServer).StaffListLabelInvoices(ctx, req.(*StaffListLabelInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingLabelAdminAPI_StaffFinalizeLabelInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffFinalizeLabelInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingLabelAdminAPIServer).StaffFinalizeLabelInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingLabelAdminAPI_StaffFinalizeLabelInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingLabelAdminAPIServer).StaffFinalizeLabelInvoice(ctx, req.(*StaffFinalizeLabelInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingLabelAdminAPI_StaffSettleLabelInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffSettleLabelInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingLabelAdminAPIServer).StaffSettleLabelInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingLabelAdminAPI_StaffSettleLabelInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingLabelAdminAPIServer).StaffSettleLabelInvoice(ctx, req.(*StaffSettleLabelInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingLabelAdminAPI_StaffListLabelEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListLabelEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingLabelAdminAPIServer).StaffListLabelEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingLabelAdminAPI_StaffListLabelEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingLabelAdminAPIServer).StaffListLabelEvents(ctx, req.(*StaffListLabelEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShippingLabelAdminAPI_ServiceDesc is the grpc.ServiceDesc for ShippingLabelAdminAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShippingLabelAdminAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.pod.v1.ShippingLabelAdminAPI",
	HandlerType: (*ShippingLabelAdminAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StaffGetTeamLabelConfig",
			Handler:    _ShippingLabelAdminAPI_StaffGetTeamLabelConfig_Handler,
		},
		{
			MethodName: "StaffUpdateTeamLabelConfig",
			Handler:    _ShippingLabelAdminAPI_StaffUpdateTeamLabelConfig_Handler,
		},
		{
			MethodName: "StaffListSellerLabels",
			Handler:    _ShippingLabelAdminAPI_StaffListSellerLabels_Handler,
		},
		{
			MethodName: "StaffGetSellerLabel",
			Handler:    _ShippingLabelAdminAPI_StaffGetSellerLabel_Handler,
		},
		{
			MethodName: "StaffCancelSellerLabel",
			Handler:    _ShippingLabelAdminAPI_StaffCancelSellerLabel_Handler,
		},
		{
			MethodName: "StaffListLabelAccruals",
			Handler:    _ShippingLabelAdminAPI_StaffListLabelAccruals_Handler,
		},
		{
			MethodName: "StaffListLabelInvoices",
			Handler:    _ShippingLabelAdminAPI_StaffListLabelInvoices_Handler,
		},
		{
			MethodName: "StaffFinalizeLabelInvoice",
			Handler:    _ShippingLabelAdminAPI_StaffFinalizeLabelInvoice_Handler,
		},
		{
			MethodName: "StaffSettleLabelInvoice",
			Handler:    _ShippingLabelAdminAPI_StaffSettleLabelInvoice_Handler,
		},
		{
			MethodName: "StaffListLabelEvents",
			Handler:    _ShippingLabelAdminAPI_StaffListLabelEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pod/v1/seller_shipping_label.proto",
}
