// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/pod/v1/seller_product_order.proto

package podv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SellerProductListingOrderCreatingAPI_UserListSellerProductSingleForCreateOrder_FullMethodName        = "/api.pod.v1.SellerProductListingOrderCreatingAPI/UserListSellerProductSingleForCreateOrder"
	SellerProductListingOrderCreatingAPI_UserListSellerProductGroupForCreateOrder_FullMethodName         = "/api.pod.v1.SellerProductListingOrderCreatingAPI/UserListSellerProductGroupForCreateOrder"
	SellerProductListingOrderCreatingAPI_UserListSellerProductSingleVariantForCreateOrder_FullMethodName = "/api.pod.v1.SellerProductListingOrderCreatingAPI/UserListSellerProductSingleVariantForCreateOrder"
)

// SellerProductListingOrderCreatingAPIClient is the client API for SellerProductListingOrderCreatingAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellerProductListingOrderCreatingAPIClient interface {
	UserListSellerProductSingleForCreateOrder(ctx context.Context, in *UserListSellerProductSingleForCreateOrderRequest, opts ...grpc.CallOption) (*UserListSellerProductSingleForCreateOrderResponse, error)
	UserListSellerProductGroupForCreateOrder(ctx context.Context, in *UserListSellerProductGroupForCreateOrderRequest, opts ...grpc.CallOption) (*UserListSellerProductGroupForCreateOrderResponse, error)
	UserListSellerProductSingleVariantForCreateOrder(ctx context.Context, in *UserListSellerProductSingleVariantForCreateOrderRequest, opts ...grpc.CallOption) (*UserListSellerProductSingleVariantForCreateOrderResponse, error)
}

type sellerProductListingOrderCreatingAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSellerProductListingOrderCreatingAPIClient(cc grpc.ClientConnInterface) SellerProductListingOrderCreatingAPIClient {
	return &sellerProductListingOrderCreatingAPIClient{cc}
}

func (c *sellerProductListingOrderCreatingAPIClient) UserListSellerProductSingleForCreateOrder(ctx context.Context, in *UserListSellerProductSingleForCreateOrderRequest, opts ...grpc.CallOption) (*UserListSellerProductSingleForCreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListSellerProductSingleForCreateOrderResponse)
	err := c.cc.Invoke(ctx, SellerProductListingOrderCreatingAPI_UserListSellerProductSingleForCreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerProductListingOrderCreatingAPIClient) UserListSellerProductGroupForCreateOrder(ctx context.Context, in *UserListSellerProductGroupForCreateOrderRequest, opts ...grpc.CallOption) (*UserListSellerProductGroupForCreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListSellerProductGroupForCreateOrderResponse)
	err := c.cc.Invoke(ctx, SellerProductListingOrderCreatingAPI_UserListSellerProductGroupForCreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerProductListingOrderCreatingAPIClient) UserListSellerProductSingleVariantForCreateOrder(ctx context.Context, in *UserListSellerProductSingleVariantForCreateOrderRequest, opts ...grpc.CallOption) (*UserListSellerProductSingleVariantForCreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListSellerProductSingleVariantForCreateOrderResponse)
	err := c.cc.Invoke(ctx, SellerProductListingOrderCreatingAPI_UserListSellerProductSingleVariantForCreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellerProductListingOrderCreatingAPIServer is the server API for SellerProductListingOrderCreatingAPI service.
// All implementations should embed UnimplementedSellerProductListingOrderCreatingAPIServer
// for forward compatibility.
type SellerProductListingOrderCreatingAPIServer interface {
	UserListSellerProductSingleForCreateOrder(context.Context, *UserListSellerProductSingleForCreateOrderRequest) (*UserListSellerProductSingleForCreateOrderResponse, error)
	UserListSellerProductGroupForCreateOrder(context.Context, *UserListSellerProductGroupForCreateOrderRequest) (*UserListSellerProductGroupForCreateOrderResponse, error)
	UserListSellerProductSingleVariantForCreateOrder(context.Context, *UserListSellerProductSingleVariantForCreateOrderRequest) (*UserListSellerProductSingleVariantForCreateOrderResponse, error)
}

// UnimplementedSellerProductListingOrderCreatingAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSellerProductListingOrderCreatingAPIServer struct{}

func (UnimplementedSellerProductListingOrderCreatingAPIServer) UserListSellerProductSingleForCreateOrder(context.Context, *UserListSellerProductSingleForCreateOrderRequest) (*UserListSellerProductSingleForCreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListSellerProductSingleForCreateOrder not implemented")
}
func (UnimplementedSellerProductListingOrderCreatingAPIServer) UserListSellerProductGroupForCreateOrder(context.Context, *UserListSellerProductGroupForCreateOrderRequest) (*UserListSellerProductGroupForCreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListSellerProductGroupForCreateOrder not implemented")
}
func (UnimplementedSellerProductListingOrderCreatingAPIServer) UserListSellerProductSingleVariantForCreateOrder(context.Context, *UserListSellerProductSingleVariantForCreateOrderRequest) (*UserListSellerProductSingleVariantForCreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListSellerProductSingleVariantForCreateOrder not implemented")
}
func (UnimplementedSellerProductListingOrderCreatingAPIServer) testEmbeddedByValue() {}

// UnsafeSellerProductListingOrderCreatingAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellerProductListingOrderCreatingAPIServer will
// result in compilation errors.
type UnsafeSellerProductListingOrderCreatingAPIServer interface {
	mustEmbedUnimplementedSellerProductListingOrderCreatingAPIServer()
}

func RegisterSellerProductListingOrderCreatingAPIServer(s grpc.ServiceRegistrar, srv SellerProductListingOrderCreatingAPIServer) {
	// If the following call pancis, it indicates UnimplementedSellerProductListingOrderCreatingAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SellerProductListingOrderCreatingAPI_ServiceDesc, srv)
}

func _SellerProductListingOrderCreatingAPI_UserListSellerProductSingleForCreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListSellerProductSingleForCreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerProductListingOrderCreatingAPIServer).UserListSellerProductSingleForCreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerProductListingOrderCreatingAPI_UserListSellerProductSingleForCreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerProductListingOrderCreatingAPIServer).UserListSellerProductSingleForCreateOrder(ctx, req.(*UserListSellerProductSingleForCreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerProductListingOrderCreatingAPI_UserListSellerProductGroupForCreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListSellerProductGroupForCreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerProductListingOrderCreatingAPIServer).UserListSellerProductGroupForCreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerProductListingOrderCreatingAPI_UserListSellerProductGroupForCreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerProductListingOrderCreatingAPIServer).UserListSellerProductGroupForCreateOrder(ctx, req.(*UserListSellerProductGroupForCreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerProductListingOrderCreatingAPI_UserListSellerProductSingleVariantForCreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListSellerProductSingleVariantForCreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerProductListingOrderCreatingAPIServer).UserListSellerProductSingleVariantForCreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerProductListingOrderCreatingAPI_UserListSellerProductSingleVariantForCreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerProductListingOrderCreatingAPIServer).UserListSellerProductSingleVariantForCreateOrder(ctx, req.(*UserListSellerProductSingleVariantForCreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SellerProductListingOrderCreatingAPI_ServiceDesc is the grpc.ServiceDesc for SellerProductListingOrderCreatingAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SellerProductListingOrderCreatingAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.pod.v1.SellerProductListingOrderCreatingAPI",
	HandlerType: (*SellerProductListingOrderCreatingAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserListSellerProductSingleForCreateOrder",
			Handler:    _SellerProductListingOrderCreatingAPI_UserListSellerProductSingleForCreateOrder_Handler,
		},
		{
			MethodName: "UserListSellerProductGroupForCreateOrder",
			Handler:    _SellerProductListingOrderCreatingAPI_UserListSellerProductGroupForCreateOrder_Handler,
		},
		{
			MethodName: "UserListSellerProductSingleVariantForCreateOrder",
			Handler:    _SellerProductListingOrderCreatingAPI_UserListSellerProductSingleVariantForCreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pod/v1/seller_product_order.proto",
}
