// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/pod/v1/vendor_routing_admin_api.proto

package podv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VendorRoutingAdminAPI_StaffListFulfillmentVendors_FullMethodName       = "/api.pod.v1.VendorRoutingAdminAPI/StaffListFulfillmentVendors"
	VendorRoutingAdminAPI_StaffListFulfillmentDestinations_FullMethodName  = "/api.pod.v1.VendorRoutingAdminAPI/StaffListFulfillmentDestinations"
	VendorRoutingAdminAPI_StaffListVendorRoutingRules_FullMethodName       = "/api.pod.v1.VendorRoutingAdminAPI/StaffListVendorRoutingRules"
	VendorRoutingAdminAPI_StaffGetVendorRoutingRule_FullMethodName         = "/api.pod.v1.VendorRoutingAdminAPI/StaffGetVendorRoutingRule"
	VendorRoutingAdminAPI_StaffCreateVendorRoutingRule_FullMethodName      = "/api.pod.v1.VendorRoutingAdminAPI/StaffCreateVendorRoutingRule"
	VendorRoutingAdminAPI_StaffUpdateVendorRoutingRule_FullMethodName      = "/api.pod.v1.VendorRoutingAdminAPI/StaffUpdateVendorRoutingRule"
	VendorRoutingAdminAPI_StaffDeleteVendorRoutingRule_FullMethodName      = "/api.pod.v1.VendorRoutingAdminAPI/StaffDeleteVendorRoutingRule"
	VendorRoutingAdminAPI_StaffListVendorVariantMappings_FullMethodName    = "/api.pod.v1.VendorRoutingAdminAPI/StaffListVendorVariantMappings"
	VendorRoutingAdminAPI_StaffCreateVendorVariantMapping_FullMethodName   = "/api.pod.v1.VendorRoutingAdminAPI/StaffCreateVendorVariantMapping"
	VendorRoutingAdminAPI_StaffUpdateVendorVariantMapping_FullMethodName   = "/api.pod.v1.VendorRoutingAdminAPI/StaffUpdateVendorVariantMapping"
	VendorRoutingAdminAPI_StaffDeleteVendorVariantMapping_FullMethodName   = "/api.pod.v1.VendorRoutingAdminAPI/StaffDeleteVendorVariantMapping"
	VendorRoutingAdminAPI_StaffPreviewOrderRouting_FullMethodName          = "/api.pod.v1.VendorRoutingAdminAPI/StaffPreviewOrderRouting"
	VendorRoutingAdminAPI_StaffListFulfillmentPackages_FullMethodName      = "/api.pod.v1.VendorRoutingAdminAPI/StaffListFulfillmentPackages"
	VendorRoutingAdminAPI_StaffListRoutingDecisions_FullMethodName         = "/api.pod.v1.VendorRoutingAdminAPI/StaffListRoutingDecisions"
	VendorRoutingAdminAPI_StaffCountRoutingDecisionStats_FullMethodName    = "/api.pod.v1.VendorRoutingAdminAPI/StaffCountRoutingDecisionStats"
	VendorRoutingAdminAPI_StaffOverrideRoutingDecision_FullMethodName      = "/api.pod.v1.VendorRoutingAdminAPI/StaffOverrideRoutingDecision"
	VendorRoutingAdminAPI_StaffReRouteDecision_FullMethodName              = "/api.pod.v1.VendorRoutingAdminAPI/StaffReRouteDecision"
	VendorRoutingAdminAPI_StaffManualRouteOrders_FullMethodName            = "/api.pod.v1.VendorRoutingAdminAPI/StaffManualRouteOrders"
	VendorRoutingAdminAPI_StaffGetDestinationLoad_FullMethodName           = "/api.pod.v1.VendorRoutingAdminAPI/StaffGetDestinationLoad"
	VendorRoutingAdminAPI_StaffListCapacityLines_FullMethodName            = "/api.pod.v1.VendorRoutingAdminAPI/StaffListCapacityLines"
	VendorRoutingAdminAPI_StaffGetCapacityMatrix_FullMethodName            = "/api.pod.v1.VendorRoutingAdminAPI/StaffGetCapacityMatrix"
	VendorRoutingAdminAPI_StaffUpdateCapacityLine_FullMethodName           = "/api.pod.v1.VendorRoutingAdminAPI/StaffUpdateCapacityLine"
	VendorRoutingAdminAPI_StaffSetMachineAvailability_FullMethodName       = "/api.pod.v1.VendorRoutingAdminAPI/StaffSetMachineAvailability"
	VendorRoutingAdminAPI_StaffUpdateFulfillmentDestination_FullMethodName = "/api.pod.v1.VendorRoutingAdminAPI/StaffUpdateFulfillmentDestination"
)

// VendorRoutingAdminAPIClient is the client API for VendorRoutingAdminAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VendorRoutingAdminAPI manages the configuration that decides which fulfillment
// vendor an order is routed to. It exposes CRUD over the vendor routing rules
// (category_code -> vendor) and the vendor variant mappings (variant_sku ->
// vendor-specific variant id), plus a read-only preview that mirrors the
// runtime vendor-resolution logic so staff can validate rules before activating.
type VendorRoutingAdminAPIClient interface {
	// --- Reference data ---
	StaffListFulfillmentVendors(ctx context.Context, in *StaffListFulfillmentVendorsRequest, opts ...grpc.CallOption) (*StaffListFulfillmentVendorsResponse, error)
	StaffListFulfillmentDestinations(ctx context.Context, in *StaffListFulfillmentDestinationsRequest, opts ...grpc.CallOption) (*StaffListFulfillmentDestinationsResponse, error)
	// --- Vendor routing rules ---
	StaffListVendorRoutingRules(ctx context.Context, in *StaffListVendorRoutingRulesRequest, opts ...grpc.CallOption) (*StaffListVendorRoutingRulesResponse, error)
	StaffGetVendorRoutingRule(ctx context.Context, in *StaffGetVendorRoutingRuleRequest, opts ...grpc.CallOption) (*StaffGetVendorRoutingRuleResponse, error)
	StaffCreateVendorRoutingRule(ctx context.Context, in *StaffCreateVendorRoutingRuleRequest, opts ...grpc.CallOption) (*StaffCreateVendorRoutingRuleResponse, error)
	StaffUpdateVendorRoutingRule(ctx context.Context, in *StaffUpdateVendorRoutingRuleRequest, opts ...grpc.CallOption) (*StaffUpdateVendorRoutingRuleResponse, error)
	StaffDeleteVendorRoutingRule(ctx context.Context, in *StaffDeleteVendorRoutingRuleRequest, opts ...grpc.CallOption) (*StaffDeleteVendorRoutingRuleResponse, error)
	// --- Vendor variant mappings ---
	StaffListVendorVariantMappings(ctx context.Context, in *StaffListVendorVariantMappingsRequest, opts ...grpc.CallOption) (*StaffListVendorVariantMappingsResponse, error)
	StaffCreateVendorVariantMapping(ctx context.Context, in *StaffCreateVendorVariantMappingRequest, opts ...grpc.CallOption) (*StaffCreateVendorVariantMappingResponse, error)
	StaffUpdateVendorVariantMapping(ctx context.Context, in *StaffUpdateVendorVariantMappingRequest, opts ...grpc.CallOption) (*StaffUpdateVendorVariantMappingResponse, error)
	StaffDeleteVendorVariantMapping(ctx context.Context, in *StaffDeleteVendorVariantMappingRequest, opts ...grpc.CallOption) (*StaffDeleteVendorVariantMappingResponse, error)
	// --- Preview ---
	StaffPreviewOrderRouting(ctx context.Context, in *StaffPreviewOrderRoutingRequest, opts ...grpc.CallOption) (*StaffPreviewOrderRoutingResponse, error)
	// --- Routed packages (observability) ---
	StaffListFulfillmentPackages(ctx context.Context, in *StaffListFulfillmentPackagesRequest, opts ...grpc.CallOption) (*StaffListFulfillmentPackagesResponse, error)
	// --- Routing decisions (decision trace / queue, slice R3) ---
	StaffListRoutingDecisions(ctx context.Context, in *StaffListRoutingDecisionsRequest, opts ...grpc.CallOption) (*StaffListRoutingDecisionsResponse, error)
	StaffCountRoutingDecisionStats(ctx context.Context, in *StaffCountRoutingDecisionStatsRequest, opts ...grpc.CallOption) (*StaffCountRoutingDecisionStatsResponse, error)
	// --- Review gate / manual routing (slice R3b) ---
	StaffOverrideRoutingDecision(ctx context.Context, in *StaffOverrideRoutingDecisionRequest, opts ...grpc.CallOption) (*StaffOverrideRoutingDecisionResponse, error)
	StaffReRouteDecision(ctx context.Context, in *StaffReRouteDecisionRequest, opts ...grpc.CallOption) (*StaffReRouteDecisionResponse, error)
	StaffManualRouteOrders(ctx context.Context, in *StaffManualRouteOrdersRequest, opts ...grpc.CallOption) (*StaffManualRouteOrdersResponse, error)
	// --- Capacity / day-load (slice R4) ---
	StaffGetDestinationLoad(ctx context.Context, in *StaffGetDestinationLoadRequest, opts ...grpc.CallOption) (*StaffGetDestinationLoadResponse, error)
	// --- Capacity matrix (slice R10a) ---
	StaffListCapacityLines(ctx context.Context, in *StaffListCapacityLinesRequest, opts ...grpc.CallOption) (*StaffListCapacityLinesResponse, error)
	StaffGetCapacityMatrix(ctx context.Context, in *StaffGetCapacityMatrixRequest, opts ...grpc.CallOption) (*StaffGetCapacityMatrixResponse, error)
	StaffUpdateCapacityLine(ctx context.Context, in *StaffUpdateCapacityLineRequest, opts ...grpc.CallOption) (*StaffUpdateCapacityLineResponse, error)
	StaffSetMachineAvailability(ctx context.Context, in *StaffSetMachineAvailabilityRequest, opts ...grpc.CallOption) (*StaffSetMachineAvailabilityResponse, error)
	StaffUpdateFulfillmentDestination(ctx context.Context, in *StaffUpdateFulfillmentDestinationRequest, opts ...grpc.CallOption) (*StaffUpdateFulfillmentDestinationResponse, error)
}

type vendorRoutingAdminAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewVendorRoutingAdminAPIClient(cc grpc.ClientConnInterface) VendorRoutingAdminAPIClient {
	return &vendorRoutingAdminAPIClient{cc}
}

func (c *vendorRoutingAdminAPIClient) StaffListFulfillmentVendors(ctx context.Context, in *StaffListFulfillmentVendorsRequest, opts ...grpc.CallOption) (*StaffListFulfillmentVendorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListFulfillmentVendorsResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffListFulfillmentVendors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffListFulfillmentDestinations(ctx context.Context, in *StaffListFulfillmentDestinationsRequest, opts ...grpc.CallOption) (*StaffListFulfillmentDestinationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListFulfillmentDestinationsResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffListFulfillmentDestinations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffListVendorRoutingRules(ctx context.Context, in *StaffListVendorRoutingRulesRequest, opts ...grpc.CallOption) (*StaffListVendorRoutingRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListVendorRoutingRulesResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffListVendorRoutingRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffGetVendorRoutingRule(ctx context.Context, in *StaffGetVendorRoutingRuleRequest, opts ...grpc.CallOption) (*StaffGetVendorRoutingRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffGetVendorRoutingRuleResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffGetVendorRoutingRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffCreateVendorRoutingRule(ctx context.Context, in *StaffCreateVendorRoutingRuleRequest, opts ...grpc.CallOption) (*StaffCreateVendorRoutingRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffCreateVendorRoutingRuleResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffCreateVendorRoutingRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffUpdateVendorRoutingRule(ctx context.Context, in *StaffUpdateVendorRoutingRuleRequest, opts ...grpc.CallOption) (*StaffUpdateVendorRoutingRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffUpdateVendorRoutingRuleResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffUpdateVendorRoutingRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffDeleteVendorRoutingRule(ctx context.Context, in *StaffDeleteVendorRoutingRuleRequest, opts ...grpc.CallOption) (*StaffDeleteVendorRoutingRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffDeleteVendorRoutingRuleResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffDeleteVendorRoutingRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffListVendorVariantMappings(ctx context.Context, in *StaffListVendorVariantMappingsRequest, opts ...grpc.CallOption) (*StaffListVendorVariantMappingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListVendorVariantMappingsResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffListVendorVariantMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffCreateVendorVariantMapping(ctx context.Context, in *StaffCreateVendorVariantMappingRequest, opts ...grpc.CallOption) (*StaffCreateVendorVariantMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffCreateVendorVariantMappingResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffCreateVendorVariantMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffUpdateVendorVariantMapping(ctx context.Context, in *StaffUpdateVendorVariantMappingRequest, opts ...grpc.CallOption) (*StaffUpdateVendorVariantMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffUpdateVendorVariantMappingResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffUpdateVendorVariantMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffDeleteVendorVariantMapping(ctx context.Context, in *StaffDeleteVendorVariantMappingRequest, opts ...grpc.CallOption) (*StaffDeleteVendorVariantMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffDeleteVendorVariantMappingResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffDeleteVendorVariantMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffPreviewOrderRouting(ctx context.Context, in *StaffPreviewOrderRoutingRequest, opts ...grpc.CallOption) (*StaffPreviewOrderRoutingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffPreviewOrderRoutingResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffPreviewOrderRouting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffListFulfillmentPackages(ctx context.Context, in *StaffListFulfillmentPackagesRequest, opts ...grpc.CallOption) (*StaffListFulfillmentPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListFulfillmentPackagesResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffListFulfillmentPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffListRoutingDecisions(ctx context.Context, in *StaffListRoutingDecisionsRequest, opts ...grpc.CallOption) (*StaffListRoutingDecisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListRoutingDecisionsResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffListRoutingDecisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffCountRoutingDecisionStats(ctx context.Context, in *StaffCountRoutingDecisionStatsRequest, opts ...grpc.CallOption) (*StaffCountRoutingDecisionStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffCountRoutingDecisionStatsResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffCountRoutingDecisionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffOverrideRoutingDecision(ctx context.Context, in *StaffOverrideRoutingDecisionRequest, opts ...grpc.CallOption) (*StaffOverrideRoutingDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffOverrideRoutingDecisionResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffOverrideRoutingDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffReRouteDecision(ctx context.Context, in *StaffReRouteDecisionRequest, opts ...grpc.CallOption) (*StaffReRouteDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffReRouteDecisionResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffReRouteDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffManualRouteOrders(ctx context.Context, in *StaffManualRouteOrdersRequest, opts ...grpc.CallOption) (*StaffManualRouteOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffManualRouteOrdersResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffManualRouteOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffGetDestinationLoad(ctx context.Context, in *StaffGetDestinationLoadRequest, opts ...grpc.CallOption) (*StaffGetDestinationLoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffGetDestinationLoadResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffGetDestinationLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffListCapacityLines(ctx context.Context, in *StaffListCapacityLinesRequest, opts ...grpc.CallOption) (*StaffListCapacityLinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffListCapacityLinesResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffListCapacityLines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffGetCapacityMatrix(ctx context.Context, in *StaffGetCapacityMatrixRequest, opts ...grpc.CallOption) (*StaffGetCapacityMatrixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffGetCapacityMatrixResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffGetCapacityMatrix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffUpdateCapacityLine(ctx context.Context, in *StaffUpdateCapacityLineRequest, opts ...grpc.CallOption) (*StaffUpdateCapacityLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffUpdateCapacityLineResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffUpdateCapacityLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffSetMachineAvailability(ctx context.Context, in *StaffSetMachineAvailabilityRequest, opts ...grpc.CallOption) (*StaffSetMachineAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffSetMachineAvailabilityResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffSetMachineAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorRoutingAdminAPIClient) StaffUpdateFulfillmentDestination(ctx context.Context, in *StaffUpdateFulfillmentDestinationRequest, opts ...grpc.CallOption) (*StaffUpdateFulfillmentDestinationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaffUpdateFulfillmentDestinationResponse)
	err := c.cc.Invoke(ctx, VendorRoutingAdminAPI_StaffUpdateFulfillmentDestination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VendorRoutingAdminAPIServer is the server API for VendorRoutingAdminAPI service.
// All implementations should embed UnimplementedVendorRoutingAdminAPIServer
// for forward compatibility.
//
// VendorRoutingAdminAPI manages the configuration that decides which fulfillment
// vendor an order is routed to. It exposes CRUD over the vendor routing rules
// (category_code -> vendor) and the vendor variant mappings (variant_sku ->
// vendor-specific variant id), plus a read-only preview that mirrors the
// runtime vendor-resolution logic so staff can validate rules before activating.
type VendorRoutingAdminAPIServer interface {
	// --- Reference data ---
	StaffListFulfillmentVendors(context.Context, *StaffListFulfillmentVendorsRequest) (*StaffListFulfillmentVendorsResponse, error)
	StaffListFulfillmentDestinations(context.Context, *StaffListFulfillmentDestinationsRequest) (*StaffListFulfillmentDestinationsResponse, error)
	// --- Vendor routing rules ---
	StaffListVendorRoutingRules(context.Context, *StaffListVendorRoutingRulesRequest) (*StaffListVendorRoutingRulesResponse, error)
	StaffGetVendorRoutingRule(context.Context, *StaffGetVendorRoutingRuleRequest) (*StaffGetVendorRoutingRuleResponse, error)
	StaffCreateVendorRoutingRule(context.Context, *StaffCreateVendorRoutingRuleRequest) (*StaffCreateVendorRoutingRuleResponse, error)
	StaffUpdateVendorRoutingRule(context.Context, *StaffUpdateVendorRoutingRuleRequest) (*StaffUpdateVendorRoutingRuleResponse, error)
	StaffDeleteVendorRoutingRule(context.Context, *StaffDeleteVendorRoutingRuleRequest) (*StaffDeleteVendorRoutingRuleResponse, error)
	// --- Vendor variant mappings ---
	StaffListVendorVariantMappings(context.Context, *StaffListVendorVariantMappingsRequest) (*StaffListVendorVariantMappingsResponse, error)
	StaffCreateVendorVariantMapping(context.Context, *StaffCreateVendorVariantMappingRequest) (*StaffCreateVendorVariantMappingResponse, error)
	StaffUpdateVendorVariantMapping(context.Context, *StaffUpdateVendorVariantMappingRequest) (*StaffUpdateVendorVariantMappingResponse, error)
	StaffDeleteVendorVariantMapping(context.Context, *StaffDeleteVendorVariantMappingRequest) (*StaffDeleteVendorVariantMappingResponse, error)
	// --- Preview ---
	StaffPreviewOrderRouting(context.Context, *StaffPreviewOrderRoutingRequest) (*StaffPreviewOrderRoutingResponse, error)
	// --- Routed packages (observability) ---
	StaffListFulfillmentPackages(context.Context, *StaffListFulfillmentPackagesRequest) (*StaffListFulfillmentPackagesResponse, error)
	// --- Routing decisions (decision trace / queue, slice R3) ---
	StaffListRoutingDecisions(context.Context, *StaffListRoutingDecisionsRequest) (*StaffListRoutingDecisionsResponse, error)
	StaffCountRoutingDecisionStats(context.Context, *StaffCountRoutingDecisionStatsRequest) (*StaffCountRoutingDecisionStatsResponse, error)
	// --- Review gate / manual routing (slice R3b) ---
	StaffOverrideRoutingDecision(context.Context, *StaffOverrideRoutingDecisionRequest) (*StaffOverrideRoutingDecisionResponse, error)
	StaffReRouteDecision(context.Context, *StaffReRouteDecisionRequest) (*StaffReRouteDecisionResponse, error)
	StaffManualRouteOrders(context.Context, *StaffManualRouteOrdersRequest) (*StaffManualRouteOrdersResponse, error)
	// --- Capacity / day-load (slice R4) ---
	StaffGetDestinationLoad(context.Context, *StaffGetDestinationLoadRequest) (*StaffGetDestinationLoadResponse, error)
	// --- Capacity matrix (slice R10a) ---
	StaffListCapacityLines(context.Context, *StaffListCapacityLinesRequest) (*StaffListCapacityLinesResponse, error)
	StaffGetCapacityMatrix(context.Context, *StaffGetCapacityMatrixRequest) (*StaffGetCapacityMatrixResponse, error)
	StaffUpdateCapacityLine(context.Context, *StaffUpdateCapacityLineRequest) (*StaffUpdateCapacityLineResponse, error)
	StaffSetMachineAvailability(context.Context, *StaffSetMachineAvailabilityRequest) (*StaffSetMachineAvailabilityResponse, error)
	StaffUpdateFulfillmentDestination(context.Context, *StaffUpdateFulfillmentDestinationRequest) (*StaffUpdateFulfillmentDestinationResponse, error)
}

// UnimplementedVendorRoutingAdminAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVendorRoutingAdminAPIServer struct{}

func (UnimplementedVendorRoutingAdminAPIServer) StaffListFulfillmentVendors(context.Context, *StaffListFulfillmentVendorsRequest) (*StaffListFulfillmentVendorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListFulfillmentVendors not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffListFulfillmentDestinations(context.Context, *StaffListFulfillmentDestinationsRequest) (*StaffListFulfillmentDestinationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListFulfillmentDestinations not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffListVendorRoutingRules(context.Context, *StaffListVendorRoutingRulesRequest) (*StaffListVendorRoutingRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListVendorRoutingRules not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffGetVendorRoutingRule(context.Context, *StaffGetVendorRoutingRuleRequest) (*StaffGetVendorRoutingRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffGetVendorRoutingRule not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffCreateVendorRoutingRule(context.Context, *StaffCreateVendorRoutingRuleRequest) (*StaffCreateVendorRoutingRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffCreateVendorRoutingRule not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffUpdateVendorRoutingRule(context.Context, *StaffUpdateVendorRoutingRuleRequest) (*StaffUpdateVendorRoutingRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffUpdateVendorRoutingRule not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffDeleteVendorRoutingRule(context.Context, *StaffDeleteVendorRoutingRuleRequest) (*StaffDeleteVendorRoutingRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffDeleteVendorRoutingRule not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffListVendorVariantMappings(context.Context, *StaffListVendorVariantMappingsRequest) (*StaffListVendorVariantMappingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListVendorVariantMappings not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffCreateVendorVariantMapping(context.Context, *StaffCreateVendorVariantMappingRequest) (*StaffCreateVendorVariantMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffCreateVendorVariantMapping not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffUpdateVendorVariantMapping(context.Context, *StaffUpdateVendorVariantMappingRequest) (*StaffUpdateVendorVariantMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffUpdateVendorVariantMapping not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffDeleteVendorVariantMapping(context.Context, *StaffDeleteVendorVariantMappingRequest) (*StaffDeleteVendorVariantMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffDeleteVendorVariantMapping not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffPreviewOrderRouting(context.Context, *StaffPreviewOrderRoutingRequest) (*StaffPreviewOrderRoutingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffPreviewOrderRouting not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffListFulfillmentPackages(context.Context, *StaffListFulfillmentPackagesRequest) (*StaffListFulfillmentPackagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListFulfillmentPackages not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffListRoutingDecisions(context.Context, *StaffListRoutingDecisionsRequest) (*StaffListRoutingDecisionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListRoutingDecisions not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffCountRoutingDecisionStats(context.Context, *StaffCountRoutingDecisionStatsRequest) (*StaffCountRoutingDecisionStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffCountRoutingDecisionStats not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffOverrideRoutingDecision(context.Context, *StaffOverrideRoutingDecisionRequest) (*StaffOverrideRoutingDecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffOverrideRoutingDecision not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffReRouteDecision(context.Context, *StaffReRouteDecisionRequest) (*StaffReRouteDecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffReRouteDecision not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffManualRouteOrders(context.Context, *StaffManualRouteOrdersRequest) (*StaffManualRouteOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffManualRouteOrders not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffGetDestinationLoad(context.Context, *StaffGetDestinationLoadRequest) (*StaffGetDestinationLoadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffGetDestinationLoad not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffListCapacityLines(context.Context, *StaffListCapacityLinesRequest) (*StaffListCapacityLinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffListCapacityLines not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffGetCapacityMatrix(context.Context, *StaffGetCapacityMatrixRequest) (*StaffGetCapacityMatrixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffGetCapacityMatrix not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffUpdateCapacityLine(context.Context, *StaffUpdateCapacityLineRequest) (*StaffUpdateCapacityLineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffUpdateCapacityLine not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffSetMachineAvailability(context.Context, *StaffSetMachineAvailabilityRequest) (*StaffSetMachineAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffSetMachineAvailability not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) StaffUpdateFulfillmentDestination(context.Context, *StaffUpdateFulfillmentDestinationRequest) (*StaffUpdateFulfillmentDestinationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaffUpdateFulfillmentDestination not implemented")
}
func (UnimplementedVendorRoutingAdminAPIServer) testEmbeddedByValue() {}

// UnsafeVendorRoutingAdminAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VendorRoutingAdminAPIServer will
// result in compilation errors.
type UnsafeVendorRoutingAdminAPIServer interface {
	mustEmbedUnimplementedVendorRoutingAdminAPIServer()
}

func RegisterVendorRoutingAdminAPIServer(s grpc.ServiceRegistrar, srv VendorRoutingAdminAPIServer) {
	// If the following call pancis, it indicates UnimplementedVendorRoutingAdminAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VendorRoutingAdminAPI_ServiceDesc, srv)
}

func _VendorRoutingAdminAPI_StaffListFulfillmentVendors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListFulfillmentVendorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffListFulfillmentVendors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffListFulfillmentVendors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffListFulfillmentVendors(ctx, req.(*StaffListFulfillmentVendorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffListFulfillmentDestinations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListFulfillmentDestinationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffListFulfillmentDestinations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffListFulfillmentDestinations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffListFulfillmentDestinations(ctx, req.(*StaffListFulfillmentDestinationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffListVendorRoutingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListVendorRoutingRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffListVendorRoutingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffListVendorRoutingRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffListVendorRoutingRules(ctx, req.(*StaffListVendorRoutingRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffGetVendorRoutingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffGetVendorRoutingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffGetVendorRoutingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffGetVendorRoutingRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffGetVendorRoutingRule(ctx, req.(*StaffGetVendorRoutingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffCreateVendorRoutingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffCreateVendorRoutingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffCreateVendorRoutingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffCreateVendorRoutingRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffCreateVendorRoutingRule(ctx, req.(*StaffCreateVendorRoutingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffUpdateVendorRoutingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffUpdateVendorRoutingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffUpdateVendorRoutingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffUpdateVendorRoutingRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffUpdateVendorRoutingRule(ctx, req.(*StaffUpdateVendorRoutingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffDeleteVendorRoutingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffDeleteVendorRoutingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffDeleteVendorRoutingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffDeleteVendorRoutingRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffDeleteVendorRoutingRule(ctx, req.(*StaffDeleteVendorRoutingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffListVendorVariantMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListVendorVariantMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffListVendorVariantMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffListVendorVariantMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffListVendorVariantMappings(ctx, req.(*StaffListVendorVariantMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffCreateVendorVariantMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffCreateVendorVariantMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffCreateVendorVariantMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffCreateVendorVariantMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffCreateVendorVariantMapping(ctx, req.(*StaffCreateVendorVariantMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffUpdateVendorVariantMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffUpdateVendorVariantMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffUpdateVendorVariantMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffUpdateVendorVariantMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffUpdateVendorVariantMapping(ctx, req.(*StaffUpdateVendorVariantMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffDeleteVendorVariantMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffDeleteVendorVariantMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffDeleteVendorVariantMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffDeleteVendorVariantMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffDeleteVendorVariantMapping(ctx, req.(*StaffDeleteVendorVariantMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffPreviewOrderRouting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffPreviewOrderRoutingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffPreviewOrderRouting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffPreviewOrderRouting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffPreviewOrderRouting(ctx, req.(*StaffPreviewOrderRoutingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffListFulfillmentPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListFulfillmentPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffListFulfillmentPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffListFulfillmentPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffListFulfillmentPackages(ctx, req.(*StaffListFulfillmentPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffListRoutingDecisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListRoutingDecisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffListRoutingDecisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffListRoutingDecisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffListRoutingDecisions(ctx, req.(*StaffListRoutingDecisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffCountRoutingDecisionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffCountRoutingDecisionStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffCountRoutingDecisionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffCountRoutingDecisionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffCountRoutingDecisionStats(ctx, req.(*StaffCountRoutingDecisionStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffOverrideRoutingDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffOverrideRoutingDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffOverrideRoutingDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffOverrideRoutingDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffOverrideRoutingDecision(ctx, req.(*StaffOverrideRoutingDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffReRouteDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffReRouteDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffReRouteDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffReRouteDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffReRouteDecision(ctx, req.(*StaffReRouteDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffManualRouteOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffManualRouteOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffManualRouteOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffManualRouteOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffManualRouteOrders(ctx, req.(*StaffManualRouteOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffGetDestinationLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffGetDestinationLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffGetDestinationLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffGetDestinationLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffGetDestinationLoad(ctx, req.(*StaffGetDestinationLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffListCapacityLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffListCapacityLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffListCapacityLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffListCapacityLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffListCapacityLines(ctx, req.(*StaffListCapacityLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffGetCapacityMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffGetCapacityMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffGetCapacityMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffGetCapacityMatrix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffGetCapacityMatrix(ctx, req.(*StaffGetCapacityMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffUpdateCapacityLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffUpdateCapacityLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffUpdateCapacityLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffUpdateCapacityLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffUpdateCapacityLine(ctx, req.(*StaffUpdateCapacityLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffSetMachineAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffSetMachineAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffSetMachineAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffSetMachineAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffSetMachineAvailability(ctx, req.(*StaffSetMachineAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorRoutingAdminAPI_StaffUpdateFulfillmentDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffUpdateFulfillmentDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorRoutingAdminAPIServer).StaffUpdateFulfillmentDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorRoutingAdminAPI_StaffUpdateFulfillmentDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorRoutingAdminAPIServer).StaffUpdateFulfillmentDestination(ctx, req.(*StaffUpdateFulfillmentDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VendorRoutingAdminAPI_ServiceDesc is the grpc.ServiceDesc for VendorRoutingAdminAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VendorRoutingAdminAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.pod.v1.VendorRoutingAdminAPI",
	HandlerType: (*VendorRoutingAdminAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StaffListFulfillmentVendors",
			Handler:    _VendorRoutingAdminAPI_StaffListFulfillmentVendors_Handler,
		},
		{
			MethodName: "StaffListFulfillmentDestinations",
			Handler:    _VendorRoutingAdminAPI_StaffListFulfillmentDestinations_Handler,
		},
		{
			MethodName: "StaffListVendorRoutingRules",
			Handler:    _VendorRoutingAdminAPI_StaffListVendorRoutingRules_Handler,
		},
		{
			MethodName: "StaffGetVendorRoutingRule",
			Handler:    _VendorRoutingAdminAPI_StaffGetVendorRoutingRule_Handler,
		},
		{
			MethodName: "StaffCreateVendorRoutingRule",
			Handler:    _VendorRoutingAdminAPI_StaffCreateVendorRoutingRule_Handler,
		},
		{
			MethodName: "StaffUpdateVendorRoutingRule",
			Handler:    _VendorRoutingAdminAPI_StaffUpdateVendorRoutingRule_Handler,
		},
		{
			MethodName: "StaffDeleteVendorRoutingRule",
			Handler:    _VendorRoutingAdminAPI_StaffDeleteVendorRoutingRule_Handler,
		},
		{
			MethodName: "StaffListVendorVariantMappings",
			Handler:    _VendorRoutingAdminAPI_StaffListVendorVariantMappings_Handler,
		},
		{
			MethodName: "StaffCreateVendorVariantMapping",
			Handler:    _VendorRoutingAdminAPI_StaffCreateVendorVariantMapping_Handler,
		},
		{
			MethodName: "StaffUpdateVendorVariantMapping",
			Handler:    _VendorRoutingAdminAPI_StaffUpdateVendorVariantMapping_Handler,
		},
		{
			MethodName: "StaffDeleteVendorVariantMapping",
			Handler:    _VendorRoutingAdminAPI_StaffDeleteVendorVariantMapping_Handler,
		},
		{
			MethodName: "StaffPreviewOrderRouting",
			Handler:    _VendorRoutingAdminAPI_StaffPreviewOrderRouting_Handler,
		},
		{
			MethodName: "StaffListFulfillmentPackages",
			Handler:    _VendorRoutingAdminAPI_StaffListFulfillmentPackages_Handler,
		},
		{
			MethodName: "StaffListRoutingDecisions",
			Handler:    _VendorRoutingAdminAPI_StaffListRoutingDecisions_Handler,
		},
		{
			MethodName: "StaffCountRoutingDecisionStats",
			Handler:    _VendorRoutingAdminAPI_StaffCountRoutingDecisionStats_Handler,
		},
		{
			MethodName: "StaffOverrideRoutingDecision",
			Handler:    _VendorRoutingAdminAPI_StaffOverrideRoutingDecision_Handler,
		},
		{
			MethodName: "StaffReRouteDecision",
			Handler:    _VendorRoutingAdminAPI_StaffReRouteDecision_Handler,
		},
		{
			MethodName: "StaffManualRouteOrders",
			Handler:    _VendorRoutingAdminAPI_StaffManualRouteOrders_Handler,
		},
		{
			MethodName: "StaffGetDestinationLoad",
			Handler:    _VendorRoutingAdminAPI_StaffGetDestinationLoad_Handler,
		},
		{
			MethodName: "StaffListCapacityLines",
			Handler:    _VendorRoutingAdminAPI_StaffListCapacityLines_Handler,
		},
		{
			MethodName: "StaffGetCapacityMatrix",
			Handler:    _VendorRoutingAdminAPI_StaffGetCapacityMatrix_Handler,
		},
		{
			MethodName: "StaffUpdateCapacityLine",
			Handler:    _VendorRoutingAdminAPI_StaffUpdateCapacityLine_Handler,
		},
		{
			MethodName: "StaffSetMachineAvailability",
			Handler:    _VendorRoutingAdminAPI_StaffSetMachineAvailability_Handler,
		},
		{
			MethodName: "StaffUpdateFulfillmentDestination",
			Handler:    _VendorRoutingAdminAPI_StaffUpdateFulfillmentDestination_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pod/v1/vendor_routing_admin_api.proto",
}
