// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: backend/ffm/v1/product_import.proto

package ffmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaitForProductImportFileUploadParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileUploadUrl string                 `protobuf:"bytes,3,opt,name=file_upload_url,json=fileUploadUrl,proto3" json:"file_upload_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForProductImportFileUploadParams) Reset() {
	*x = WaitForProductImportFileUploadParams{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForProductImportFileUploadParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForProductImportFileUploadParams) ProtoMessage() {}

func (x *WaitForProductImportFileUploadParams) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForProductImportFileUploadParams.ProtoReflect.Descriptor instead.
func (*WaitForProductImportFileUploadParams) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{0}
}

func (x *WaitForProductImportFileUploadParams) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *WaitForProductImportFileUploadParams) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *WaitForProductImportFileUploadParams) GetFileUploadUrl() string {
	if x != nil {
		return x.FileUploadUrl
	}
	return ""
}

type WaitForProductImportFileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUploadUrl string                 `protobuf:"bytes,1,opt,name=file_upload_url,json=fileUploadUrl,proto3" json:"file_upload_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForProductImportFileUploadResponse) Reset() {
	*x = WaitForProductImportFileUploadResponse{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForProductImportFileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForProductImportFileUploadResponse) ProtoMessage() {}

func (x *WaitForProductImportFileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForProductImportFileUploadResponse.ProtoReflect.Descriptor instead.
func (*WaitForProductImportFileUploadResponse) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{1}
}

func (x *WaitForProductImportFileUploadResponse) GetFileUploadUrl() string {
	if x != nil {
		return x.FileUploadUrl
	}
	return ""
}

type ImportFFMProductParams struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	TeamId        string                            `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Images        []*ImportFFMProductParams_Image   `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	WmsPush       []*ImportFFMProductParams_WMSPush `protobuf:"bytes,3,rep,name=wms_push,json=wmsPush,proto3" json:"wms_push,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportFFMProductParams) Reset() {
	*x = ImportFFMProductParams{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFFMProductParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFFMProductParams) ProtoMessage() {}

func (x *ImportFFMProductParams) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFFMProductParams.ProtoReflect.Descriptor instead.
func (*ImportFFMProductParams) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{2}
}

func (x *ImportFFMProductParams) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ImportFFMProductParams) GetImages() []*ImportFFMProductParams_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ImportFFMProductParams) GetWmsPush() []*ImportFFMProductParams_WMSPush {
	if x != nil {
		return x.WmsPush
	}
	return nil
}

type ImportFFMProductResult struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Images        []*ImportFFMProductResult_Image     `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	WmsRecords    []*ImportFFMProductResult_WMSRecord `protobuf:"bytes,2,rep,name=wms_records,json=wmsRecords,proto3" json:"wms_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportFFMProductResult) Reset() {
	*x = ImportFFMProductResult{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFFMProductResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFFMProductResult) ProtoMessage() {}

func (x *ImportFFMProductResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFFMProductResult.ProtoReflect.Descriptor instead.
func (*ImportFFMProductResult) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{3}
}

func (x *ImportFFMProductResult) GetImages() []*ImportFFMProductResult_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ImportFFMProductResult) GetWmsRecords() []*ImportFFMProductResult_WMSRecord {
	if x != nil {
		return x.WmsRecords
	}
	return nil
}

type ProcessImportWMSProductParams struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	TeamId        string                          `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	WmsPush       *ImportFFMProductParams_WMSPush `protobuf:"bytes,2,opt,name=wms_push,json=wmsPush,proto3" json:"wms_push,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessImportWMSProductParams) Reset() {
	*x = ProcessImportWMSProductParams{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessImportWMSProductParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessImportWMSProductParams) ProtoMessage() {}

func (x *ProcessImportWMSProductParams) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessImportWMSProductParams.ProtoReflect.Descriptor instead.
func (*ProcessImportWMSProductParams) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessImportWMSProductParams) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ProcessImportWMSProductParams) GetWmsPush() *ImportFFMProductParams_WMSPush {
	if x != nil {
		return x.WmsPush
	}
	return nil
}

type ProcessImportWMSProductResult struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	WmsRecord     *ImportFFMProductResult_WMSRecord `protobuf:"bytes,1,opt,name=wms_record,json=wmsRecord,proto3" json:"wms_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessImportWMSProductResult) Reset() {
	*x = ProcessImportWMSProductResult{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessImportWMSProductResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessImportWMSProductResult) ProtoMessage() {}

func (x *ProcessImportWMSProductResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessImportWMSProductResult.ProtoReflect.Descriptor instead.
func (*ProcessImportWMSProductResult) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessImportWMSProductResult) GetWmsRecord() *ImportFFMProductResult_WMSRecord {
	if x != nil {
		return x.WmsRecord
	}
	return nil
}

type CompleteImportFFMProductParams struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	TeamId        string                              `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Images        []*ImportFFMProductResult_Image     `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	WmsRecords    []*ImportFFMProductResult_WMSRecord `protobuf:"bytes,3,rep,name=wms_records,json=wmsRecords,proto3" json:"wms_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteImportFFMProductParams) Reset() {
	*x = CompleteImportFFMProductParams{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteImportFFMProductParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteImportFFMProductParams) ProtoMessage() {}

func (x *CompleteImportFFMProductParams) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteImportFFMProductParams.ProtoReflect.Descriptor instead.
func (*CompleteImportFFMProductParams) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteImportFFMProductParams) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CompleteImportFFMProductParams) GetImages() []*ImportFFMProductResult_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CompleteImportFFMProductParams) GetWmsRecords() []*ImportFFMProductResult_WMSRecord {
	if x != nil {
		return x.WmsRecords
	}
	return nil
}

type CompleteImportFFMProductResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteImportFFMProductResult) Reset() {
	*x = CompleteImportFFMProductResult{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteImportFFMProductResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteImportFFMProductResult) ProtoMessage() {}

func (x *CompleteImportFFMProductResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteImportFFMProductResult.ProtoReflect.Descriptor instead.
func (*CompleteImportFFMProductResult) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{7}
}

type ImportFFMProductParams_Image struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VariantId      string                 `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	OriginImageUrl string                 `protobuf:"bytes,2,opt,name=origin_image_url,json=originImageUrl,proto3" json:"origin_image_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportFFMProductParams_Image) Reset() {
	*x = ImportFFMProductParams_Image{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFFMProductParams_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFFMProductParams_Image) ProtoMessage() {}

func (x *ImportFFMProductParams_Image) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFFMProductParams_Image.ProtoReflect.Descriptor instead.
func (*ImportFFMProductParams_Image) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ImportFFMProductParams_Image) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *ImportFFMProductParams_Image) GetOriginImageUrl() string {
	if x != nil {
		return x.OriginImageUrl
	}
	return ""
}

type ImportFFMProductParams_WMSPush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VariantId      string                 `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	WarehouseCodes []string               `protobuf:"bytes,2,rep,name=warehouse_codes,json=warehouseCodes,proto3" json:"warehouse_codes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportFFMProductParams_WMSPush) Reset() {
	*x = ImportFFMProductParams_WMSPush{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFFMProductParams_WMSPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFFMProductParams_WMSPush) ProtoMessage() {}

func (x *ImportFFMProductParams_WMSPush) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFFMProductParams_WMSPush.ProtoReflect.Descriptor instead.
func (*ImportFFMProductParams_WMSPush) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ImportFFMProductParams_WMSPush) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *ImportFFMProductParams_WMSPush) GetWarehouseCodes() []string {
	if x != nil {
		return x.WarehouseCodes
	}
	return nil
}

type ImportFFMProductResult_Image struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VariantId      string                 `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	OriginImageUrl string                 `protobuf:"bytes,2,opt,name=origin_image_url,json=originImageUrl,proto3" json:"origin_image_url,omitempty"`
	MediaPath      string                 `protobuf:"bytes,3,opt,name=media_path,json=mediaPath,proto3" json:"media_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportFFMProductResult_Image) Reset() {
	*x = ImportFFMProductResult_Image{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFFMProductResult_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFFMProductResult_Image) ProtoMessage() {}

func (x *ImportFFMProductResult_Image) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFFMProductResult_Image.ProtoReflect.Descriptor instead.
func (*ImportFFMProductResult_Image) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ImportFFMProductResult_Image) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *ImportFFMProductResult_Image) GetOriginImageUrl() string {
	if x != nil {
		return x.OriginImageUrl
	}
	return ""
}

func (x *ImportFFMProductResult_Image) GetMediaPath() string {
	if x != nil {
		return x.MediaPath
	}
	return ""
}

type ImportFFMProductResult_WMSRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantId     string                 `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceSku  string                 `protobuf:"bytes,3,opt,name=reference_sku,json=referenceSku,proto3" json:"reference_sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportFFMProductResult_WMSRecord) Reset() {
	*x = ImportFFMProductResult_WMSRecord{}
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFFMProductResult_WMSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFFMProductResult_WMSRecord) ProtoMessage() {}

func (x *ImportFFMProductResult_WMSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_backend_ffm_v1_product_import_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFFMProductResult_WMSRecord.ProtoReflect.Descriptor instead.
func (*ImportFFMProductResult_WMSRecord) Descriptor() ([]byte, []int) {
	return file_backend_ffm_v1_product_import_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ImportFFMProductResult_WMSRecord) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *ImportFFMProductResult_WMSRecord) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *ImportFFMProductResult_WMSRecord) GetReferenceSku() string {
	if x != nil {
		return x.ReferenceSku
	}
	return ""
}

var File_backend_ffm_v1_product_import_proto protoreflect.FileDescriptor

var file_backend_ffm_v1_product_import_proto_rawDesc = string([]byte{
	0x0a, 0x23, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x66, 0x66, 0x6d, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x66,
	0x66, 0x6d, 0x2e, 0x76, 0x31, 0x22, 0x88, 0x01, 0x0a, 0x24, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f,
	0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c,
	0x22, 0x50, 0x0a, 0x26, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55,
	0x72, 0x6c, 0x22, 0xe7, 0x02, 0x0a, 0x16, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x46, 0x4d,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x44, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2e, 0x66, 0x66, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x46,
	0x4d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x08,
	0x77, 0x6d, 0x73, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x66, 0x66, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x46, 0x4d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x57, 0x4d, 0x53, 0x50, 0x75, 0x73, 0x68, 0x52, 0x07,
	0x77, 0x6d, 0x73, 0x50, 0x75, 0x73, 0x68, 0x1a, 0x50, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x28, 0x0a, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x1a, 0x51, 0x0a, 0x07, 0x57, 0x4d, 0x53,
	0x50, 0x75, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x77, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x96, 0x03, 0x0a,
	0x16, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x46, 0x4d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x44, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2e, 0x66, 0x66, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46,
	0x46, 0x4d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x51, 0x0a,
	0x0b, 0x77, 0x6d, 0x73, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x66, 0x66, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x46, 0x4d, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x57, 0x4d, 0x53, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x77, 0x6d, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x1a, 0x6f, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x50, 0x61, 0x74,
	0x68, 0x1a, 0x72, 0x0a, 0x09, 0x57, 0x4d, 0x53, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x6b,
	0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x53, 0x6b, 0x75, 0x22, 0x83, 0x01, 0x0a, 0x1d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x4d, 0x53, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64,
	0x12, 0x49, 0x0a, 0x08, 0x77, 0x6d, 0x73, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x66, 0x66, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x46, 0x4d, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x57, 0x4d, 0x53, 0x50, 0x75,
	0x73, 0x68, 0x52, 0x07, 0x77, 0x6d, 0x73, 0x50, 0x75, 0x73, 0x68, 0x22, 0x70, 0x0a, 0x1d, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x4d, 0x53, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x4f, 0x0a, 0x0a,
	0x77, 0x6d, 0x73, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x30, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x66, 0x66, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x46, 0x4d, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x57, 0x4d, 0x53, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x09, 0x77, 0x6d, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0xd2, 0x01,
	0x0a, 0x1e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x46, 0x46, 0x4d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x44, 0x0a, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2e, 0x66, 0x66, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x46, 0x46, 0x4d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x51, 0x0a, 0x0b, 0x77, 0x6d, 0x73, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x66,
	0x66, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x46, 0x4d, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x57, 0x4d, 0x53,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x77, 0x6d, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x22, 0x20, 0x0a, 0x1e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x46, 0x46, 0x4d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x42, 0xbf, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x66, 0x66, 0x6d, 0x2e, 0x76, 0x31, 0x42, 0x12, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65,
	0x61, 0x72, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x67, 0x65, 0x61, 0x2d, 0x6e, 0x65, 0x78, 0x74, 0x2f,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x64, 0x6b, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x66, 0x66, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x66, 0x6d, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x42, 0x46, 0x58, 0xaa, 0x02, 0x0e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x46,
	0x66, 0x6d, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5c,
	0x46, 0x66, 0x6d, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1a, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x5c, 0x46, 0x66, 0x6d, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x3a, 0x3a, 0x46,
	0x66, 0x6d, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_backend_ffm_v1_product_import_proto_rawDescOnce sync.Once
	file_backend_ffm_v1_product_import_proto_rawDescData []byte
)

func file_backend_ffm_v1_product_import_proto_rawDescGZIP() []byte {
	file_backend_ffm_v1_product_import_proto_rawDescOnce.Do(func() {
		file_backend_ffm_v1_product_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_ffm_v1_product_import_proto_rawDesc), len(file_backend_ffm_v1_product_import_proto_rawDesc)))
	})
	return file_backend_ffm_v1_product_import_proto_rawDescData
}

var file_backend_ffm_v1_product_import_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_backend_ffm_v1_product_import_proto_goTypes = []any{
	(*WaitForProductImportFileUploadParams)(nil),   // 0: backend.ffm.v1.WaitForProductImportFileUploadParams
	(*WaitForProductImportFileUploadResponse)(nil), // 1: backend.ffm.v1.WaitForProductImportFileUploadResponse
	(*ImportFFMProductParams)(nil),                 // 2: backend.ffm.v1.ImportFFMProductParams
	(*ImportFFMProductResult)(nil),                 // 3: backend.ffm.v1.ImportFFMProductResult
	(*ProcessImportWMSProductParams)(nil),          // 4: backend.ffm.v1.ProcessImportWMSProductParams
	(*ProcessImportWMSProductResult)(nil),          // 5: backend.ffm.v1.ProcessImportWMSProductResult
	(*CompleteImportFFMProductParams)(nil),         // 6: backend.ffm.v1.CompleteImportFFMProductParams
	(*CompleteImportFFMProductResult)(nil),         // 7: backend.ffm.v1.CompleteImportFFMProductResult
	(*ImportFFMProductParams_Image)(nil),           // 8: backend.ffm.v1.ImportFFMProductParams.Image
	(*ImportFFMProductParams_WMSPush)(nil),         // 9: backend.ffm.v1.ImportFFMProductParams.WMSPush
	(*ImportFFMProductResult_Image)(nil),           // 10: backend.ffm.v1.ImportFFMProductResult.Image
	(*ImportFFMProductResult_WMSRecord)(nil),       // 11: backend.ffm.v1.ImportFFMProductResult.WMSRecord
}
var file_backend_ffm_v1_product_import_proto_depIdxs = []int32{
	8,  // 0: backend.ffm.v1.ImportFFMProductParams.images:type_name -> backend.ffm.v1.ImportFFMProductParams.Image
	9,  // 1: backend.ffm.v1.ImportFFMProductParams.wms_push:type_name -> backend.ffm.v1.ImportFFMProductParams.WMSPush
	10, // 2: backend.ffm.v1.ImportFFMProductResult.images:type_name -> backend.ffm.v1.ImportFFMProductResult.Image
	11, // 3: backend.ffm.v1.ImportFFMProductResult.wms_records:type_name -> backend.ffm.v1.ImportFFMProductResult.WMSRecord
	9,  // 4: backend.ffm.v1.ProcessImportWMSProductParams.wms_push:type_name -> backend.ffm.v1.ImportFFMProductParams.WMSPush
	11, // 5: backend.ffm.v1.ProcessImportWMSProductResult.wms_record:type_name -> backend.ffm.v1.ImportFFMProductResult.WMSRecord
	10, // 6: backend.ffm.v1.CompleteImportFFMProductParams.images:type_name -> backend.ffm.v1.ImportFFMProductResult.Image
	11, // 7: backend.ffm.v1.CompleteImportFFMProductParams.wms_records:type_name -> backend.ffm.v1.ImportFFMProductResult.WMSRecord
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_backend_ffm_v1_product_import_proto_init() }
func file_backend_ffm_v1_product_import_proto_init() {
	if File_backend_ffm_v1_product_import_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_ffm_v1_product_import_proto_rawDesc), len(file_backend_ffm_v1_product_import_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_ffm_v1_product_import_proto_goTypes,
		DependencyIndexes: file_backend_ffm_v1_product_import_proto_depIdxs,
		MessageInfos:      file_backend_ffm_v1_product_import_proto_msgTypes,
	}.Build()
	File_backend_ffm_v1_product_import_proto = out.File
	file_backend_ffm_v1_product_import_proto_goTypes = nil
	file_backend_ffm_v1_product_import_proto_depIdxs = nil
}
